### ISSUE TITLE
Main Menu 'divider' (<li class="divider"></li>)

### ISSUE THREAD

**Issue by pknadella** [JeremyEnglert/JointsWP#102]
hi,
if a divider is placed at the end of the menu list ....i guess, then it will make the menu items look even
or 
else can remove divider from the start of the menu list.

I tried to fix this my self and as i am no programmer may efforts gone vain.....but with a little research I found that the divider is from the menu walker and in the walker only 'start_el' is used.....and by using  'end_el' can I place the 'divider' at the end of the list?.......

**Comment by JeremyEnglert** [comment]
Unfortunately, end_el will place a divider at the end of every list item, so you would end up with double dividers. Foundation 6 is going to have a new navigation, so I'm going to wait to see what the looks like before trying to make this fix.

**Comment by JeremyEnglert** [comment]
Closing this. F6 doesn't use a divider.
