### ISSUE TITLE
tab-bar html/css

### ISSUE THREAD

**Issue by uniquelylost** [JeremyEnglert/JointsWP#106]
nav-top-offcanvas.php

    <aside class="left-off-canvas-menu">

removing show-for-small-only fixes bug where if the off canvas menu is open when the browser window is expanded beyond small it turns white and remains open. Not alot of people probably would do that, I just noticed it while developing with jointswp :)

**Comment by JeremyEnglert** [comment]
Awesome! Thanks - this will be addressed in JointsWP 4.

**Comment by JeremyEnglert** [comment]
Closing this as it has been fixed in JointsWP 4. Thanks!
