### ISSUE TITLE
Missing menu item description ( in walker )

### ISSUE THREAD

**Issue by Erehr** [JeremyEnglert/JointsWP#107]
Can this function (having display menu item description) can be included in theme ? It's require adding menu-walker like in this article - http://www.wpbeginner.com/wp-themes/how-to-add-menu-descriptions-in-your-wordpress-themes/ but since JointsWP menu have it's own walker can it be  modified to do that too?

**Comment by JeremyEnglert** [comment]
The Walker in JointsWP 4 is much simpler, integrating something like the above should be fairly easy now.
