### ISSUE TITLE
Q: is it possible to install and use a customized minimal foundation.css?

### ISSUE THREAD

**Issue by COLABORATI** [JeremyEnglert/JointsWP#108]
Hi, with this workflow, is it possible to get rid of unneeded features from the foundation.css? 
Think of the zurb custom download site - from what I see bower installs always a version that has too much (if you just need a subset)? Is there an analogy of the zurb custom download site for bower?
Thanks for your attention!

**Comment by JeremyEnglert** [comment]
You can comment out the styles you don't need here: https://github.com/JeremyEnglert/JointsWP/blob/master/bower_components/foundation/scss/foundation.scss

Or, you can download a custom version of the CSS and enqueue that.

**Comment by COLABORATI** [comment]
Ah, ok, thank you very much for the quick response! Great! Have a nice day!
