### ISSUE TITLE
Why bower_components in repo?

### ISSUE THREAD

**Issue by COLABORATI** [JeremyEnglert/JointsWP#110]
I am not absolutely sure why this is a plus, that's why I am asking:
why do you put bower_components into this repo?

I would like to keep the bower_components in a different directory (e.g. "c") because I like short directory names, especially on web sites.

Is there any important reason why "bower_components" is not in .gitignore?

**Comment by COLABORATI** [comment]
ok, sorry, just found #82 .

For the customizers: here is a small bash script that sets up joints wp and changes the bower_components path: https://gist.github.com/COLABORATI/40ee0a32a53aaa59b014

However, I feel like that directory should not be in this repo, it will produce lots of noise over time.

**Comment by COLABORATI** [comment]
After woring a while with joints - I like the way you organized the files very much, I would have done it in a similar way - I finally come to the conclusion that putting bower_components in the repo was a mistake. Everything should be started with a new repo without this, however, we are free to do whatever we want, I am just complaining :)

**Comment by JeremyEnglert** [comment]
The theme directly includes files from bower_components, which is why it is included in the repo (this makes it easier to update using Bower). However, with JointsWP 4 (in development now), the bower_components directory will not exist in the repo.

Instead, there will be a vendor directory that pulls assets from the bower_components directory (if you're using Bower).

**Comment by COLABORATI** [comment]
The dependency is no problem, I think everybody who is using this will be able to 'bower install'. 
Hmm, so the vendor directory contains copies of files from bower_components?

**Comment by JeremyEnglert** [comment]
In the upcoming version, yes. The "vendor" directory will contain files from the bower_components directory.

If you want to update a vendor file, you will simply need to run 'Gulp Bower'. This will create a bower_components directory with the most updated assets. It will then clone those assets into the vendor directory.

You can see how it is setup here: https://github.com/JeremyEnglert/JointsWP/tree/4.0

**Comment by COLABORATI** [comment]
ah, ok, you are creating a vendor directory on the top level of the template file... hmmm. As there are only two files needed from bower_components atm I would prefer ```assets/js/vendor``` - but before going on - what would be a good place to discuss directory structure? Open a new issue?

**Comment by JeremyEnglert** [comment]
I'd love that - anything that can help improve the file structure is greatly appreciated it.

One reason I keep Foundation files separate is to make them easier to update.
