### ISSUE TITLE
archive.php line 7: "first" - what is it and why does it exist?

### ISSUE THREAD

**Issue by COLABORATI** [JeremyEnglert/JointsWP#112]
JointsWP/archive.php Line 7 there is this: 

 class="large-8 medium-8 columns first"

what is the 'first' and why can't I find a matching class for it? Is this an orphan from another project or is my search routine broken? This seems to be no foundation thing, also I could not find any scss file pointing to it. 

Thanks for your attention!

**Comment by JeremyEnglert** [comment]
Let me double check - I think that may have been something left over from an older version.

**Comment by JeremyEnglert** [comment]
This has been resolved in JointsWP 4 beta. Closing.
