### ISSUE TITLE
foundation 6?

### ISSUE THREAD

**Issue by titaniumbones** [JeremyEnglert/JointsWP#116]
well, I got the email about foundation 6 today! Do you have plans to update? thank you!

**Comment by JeremyEnglert** [comment]
Indeed! I've already started testing many of the F6 elements with JointsWP and everything is going pretty smoothly.

The biggest hurdle at this point will be the navigation options. These changed quite drastically, but with the help of @BrettMason, I think we're getting close!

**Comment by titaniumbones** [comment]
awesome.  Look forward to seeing what you come up with! Some of the new nav options look pretty intriguing.
