### ISSUE TITLE
Having Off Canvas menu display on tablet, and mobile views?

### ISSUE THREAD

**Issue by dfill** [JeremyEnglert/JointsWP#117]
Hello Jeremy,

Wondering if this is possible! I'm currently building out a client site and this is really the only sticking point I'm struggling with right now.

Any advice would help!

Thank you,
Douglas

**Comment by JeremyEnglert** [comment]
Sure is!

Check out this file: /parts/nav-top-offcanvas.php

Line 1 and Line 15 have visibility classes. Adjust those and you should be set.

**Comment by dfill** [comment]
Thanks a bunch Jeremy! Decided to use "show-for-medium-down" and it worked like a charm. Appreciate it!
