### ISSUE TITLE
Custom Roles in mu-plugins not working but plugin is active in network dash...

### ISSUE THREAD

**Issue by socratics** [JeremyEnglert/JointsWP#118]
Hello,

I am trying to rename the native WP roles to new names. I created a mu-plugin, and it is active b/c you can see it in the network admin, but the native roles are still showing...

Here is my code from the plugin...

<?php
	function wps_change_role_name() {
		global $wp_roles;
		if ( ! isset( $wp_roles ) )
			$wp_roles = new WP_Roles();
			$wp_roles->roles['administrator']['Director'] = 'Owner';
			$wp_roles->role_names['administrator'] = 'Owner';
			$wp_roles->roles['editor']['Manager'] = 'Owner';
			$wp_roles->role_names['editor'] = 'Owner';
			$wp_roles->roles['author']['Writer'] = 'Owner';
			$wp_roles->role_names['author'] = 'Owner';
			$wp_roles->roles['contributor']['Participant'] = 'Owner';
			$wp_roles->role_names['contributor'] = 'Owner';
			$wp_roles->roles['subscriber']['Reader'] = 'Owner';
			$wp_roles->role_names['subscriber'] = 'Owner';
	}
	add_action('init', 'wps_change_role_name');

Is there a more effective way of accomplishing this network wide with JointsWP?

Thanks in advance for your help...

**Comment by JeremyEnglert** [comment]
If you switch themes, does the code work?

**Comment by socratics** [comment]
Hi Jeremy,

I failed to mention that I am running MS, and the mu-plugins is in the network plugins folder... so if I am not mistaken it is not theme specific... but I tried it just to be safe on the main site, and it had no effect...

Thanks

**Comment by JeremyEnglert** [comment]
Have you tried the code on a default theme like 2015? If the code isn't working with any theme, my guess would be that the issue isn't related to the theme.

**Comment by JeremyEnglert** [comment]
Taking a look at your code, I think it needs to be more like this:

<?php
function wps_change_role_name() {
global $wp_roles;
if ( ! isset( $wp_roles ) )
$wp_roles = new WP_Roles();
$wp_roles->roles['administrator']['name'] = 'Director';
$wp_roles->role_names['administrator'] = 'Director';
$wp_roles->roles['editor']['name'] = 'Manager';
$wp_roles->role_names['editor'] = 'Manager';
...
}
add_action('init', 'wps_change_role_name');

**Comment by socratics** [comment]
Sorry for the delayed response... I tried that code but it didn't work... I am going to wait until the weekend, and set up a dummy install to test against native themes... Will update ASAP...
