### ISSUE TITLE
Can't export site at all with Duplicator!

### ISSUE THREAD

**Issue by dfill** [JeremyEnglert/JointsWP#119]
Hey there,

So I finished a website completely, developping locally. No complaints at all! Very easy to use. 

I tried exporting the site with the WordPress Duplicator plugin - however I got this error

    Fatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(C:/xampp/htdocs/simple/wp-content/themes/simple-joints/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/node_modules/nopt/examples,C:/xampp/htdocs/simple/wp-content/themes/simple-joints/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/node_modules/nopt/examples): The system cannot find the path specified. (code: 3)' in C:\xampp\htdocs\simple\wp-content\plugins\duplicator\classes\utility.php:170 Stack trace: #0 C:\xampp\htdocs\simple\wp-content\plugins\duplicator\classes\utility.php(170): DirectoryIterator->__construct('C:/xampp/htdocs...') #1 C:\xampp\htdocs\simple\wp-content\plugins\duplicator\classes\package.archive.php(232): DUP_Util::ListFiles('C:/xampp/htdocs...') in C:\xampp\htdocs\simple\wp-content\plugins\duplicator\classes\utility.php on line 170

I've tried exporting with a different plugin (All In One WP Migration), and get a very similar error. What's causing this? I need to get this site exported to live.

Any help would help!

**Comment by JeremyEnglert** [comment]
You don't want to include your node_modules when uploading to a live site. Set Duplicator to ignore that directory.

**Comment by dfill** [comment]
Works! Thank you!
