### ISSUE TITLE
SCSS compiling error

### ISSUE THREAD

**Issue by gabrielbajada** [JeremyEnglert/JointsWP#121]
Hey Jeremy,

I just downloaded Joints SCSS yesterday and when compiling CSS using gulp, I'm getting the following error: 

```
assets/scss/style.scss
Error: File to import not found or unreadable: ../../bower_components/foundation/scss/normalize
       Parent style sheet: stdin
        on line 15 of stdin
>> @import "../../bower_components/foundation/scss/normalize";
```

Any idea what it could be?

Thanks,

Gabriel

**Comment by gabrielbajada** [comment]
Sorry Jeremy, this was an internal error from our end. Nothing to do with Joints. Joints is still as awesome as always.

Cheers,

Gabriel

**Comment by AndrewSepic** [comment]
@gabrielbajada What were you doing that created this error?  I'm getting the same from a simple JointsWP Setup and I'm not sure what I can do to fix it.

**Comment by gabrielbajada** [comment]
@AndrewSepic I'm sorry but this was so long ago, I don't know. Looks like it must've been some screw-up from my end. Sorry buddy. Hope you manage to fix it.

**Comment by AndrewSepic** [comment]
@gabrielbajada Totally :-)  Somehow the JointsWP file structure wasn't complete and I was missing some folders in my local copy which was throwing the compiling errors.  Tracked them down and replaced them and all was good.
