### ISSUE TITLE
Any interest in including browser-sync in your gulpfile?

### ISSUE THREAD

**Issue by ayezee33** [JeremyEnglert/JointsWP#122]
Hey, 

Before I spend any time working on this, would you like to see browser-sync in your gulpfile? I use a few other WP based projects with browser-sync and it makes local dev nice and easy. 

I would need to do some added research but I guess what we would need to decide is if we want to support when people put JointsWP on a local box, therefore wrapping the dev URL in a proxy.

**Comment by JeremyEnglert** [comment]
JointsWP briefly had live-reload included, but I wasn't a huge fan of the setup.

I love browser-sync and think it would be a great addition - especially if it's easily removable/not required.

**Comment by konsulenten** [comment]
Hi 

I'm using GULP and CodeKit at the same time now; it works great... Browser-sync + scss-maps works like a charm...

**Comment by konsulenten** [comment]
Only thing. While developing you must change:
 comment out lines 28 and 29 in gulp file 
//    .pipe(rename({suffix: '.min'}))
//    .pipe(minifycss())

and change to un-minified css i enqueue.php
    wp_enqueue_style( 'site-css', get_template_directory_uri() . '/assets/css/style.css', array(), '', 'all' );

In Codekit. Do not process JavaScript.
Process style.scss to css/style.css

**Comment by arielnoname** [comment]
@ayezee33 Do you have a gulpfile with browsersync for JointsWP already? I'm starting a project and before doing it on my own maybe I can borrow yours and when @JeremyEnglert looks over it, maybe he can put that commented on the Gulpfile as well.

I was trying it with FoundationPress (it has browsersync out of the box) and it was really amazing, never used it before, its really fast and works like a charm

**Comment by JeremyEnglert** [comment]
Let me take a stab at this over the weekend. I've been playing with BrowserSync lately and really like it.

**Comment by arielnoname** [comment]
Its really really nice, especially when you are one of those anxious kind
of people (myself) who hits cmd+r 3 times lol

**Comment by JeremyEnglert** [comment]
The current hurdle is that Browsersync requires a URL - which I guess isn't a huge deal. But it does create another hurdle/annoyance - especially if you aren't using Browsersync.

Maybe it should be included - but commented out by default?

**Comment by ayezee33** [comment]
Yeah I remember when I first started looking into this I wasn't sure how to handle the root URL since some people will have the project set up differently. 

I use a project called Roots on a lot of my local dev. I won't say I understand exactly what is going on but they use a mainfest.json file to pipe the dev URL into the gulpfile. 

https://github.com/roots/sage/blob/master/gulpfile.js
https://github.com/roots/sage/blob/master/assets/manifest.json

I do not know if this is an easy implementation or not.

**Comment by JeremyEnglert** [comment]
Does that automatically grab the dev URL or do you have to edit the manifest file each time?

**Comment by ayezee33** [comment]
You have to manually specify the Dev URL

**Comment by arielnoname** [comment]
You can check the gulpfile from FoundationPress, works very good. Has a
javascript snippet for the url handling that you have to put just before
/body

**Comment by andycochran** [comment]
+1 to "commented out by default"

**Comment by JeremyEnglert** [comment]
I'm thinking it would be a new Gulp task - something like "gulp sync" that would be commented out by default. It would be similar to "gulp watch", but with BrowserSync enabled. 

Since the URL has to be manually inputted, it's not a big deal to un-comment the code for those who want to use it.

**Comment by andycochran** [comment]
Could you require the URL be included in the command? 
```
gulp sync --url [localhost]
```

**Comment by JeremyEnglert** [comment]
@andycochran I definitely think that's possible. 

I'm working on this now in a new branch: https://github.com/JeremyEnglert/JointsWP/tree/browser-sync

BrowserSync is hooked up, however, the "style injecting" doesn't seem to be working. Trying to figure out why.

**Comment by JeremyEnglert** [comment]
Check it out: https://github.com/JeremyEnglert/JointsWP/blob/browser-sync/gulpfile.js

Run 'gulp browser-sync' to watch files. Any JS or PHP changes will trigger a full page reload. Any Sass changes will be "injected" into the browser without a page reload. 

Thoughts?

**Comment by Shipwreck** [comment]
Working great for me - thanks!

**Comment by JeremyEnglert** [comment]
This can now be found here: https://github.com/JeremyEnglert/JointsWP/tree/gulp-updates

Going to fix some other things in the Gulp file and then push it live.

**Comment by Shipwreck** [comment]
If you are irritated by Browser Sync messages interfering with top-bar-right menu items:

```
    browserSync.init(files, {
      // URL of local site
      proxy: "http://localhost/stretcheveryday/",
      notify: false,
    });
```

Perhaps there is a more elegant solution but it works for me!

**Comment by arielnoname** [comment]
I think thats the correct way to do that

**Comment by JeremyEnglert** [comment]
This was merged into the master branch today. Closing.
