### ISSUE TITLE
jQuery load order and plugin BNE Flyouts

### ISSUE THREAD

**Issue by konsulenten** [JeremyEnglert/JointsWP#126]
Hi

I'm using the plugin BNE Flyouts. Because Foundation jQuery loads in the footer, the scripts added on the page by the plugin does not work. 

I get the error code: "ReferenceError: Can't find variable: jQuery"

On the development version of JointsWP we got it working by adding the following to enqueue-scripts.php:
    function bne_flyout_move_output_in_wp_footer() {
    remove_action( 'wp_footer', 'bne_flyout_footer_output' );
       add_action( 'wp_enqueue_scripts', 'bne_flyout_footer_output', 99 );
   }
    add_action( 'after_setup_theme','bne_flyout_move_output_in_wp_footer' );

What could be the reason that this no longer work? 

Thanks for all help.

**Comment by JeremyEnglert** [comment]
On line 9 in enqueue-scripts.php, change "true" to "false" - this will load jQuery in the header.

https://github.com/JeremyEnglert/JointsWP/blob/master/assets/functions/enqueue-scripts.php
