### ISSUE TITLE
Task 'vendor-js' is not in your gulpfile

### ISSUE THREAD

**Issue by vitaligent** [JeremyEnglert/JointsWP#130]
Hello! It looks like the old "vendor-js" task is referenced in the default gulp task. Removing it seems to fix it.

**Comment by JeremyEnglert** [comment]
Thanks! This has been resolved.

https://github.com/JeremyEnglert/JointsWP/commit/5b6ff6cb0228fcac14128b6aac75f9cd99e1d8bf
