### ISSUE TITLE
Topbar Navigation - Dropdown links are dead.

### ISSUE THREAD

**Issue by iamchaka** [JeremyEnglert/JointsWP#131]
I created a menu structure. I select both menu settings (Main Menu and Footer). The footer links work, but the sub nav in the top bar are dead. You can click on them, but they don't go anywhere. But at the bottom of the page, all of them work find.  This is a fresh install with no customization. I just added pages and then created a menu. Anyone else see this?

**Comment by JeremyEnglert** [comment]
This is a known issue with Foundation. They're hoping to release a fix this week.

**Comment by iamchaka** [comment]
Very cool. Thanks a lot man.

**Comment by JeremyEnglert** [comment]
This has been resolved.
