### ISSUE TITLE
Dropdown Issue

### ISSUE THREAD

**Issue by nusserstudios** [JeremyEnglert/JointsWP#135]
I did some testing and it seems like its something with the Menu Walker and menu dropdown. The menu items output ok, but they won't allow you to click through. I tried on a fresh install, and I'm still having some issues. I will continue to work on it, but just giving you a heads up. I thought it maybe because I bumped the bower version to 6.0.4, but same issue no matter what version.

**Comment by JeremyEnglert** [comment]
This was a Foundation issue. It has been resolved.

**Comment by mediamr** [comment]
I also have this issue with this. bower version 6.0.4. Wich version is fixed?

**Comment by JeremyEnglert** [comment]
I had to download directly from GitHub to get it to work - not 100% sure why. I may open that as an issue on the Foundation repo.

**Comment by JeremyEnglert** [comment]
Reopening as it looks like Chris is still working on some fixes: https://github.com/zurb/foundation-sites/pull/7344

**Comment by zurbchris** [comment]
I just changed a few things with how a user can click through a menu. Mostly focused on mobile devices, since there were some differing opinions on what a link should or should not do if one is using a touch screen... should get merged in master today, and default action hasn't changed.

**Comment by JeremyEnglert** [comment]
This has been resolved.
