### ISSUE TITLE
flexbox grid?

### ISSUE THREAD

**Issue by titaniumbones** [JeremyEnglert/JointsWP#136]
Have you tried, or do you have any interest at all in incorporating, the new flexbox grid? WHat would be gained and lost by making hte switch?

**Comment by andycochran** [comment]
Browser support. :cry: 

> The flex grid is only supported in Chrome, Firefox, Safari 6+, IE10+, iOS 7+, and Android 4+. Flexbox is supported in Android 2, but not reliably enough for use with this grid. ([View flexbox browser support.](http://caniuse.com/#feat=flexbox)) We recommend only using the flex grid on projects that can live with purely cutting-edge browser support.

Would be a good case for a fork/branch.

**Comment by JeremyEnglert** [comment]
Similar to in Foundation 6, the Flex Grid isn't included by default, but its easy to add: http://foundation.zurb.com/sites/docs/flex-grid.html

"The flex grid is not enabled by default. To use the default CSS, add the export mixin for the flex grid, and remove the default grid."
