### ISSUE TITLE
F6 + Archive Accordion

### ISSUE THREAD

**Issue by ghost** [JeremyEnglert/JointsWP#138]
I was wondering if the accordion archive loop/template are still supported on F6?

I updated the files from the F5 version according to the F6 docs since they weren't included in the latest release, but...
- the [all closed](http://foundation.zurb.com/sites/docs/accordion.html#all-closed) option doesn't work,  the first option stays open on refresh.
- get the following errors whenever I click on the accordion to open/close, and the "yellow" error I get when I press the ⌘ button... never seen that before...

<img width="1439" alt="screen shot 2015-12-02 at 8 03 53 pm" src="https://cloud.githubusercontent.com/assets/15204820/11549042/884037b8-9930-11e5-9b87-1762f8ca38ed.png">

Here is a draft of my loop-archive-accordion.php...

``` php
        <ul id="main_container" class="accordion" data-accordion data-allow-all-closed="true">
            <?php if (have_posts()) : while (have_posts()) : the_post(); ?>                       
                  <li id="panel_container" class="accordion-item">
                    <a href="#panel-<?php the_ID(); ?>" role="tab" class="accordion-title" id="panel-<?php the_ID(); ?>-heading" aria-controls="panel-<?php the_ID(); ?>">
                        <h1 class="panel_title"><?php the_title(); ?></h1>
                            <h3 class="panel_concept"><?php echo get_post_meta( get_the_ID(), 'rf_title', true ); ?></h3>
                            <?php echo get_avatar( get_the_author_meta( 'ID' ), 'avatar-thumb-icon', 32 ); ?>
                            <i class="fa fa-eye fa-2x panel_view_icon"></i>
                    </a>


                    <div id="panel-<?php the_ID(); ?>" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="panel1d-heading">
                        <h1 class="np-direct"><a href="<?php the_permalink() ?>" rel="bookmark" title="<?php the_title_attribute(); ?>"><?php the_title(); ?></a></h1>
                        <h3 class="nr-direct"><?php echo get_post_meta( get_the_ID(), 'nr_direct', true ); ?></h3>
                        <h3 class="nn-direct"><?php echo get_post_meta( get_the_ID(), 'nn_direct', true ); ?></h3>

                        <a href="<?php the_permalink() ?>" id="view_scr_btn" class="button expand" value="_self">go to this thing</a>
                    </div>
                  </li>
            <?php endwhile; ?>
        </ul>

    <?php joints_page_navi(); ?>

    <?php else : ?>
        <?php get_template_part( 'parts/missing', 'content' ); ?>
    <?php endif; ?>

```

Any ideas on how I can get this working?

**Comment by JeremyEnglert** [comment]
I did remove this from JointsWP 4 simply because I didn't have the time to update it to the new syntax. Let me take a stab at this over the weekend.

**Comment by socratics** [comment]
Thanks Jeremy... Just wasn't sure... glad that it will continue to be supported... It is a kick ass feature...

**Comment by socratics** [comment]
Hi Jeremy... hope all is well... I was wondering if you got around to touching this? I am almost done with the basic elements of the archive, and don't want to delve any deeper for fear that the things I will hack are just part of the fix you planned... Cheers

**Comment by JeremyEnglert** [comment]
Hi, sorry for the slow follow-up.

I was working on this a bit last night. The tricky part is getting it setup to work as a template part, because the loop needs to be setup a little differently. 

However, let me gather the code and shoot it over to you. It works - just not 100% ideal to be integrated into the starter theme yet.

**Comment by socratics** [comment]
No worries... just touching base on it... if you would like to take a look at the implementation that is working fairly ok on my project site let me know, and I can give you access, or access to the project Git repo on offline channels...

I will await the code you send over, and take a look at implementing it into my current structure...

P.S. setting up the loop was especially complicated on my end, and any suggestions on improving it is most welcome... but it is the console error I was getting that concerned me... Uncaught TypeError: this.rules.split is not a function...

**Comment by socratics** [comment]
Hey Jeremy... Just touching base on this... sort of rounding out the rest of the project, and this is last on the list... you mentioned you would send the code... did I just miss it?

**Comment by JeremyEnglert** [comment]
@socratics - this should work: https://gist.github.com/JeremyEnglert/22bab1edc25e5a7d4eeb
