### ISSUE TITLE
F6 + Reveal/Modal Baked In Sizes Conflict

### ISSUE THREAD

**Issue by socratics** [JeremyEnglert/JointsWP#139]
Noticed what appears to be a conflict in the JWP theme with using the different [baked in F6 sizes] (http://foundation.zurb.com/sites/docs/reveal.html#sizing) of reveals/modals (i.e. small, medium, large (default), and xlarge)...

Not sure where it is coming from, my thoughts are js, but the JWP css assigns left:420px to the active modal, and this conflicts with position/size of the reveal. It fixed for me when I change the left to 0 and added right:0 in dev tools chrome. The modal was centered, and true to size... But I am unable to locate where to adjust this so that it is global...

<img width="159" alt="screen shot 2015-12-03 at 1 18 01 pm" src="https://cloud.githubusercontent.com/assets/15204820/11569822/f4efe656-99c1-11e5-84f8-f4729422af63.png">

Digging around I also saw this in the assets/css/style.css... Not sure if this is relevant, but the .large is set 90% and in the F6 docs it appears that the default for .large is 80%... again... just an observation...

<img width="394" alt="screen shot 2015-12-03 at 1 31 52 pm" src="https://cloud.githubusercontent.com/assets/15204820/11569917/677e480c-99c2-11e5-9aa9-023f113e3ed1.png">

Edit: I was using the .xlarge size for my testing... and only did browser testing with the other sizes...

**Comment by JeremyEnglert** [comment]
JointsWP doesn't including any styling that should conflict with Foundation styles. Do you have a link I can check out? 

I also see a couple issues on GitHub that may be related:
https://github.com/zurb/foundation-sites/issues/7333
https://github.com/zurb/foundation-sites/issues/7282

**Comment by socratics** [comment]
Awesome... Thanks Jeremy. I did notice on the F6 docs that there is a note... but thought this might be something worth mentioning... I will keep an eye on those threads... evolution at its finest... haha...

<img width="817" alt="screen shot 2015-12-03 at 1 46 55 pm" src="https://cloud.githubusercontent.com/assets/15204820/11570272/607b8b76-99c4-11e5-9070-1d619bc85c68.png">


Cheers...

**Comment by JeremyEnglert** [comment]
I believe this was an F6 issue that has been resolved. Feel free to reopen if there is still an issue.
