### ISSUE TITLE
Option/Alt + Tab reveal off canvas navigation...

### ISSUE THREAD

**Issue by socratics** [JeremyEnglert/JointsWP#141]
Hi...

I was skipping back and forth between my site and other apps, and I accidentally pressed option/alt + tab, which suddenly opened my off canvas navigation. This happens on the JWP demo site as well, but not on jwp.com... Any thoughts on how to easily disable this?

To replicate just go to the demo site, and press option/alt + tab... I am using mac, not sure if/key combination on not~Mac...

Not sure if this is a theme thing, or a foundation thing... or even a bug per say, but it is annoying since I don't have my off canvas nav set up, and not sure I want it to show at all... 

Thanks...

**Comment by JeremyEnglert** [comment]
Very odd indeed - let me look into this.

If you aren't using off-canvas at all, you can remove the off-canvas container from your header.php. That would be a good temporary fix.

**Comment by socratics** [comment]
Thanks... that temp fix did work... so obvious too...

**Comment by JeremyEnglert** [comment]
@socratics - check this out: https://github.com/JeremyEnglert/JointsWP/issues/158

Does that help?

**Comment by socratics** [comment]
@JeremyEnglert Awesome! Helps a ton. Worked it out, and it is no longer an issue... You guys rock!

**Comment by JeremyEnglert** [comment]
Awesome! Glad it's working for you.

Closing this out.
