### ISSUE TITLE
Undefined variable: tag_arr in related-posts.php

### ISSUE THREAD

**Issue by Freelancealot** [JeremyEnglert/JointsWP#142]
Getting the following error when I include the related posts function on the loop-single.php file.

Notice: Undefined variable: tag_arr in /public_html/.../wp-content/themes/Horizon-Grenada/assets/functions/related-posts.php on line 8

This is what's on line 8: $tag_arr .= $tag->slug . ',';

It is displaying a related post underneath the error notice.

I got rid of the warning by adding $tag_arr = ''; right before global $post;

But there may be a more elegant way of dealing with it.

Cheers
Tracy

**Comment by JeremyEnglert** [comment]
Having a hard time replicating this issue.

Actually, I'm having a hard time getting this function to work at all.

Diving into it now.

**Comment by JeremyEnglert** [comment]
This has been resolved.

https://github.com/JeremyEnglert/JointsWP/commit/850492598529d56d41eb7438cf90e61d90b42960

**Comment by Freelancealot** [comment]
Great thanks, Jeremy.

From:  Jeremy Englert <notifications@github.com>
Reply-To:  JeremyEnglert/JointsWP
<reply+009e4fa5bab44ab5658acdc8c9baa28292a6498a3d376a2f92cf00000001130d86169
2a169ce073bbed2@reply.github.com>
Date:  Fri, 25 Mar 2016 16:04:54 -0700
To:  JeremyEnglert/JointsWP <JointsWP@noreply.github.com>
Cc:  Tracy Shorrock <info@freelancealot.co.uk>
Subject:  Re: [JointsWP] Undefined variable: tag_arr in related-posts.php
(#142)


This has been resolved.

8504925 
<https://github.com/JeremyEnglert/JointsWP/commit/850492598529d56d41eb7438cf
90e61d90b42960> 


You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/JeremyEnglert/JointsWP/issues/142#issuecomment-201571223
>
