### ISSUE TITLE
Remove Emoji

### ISSUE THREAD

**Issue by arielnoname** [JeremyEnglert/JointsWP#143]
I think its a good idea to remove emoji from WP by default.

Taken from FoundationPress:
```
// Emoji detection script.
remove_action( 'wp_head', 'print_emoji_detection_script', 7 );

// Emoji styles.
remove_action( 'wp_print_styles', 'print_emoji_styles' );
```

What do you say?
Cheers

**Comment by JeremyEnglert** [comment]
I definitely add this to every site I launch, however, maybe it's best if this is left up to the end user?

Or maybe it can be treated like the CPT function - which is included, but off by default.

**Comment by arielnoname** [comment]
I really doubt that most sites use this. And I also think that developers who use WP and Joints or any starter theme like this one, use it for "types of webpages" that doesn't use those emoji. But then again, I may be very wrong.

I think I would be nice to at least have those 2 lines of code commented in the file.

**Comment by JeremyEnglert** [comment]
The more I think about this, the more I like the idea.

**Comment by arielnoname** [comment]
For the sake of irony: :ok_hand: :ok_hand:

**Comment by badcat** [comment]
I'm all for less emoji (and emoticons ;) , but I thought the point of getting emoji into WP 4.4 was to make it get closer to supporting a wider range of Unicode 8+ 4byte etc (utf8mb4) charactersets including Japanese, Chinese, Korean, and other HAN Asian Multi-characters?  
>^. .^<    and  ¯\_(ツ)_/¯

**Comment by andycochran** [comment]
:-1: 

JointsWP is amazing; I love it. But I think it should make fewer assumptions about what the developer is trying to do. It could be even more bare-bones than it is.

**Comment by arielnoname** [comment]
I would vote for commented lines on cleanup.php, enabled emoji by default but we don't have to go to our "snippets.txt" every time we start a project.

(y)

**Comment by JeremyEnglert** [comment]
Love all the input from everyone!

@badcat is correct - Emoji support is the stepping stone to bigger things.

@andycochran - You hit my biggest concern right on the head. It seems like a great feature that most people would use (making an assumption here), but is it just another item to remove for some people? Are there any other items you think should be removed to make it more bare-bones? 

@arielnoname - I like the idea of including the snippet in the functions.php file. 

Note: The WP Emoji Support does conflict with the Orbit slider. So there is a pretty good reason for having this available as an option.

**Comment by JeremyEnglert** [comment]
This was added to the functions file. By default, it is commented out. Remove the comments and all emoji related scripts will not load.
