### ISSUE TITLE
Question: Why is the unminified CSS and JS default?

### ISSUE THREAD

**Issue by arielnoname** [JeremyEnglert/JointsWP#144]
Out of curiosity... I think the minified versions should be the default in the sass version since we don't touch them.

Cheers!

**Comment by JeremyEnglert** [comment]
I completely agree - however, not everyone who uses Joints uses a compiler that also creates a minified file.

When JointsWP 4 first launched, it used the minified files. However, it led to some confusion for users who were not using Gulp as they thought their Sass changes were not being applied. 

Unfortunately, it seems like only a small percentage of JointsWP users utilize Gulp :(

**Comment by arielnoname** [comment]
Oh well, in that case...

Thats a shame, because now Foundation uses Gulp. I think it's better to keep this kind of things close to home. But that's me.

Cheers

**Comment by socratics** [comment]
Would you mind pointing out how to switch to the min being the default if you are using gulp + sass?

**Comment by arielnoname** [comment]
I think you have to edit assets/functions/enqueue-scripts.php

From 
```
wp_enqueue_script( 'foundation-js', get_template_directory_uri() . '/assets/js/foundation.js', array( 'jquery' ), '6.0', true );
```
To
```
wp_enqueue_script( 'foundation-js', get_template_directory_uri() . '/assets/js/foundation.min.js', array( 'jquery' ), '6.0', true );
```
Same for CSS

**Comment by JeremyEnglert** [comment]
Thanks @arielnoname!

**Comment by arielnoname** [comment]
My pleasure @JeremyEnglert

**Comment by socratics** [comment]
Thank you @arielnoname... apparently it was already set... cheers...

**Comment by socratics** [comment]
So I now I am getting a weird error in my console related to the min file... see screengrab... any ideas why this is?

<img width="1440" alt="screen shot 2015-12-16 at 5 17 37 pm" src="https://cloud.githubusercontent.com/assets/15204820/11855583/20200c00-a419-11e5-943b-b226ea3fe8dc.png">

**Comment by JeremyEnglert** [comment]
What version of Foundation are you running?

The original launch of 6.0 had some issues with minified files.

**Comment by socratics** [comment]
Upgrading via bower cleared it right up... dope... thanks man...
