### ISSUE TITLE
empty license field in package.json

### ISSUE THREAD

**Issue by df-nakami** [JeremyEnglert/JointsWP#145]
Hi Jeremy,

rather small issue:
npm install throws a warning:
"npm WARN package.json JointsWP-sass@4.0.0 No license field."

A valid SPDX license expression would be "GPL-2.0 AND MIT"

Thanks, for your work!
best Daniel

**Comment by JeremyEnglert** [comment]
Thanks! I'll get this fixed before the next push.

**Comment by JeremyEnglert** [comment]
Thanks @df-nakami - this has been fixed!

https://github.com/JeremyEnglert/JointsWP/commit/6487938bdbb506a927461f00763f67ef19412b6f
