### ISSUE TITLE
$global-margin repeated in _settings.scss

### ISSUE THREAD

**Issue by jwindeknecht** [JeremyEnglert/JointsWP#146]
In the _settings.scss, $global-margin is used twice, once on line 64 and again on 66.

    63  ...
    64  $global-margin: 1rem;
    65  $global-padding: 1rem;
    66  $global-margin: 1rem;
    67  ...

Not world ending by any means, just a heads up. :)

**Comment by JeremyEnglert** [comment]
Thanks! This has been resolved.

https://github.com/JeremyEnglert/JointsWP/blob/master/assets/scss/_settings.scss
