### ISSUE TITLE
Gulp not updating/compiling assets/css folder/files

### ISSUE THREAD

**Issue by socratics** [JeremyEnglert/JointsWP#147]
Hello,

So I am new to gulp, and this workflow. For some reason I am having issues updating style.css, and compiling into the min file. I am also seeing an inconsistency when I add/update custom files in the folder, and gulp it. I even try gulp styles, and it doesn't work consistently.

I am sure this is an issue with my personal installation, but couldn't find any doc that fit my scenario, and figured it would be better to ask then to try to piece together snippets from various sources...

How would I go about troubleshooting this? And is there a quick fix? I tried reinstalling the theme, and gulp to see if it was a "mapping" issue, but that didn't have any noticeable effect...

Cheers

**Comment by JeremyEnglert** [comment]
Hi @socratics,

Glad you're taking a stab at trying Gulp!

What error are you getting?

**Comment by socratics** [comment]
Hey Jeremy... That is the thing... I am not getting any errors, and the gulp process seems to be flowing smoothly whether the changes take effect or not... at least in the same way it has since I started using it a few weeks back... that is what is baffling me... 

I attached a copy of the output from the gulp process... the xxxxxx- in the path is just my effort at network security... haha... jk... no I'm not... not sure what is safe to post publicly or not... I can send more privately if you want...

[gulp-output.txt](https://github.com/JeremyEnglert/JointsWP/files/62912/gulp-output.txt)

Cheers

**Comment by JeremyEnglert** [comment]
This is an odd one - because your Gulp output looks perfect.

What file are you putting your custom styles into?

Try running "gulp watch" and then making your change. Does Gulp respond to the change?

**Comment by socratics** [comment]
I tried gulp watch earlier, and again just to make sure, but if I make a change to style.css, it does not compile into the min, and does not take effect on the site...

I have some custom files in the css folder for framework styles etc., and what is weird is that if the file is already in the folder from a previous session, it compiles, and I can update it successfully.

I tried adding a new file today with some custom styles, just like the other files that are working properly, but when I gulped, the new file did not show in the sources on dev tools, and the changes in them did not take effect.

Again, I can update the files already in there successfully, but the new one didn't even get compiled at all into the theme's output... make sense?

I checked permissions on the folders, and that wasn't an issue (anymore... haha...)
I checked that the custom files were in the assets/css folder on the server, and that the file on the server matched the file on my local...

Weird huh?

**Comment by socratics** [comment]
P.S. I am able to successfully make changes to the scss folder, and effect some styles globally. So there's that... but there are global styles overwritten by the style.css file that I would like to change, rather than target from a custom css file... Last week I even resorted to changing the min file directly on the dev server just to get something looking right for a demo call...

**Comment by JeremyEnglert** [comment]
So you'll want to make all of your changes to the files in the /scss folder - these are the Sass files. When you make a change to these files, it is compiled into the /css files. I'm working on improving the documentation about this, but check out this page - it describes the workflow pretty well: http://jointswp.com/docs/gulp/

**Comment by socratics** [comment]
Yeah this is a bit hazy for me... I get the gulp process itself to a certain extent, but not the workflow to customize the styles... So the _main.scss and the _settings.scss are the main points to customize? Do these two files make up all the styles in the css/style.css?

So is it better to create a custom /scss/_custom.scss file and fill it with custom css, or is it better to just use a css/custom.css?

Or am I still not getting this, cause it still feels a bit unclear for me... mea culpa...

**Comment by JeremyEnglert** [comment]
**So the _main.scss and the _settings.scss are the main points to customize?**
Correct. Main.scss is where you'll end up putting most of your custom styles. Settings.scss 

**Do these two files make up all the styles in the css/style.css?**
No, there are many other parts to the styles.css. You can see all of the pieces by looking at the styles.scss file here: https://github.com/JeremyEnglert/JointsWP/blob/master/assets/scss/style.scss

**So is it better to create a custom /scss/_custom.scss file and fill it with custom css, or is it better to just use a css/custom.css?**
Put all of your custom styles in scss/_main.scss - this is the easiest approach. You can also create your own file like scss/_custom.scss if you want - just be sure to add it to the styles.scss file like above.

Let me know if this helps any :)

**Comment by socratics** [comment]
Ok. I am starting to get this based on the documentation, and your response, but for some reason it is not working on my setup the way you are explaining.

An example using out of the box theme files. In the [_settings.scss](https://github.com/JeremyEnglert/JointsWP/blob/master/assets/scss/_settings.scss#L60) its $body-background: $white;... and in the [style.css] (https://github.com/JeremyEnglert/JointsWP/blob/master/assets/css/style.css#L1329) it is .body {background: #fefefe;}...

So is the workflow supposed to be ignore the _settings.scss, overwrite the style.css using the _main.scss with a .body {background:color;}? And theoretically, the first time you gulp the site, shouldn't these two styles sync/compile?

When I change [_settings.scss](https://github.com/JeremyEnglert/JointsWP/blob/master/assets/scss/_settings.scss#L60) to my custom color #e7e7e7, or even when I use the [$light-gray](https://github.com/JeremyEnglert/JointsWP/blob/master/assets/scss/_settings.scss#L55) I customized with #e7e7e7, and gulp/gulp styles... it does not effect the style.css or the min... and the site loads as [.body {background: #fefefe;}](https://github.com/JeremyEnglert/JointsWP/blob/master/assets/css/style.css#L1329)

And if I do have to overwrite the style.css file with _main.scss, wouldn't it be easier to just copy/paste the contents of style.css into _main, and remove/change styles, rather than piece mailing each style?

Or am I still not getting this?

**Comment by JeremyEnglert** [comment]
**An example using out of the box theme files. In the _settings.scss its $body-background: $white;... and in the style.css it is .body {background: #fefefe;}...**
If you look in the _settings.scss file, you'll see that there is a variable called "$white" with the value of "#fefefe". This allows you to use "$white" in your Sass, which will compile to "#fefefe" in your CSS. If you want to change the background color, simply change $body-background to any color you would like.

You can make changes directly to the _settings.scss file - they won't be overridden. You can even add your own variables to this file.

**Comment by socratics** [comment]
Awesome... I am tracking now... thanks man... I am closing this out...
