### ISSUE TITLE
Widescreen Flex Video Embeds 

### ISSUE THREAD

**Issue by andycochran** [JeremyEnglert/JointsWP#148]
So, `scripts.js` automatically wraps YouTube/Vimeo embeds with a flex video wrapper. However, there's no option for the `.widescreen`. Could we add this programmatically, based on the iframe's `width=""` and `height=""` attributes?

**Comment by JeremyEnglert** [comment]
This would be awesome.

So something like "if video is X by Y, then add .widescreen", 

Let me take a stab at this.

**Comment by andycochran** [comment]
I used your line from `scripts.js` to do this in a theme I'm working on. I just defaulted to `.widescreen`. But if I get it working dynamically, I'll let ya know. Any suggestions on how to go about it?

**Comment by JeremyEnglert** [comment]
We might be able to use jQuery .innerHeight() & .innerWidth(); to determine the height/width ratio and dynamically add the class.

**Comment by andycochran** [comment]
This works: 
```js
jQuery('iframe[src*="youtube.com"], iframe[src*="vimeo.com"]').each(function() {
  if ( jQuery(this).innerWidth() / jQuery(this).innerHeight() > 1.5 ) {
    jQuery(this).wrap("<div class='widescreen flex-video'/>");
  } else {
    jQuery(this).wrap("<div class='flex-video'/>");
  }
});
```
I'll PR…
