### ISSUE TITLE
Request Snippet: Toggle Archive Page Template On Click

### ISSUE THREAD

**Issue by socratics** [JeremyEnglert/JointsWP#149]
Hey Jeremy... this is more of a request... than an issue... so no rush...

I just need some help on a snippet that toggles the parts template in the archive.php on click. Some context... I have a sidebar menu with two view options... Grid + List/Full... The grid is the default template the user will see, but if they click on the list link/icon it will swap to the list parts template using either a simple jQuery toggle snippet in the assets/js/scipts or the foundation toggle...

So basically how to toggle these two elements within the archive.php file with a click without breaking it... haha

	  <?php get_template_part( 'parts/loop', 'archive-grid' ); ?>
          
          <?php get_template_part( 'parts/loop', 'archive-accordion' ); ?>

I suppose in the end it would be cool to fadeToggle with jQuery, or motionUI fade-in/fade-out for some cool effects....

Not sure if this is as simple as I think it is... but it would be really cool, and my searches online have yielded zero working versions...

![giphy 1](https://cloud.githubusercontent.com/assets/15204820/11821673/b5237e72-a338-11e5-8b23-4cffaae3863b.gif)

**Comment by JeremyEnglert** [comment]
You won't be able to use Foundation's Toggler as that is meant for adding/removing CSS class.

I'm actually not sure the best way to approach this, because the template part code is PHP, which I don't think you'll be able to directly change using a toggle like switch.

**Comment by socratics** [comment]
Damn... I figured as much... thanks for taking the time to consider it... If I come across a fix, I will report back here to share...

**Comment by socratics** [comment]
P.S. we can close this if you want... so it doesn't clutter the board...

**Comment by JeremyEnglert** [comment]
:+1:
