### ISSUE TITLE
Class wp-sticky is added to all posts

### ISSUE THREAD

**Issue by adowdle** [JeremyEnglert/JointsWP#155]
The remove_sticky_class() function adds wp-sticky to all posts, regardless of sticky status.

**Comment by JeremyEnglert** [comment]
Well that's pretty annoying! Let me see if I can get that fixed.

**Comment by anyway** [comment]
I have the same problem. Is there already a workaround?

**Comment by JeremyEnglert** [comment]
For now, you can remove the remove_sticky_class() function from assets/functions/cleanup.php.

https://github.com/JeremyEnglert/JointsWP/blob/e0cba5bd36e6436491f31d62ff833bf5de42a693/assets/functions/cleanup.php

**Comment by anyway** [comment]
Thanks, that works for me, as long as there is no other solution for this.

**Comment by JeremyEnglert** [comment]
This has been fixed.

https://github.com/JeremyEnglert/JointsWP/commit/b16f319ab34c37740d4d3257c439a6f4004e706b
