### ISSUE TITLE
Keyboard issue with menu

### ISSUE THREAD

**Issue by alastair38** [JeremyEnglert/JointsWP#158]
This may have something to do with #135 so I'm guessing it's a Foundation issue, but thought I'd give you a heads up.

Although tabbing to menu items via the keyboard is fine (I'm using *Chrome version  47.0.2526.111 m*), hitting 'Enter' when a menu item is focused does not follow the link. 'Ctrl' + 'Enter' does work to open the link in a new tab. There is no problem with non-menu links and there is no problem when using the mouse. 

Removing the attribute *data-responsive-menu="accordion medium-dropdown"* allows you to properly access the menu items via the keyboard, but obviously breaks the dropdown.

I'm using Foundation 6.1.1

**Comment by alastair38** [comment]
Just a note to say that I've posted this to the Foundation forum, so we'll see what they have to say.

**Comment by alastair38** [comment]
OK, changing the keyboard mapping for the Dropdown Menu ('Enter' is set to open a menu item rather than a link by default) did the job. 
 ```
  $(document).foundation();
  // following pulled from foundation.dropdownMenu.js
  Foundation.Keyboard.register('DropdownMenu',{
//    'ENTER': 'open',
    'SPACE': 'open',
    'ARROW_RIGHT': 'next',
    'ARROW_UP': 'up',
    'ARROW_DOWN': 'down',
    'ARROW_LEFT': 'previous',
    'ESCAPE': 'close'
  });
```

**Comment by JeremyEnglert** [comment]
:+1: 

Thanks for working through this.

Just to confirm, it looks like this isn't necessarily a bug, but a setting that needs to be set in Foundation is users wish to implement this. Correct?

Big thanks!

**Comment by alastair38** [comment]
That's right. It's not a bug, but leaving the setting 'as is' doesn't make for the best experience (IMHO) if navigating with the keyboard. As a side note, thanks for the continued work on JointsWP, I love how you've structured everything in the new version and included some handy gulp goodness.

**Comment by JeremyEnglert** [comment]
No problem! I'm glad you're enjoying it! :+1: 

Thanks for figuring this out. It looks like it helped close out another issue as well.
