### ISSUE TITLE
Interchange not working

### ISSUE THREAD

**Issue by JanikWeb** [JeremyEnglert/JointsWP#159]
I'm trying to load images with interchange. Somehow no Image is matching the Media Query rule.
Everything is set correctly as discribed in the docs. Even setting a default image via [ .. (default)] isn't working.

```<?php
$small = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'small' );
$medium = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'medium' );
$large = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'full' );
					
if(has_post_thumbnail()) { ?>
	<img data-interchange="[<?php echo $small[0]; ?>, (small)], [<?php echo $medium[0]; ?>, (medium)], [<?php echo $large[0]; ?>, (large)]">
	<noscript><img src="<?php echo $large[0]; ?>"></noscript>
<?php } ?>
```

**Comment by JeremyEnglert** [comment]
Check out the last post on this thread: http://foundation.zurb.com/forum/posts/493-interchange-with-wordpress

Let me know if that helps!

**Comment by JanikWeb** [comment]
Thanks Jeremy - But This didn't help. I'm trying to load images, not individual php files (which was the problem in the thread you mentioned).
I'm using interchange in other themes without problems. That's the first time I'm facing this error.
All images are found on the server but somehow no image seems to be valid for the current media query.

**Comment by gabrielbajada** [comment]
I'm having the same issue exactly. This bit of code was taken from a site I just finished using JointsWP3.

**PHP**
`
<?php $bg_img_small = types_render_field("banner-image-small", array( "output" => "raw" )); ?> <?php $bg_img_medium = types_render_field("banner-image-medium", array( "output" => "raw" )); ?> <?php $bg_img_large = types_render_field("banner-image-large", array( "output" => "raw" )); ?> <?php $bg_img_xlarge = types_render_field("banner-image-xlarge", array( "output" => "raw" )); ?> <?php $bg_img_xxlarge = types_render_field("banner-image-xxlarge", array( "output" => "raw" )); ?>

<div data-interchange="[<?php echo $bg_img_small; ?>, (small)], [<?php echo $bg_img_medium; ?>, (medium)], [<?php echo $bg_img_large; ?>, (large)], [<?php echo $bg_img_medium; ?>, (medium)], [<?php echo $bg_img_large; ?>, (mediumretina)], [<?php echo $bg_img_large; ?>, (large)], [<?php echo $bg_img_xlarge; ?>, (largeretina)], [<?php echo $bg_img_xlarge; ?>, (xlarge)], [<?php echo $bg_img_xxlarge; ?>, (xlargeretina)], [<?php echo $bg_img_xxlarge; ?>, (xxlarge)]" class="full-viewport display-table banner-image"></div>
`

**Javascript**
`
$(document).foundation('interchange', {
    named_queries : {
        smallretina : 'only screen and (min-width: 1px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 1px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 1px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 1px) and (min-device-pixel-ratio: 2), only screen and (min-width: 1px) and (min-resolution: 192dpi), only screen and (min-width: 1px) and (min-resolution: 2dppx)',
        mediumretina : 'only screen and (min-width: 641px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 641px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 641px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 641px) and (min-device-pixel-ratio: 2), only screen and (min-width: 641px) and (min-resolution: 192dpi), only screen and (min-width: 641px) and (min-resolution: 2dppx)',
        largeretina : 'only screen and (min-width: 1025px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 1025px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 1025px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 1025px) and (min-device-pixel-ratio: 2), only screen and (min-width: 1025px) and (min-resolution: 192dpi), only screen and (min-width: 1025px) and (min-resolution: 2dppx)',
        xlargeretina : 'only screen and (min-width: 1921px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 1921px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 1921px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 1921px) and (min-device-pixel-ratio: 2), only screen and (min-width: 1921px) and (min-resolution: 192dpi), only screen and (min-width: 1921px) and (min-resolution: 2dppx)'
    }
});
`

**Comment by mrscharf** [comment]
In Foundation 6, they changed the syntax ever so slightly for this. The size for each data-interchange should not be enclosed in ellipsis (). So your html should look like this:

`<div data-interchange="[<?php echo $bg_img_small; ?>, small], 
[<?php echo $bg_img_medium; ?>, smallretina],
[<?php echo $bg_img_medium; ?>, medium], [<?php echo $bg_img_large; ?>, mediumretina],
[<?php echo $bg_img_large; ?>, large], [<?php echo $bg_img_xlarge; ?>, largeretina],
[<?php echo $bg_img_xlarge; ?>, xlarge], [<?php echo $bg_img_xxlarge; ?>, xlargeretina],
[<?php echo $bg_img_xxlarge; ?>, xxlarge]"></div>`

You might notice some of the default sizes are working at this point. 

Foundation has a particular way to add your own custom named sizes to Interchange ([documented here](http://foundation.zurb.com/sites/docs/interchange.html#named-media-queries)). When adding your own named sizes to Interchange, you must do this before foundation is initialized in the assets/js/scripts.js file. Initialization takes place on the first line and looks like this:

`jQuery(document).foundation();`

To define your named sizes, try changing to this:

`Foundation.Interchange.SPECIAL_QUERIES['smallretina'] = 'only screen and (min-width: 1px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 1px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 1px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 1px) and (min-device-pixel-ratio: 2), only screen and (min-width: 1px) and (min-resolution: 192dpi), only screen and (min-width: 1px) and (min-resolution: 2dppx)';
Foundation.Interchange.SPECIAL_QUERIES['mediumretina'] = 'only screen and (min-width: 641px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 641px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 641px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 641px) and (min-device-pixel-ratio: 2), only screen and (min-width: 641px) and (min-resolution: 192dpi), only screen and (min-width: 641px) and (min-resolution: 2dppx)';
Foundation.Interchange.SPECIAL_QUERIES['largeretina'] = 'only screen and (min-width: 1025px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 1025px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 1025px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 1025px) and (min-device-pixel-ratio: 2), only screen and (min-width: 1025px) and (min-resolution: 192dpi), only screen and (min-width: 1025px) and (min-resolution: 2dppx)';
Foundation.Interchange.SPECIAL_QUERIES['xlargeretina'] = 'only screen and (min-width: 1921px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 1921px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 1921px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 1921px) and (min-device-pixel-ratio: 2), only screen and (min-width: 1921px) and (min-resolution: 192dpi), only screen and (min-width: 1921px) and (min-resolution: 2dppx)';

jQuery(document).foundation();`

**Comment by JeremyEnglert** [comment]
@mrscharf is the man! :+1: 

@gabrielbajada and @JanikWeb - did that fix the issue for you?

**Comment by gabrielbajada** [comment]
Indeed @mrscharf is the man. The code works. Thanks so much.

However, I still have an issue. If I use more than one script, nothing works. We tried different variations with different scripts that used to work well together in the previous version. Please find an example below. Could you take a look please? [Demo](http://www.jpacampaigns.com/test-sites/test-site-3/)

`
// Google Maps Banner - Disable scroll zooming and bind back the click event
var onMapMouseleaveHandler = function (event) {
    var that = $(this);

    that.on('click', onMapClickHandler);
    that.off('mouseleave', onMapMouseleaveHandler);
    that.find('iframe').css("pointer-events", "none");
};

var onMapClickHandler = function (event) {
    var that = $(this);

    // Disable the click handler until the user leaves the map area
    that.off('click', onMapClickHandler);

    // Enable scrolling zoom
    that.find('iframe').css("pointer-events", "auto");

    // Handle the mouse leave event
    that.on('mouseleave', onMapMouseleaveHandler);
};

// Enable map zooming with mouse scroll when the user clicks the map
$('.google-maps-scroll.google-map-banner').on('click', onMapClickHandler);




// Interchange Retina Functionality

Foundation.Interchange.SPECIAL_QUERIES['small.retina'] = 'only screen and (min-width: 1px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 1px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 1px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 1px) and (min-device-pixel-ratio: 2), only screen and (min-width: 1px) and (min-resolution: 192dpi), only screen and (min-width: 1px) and (min-resolution: 2dppx)';
Foundation.Interchange.SPECIAL_QUERIES['medium.retina'] = 'only screen and (min-width: 641px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 641px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 641px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 641px) and (min-device-pixel-ratio: 2), only screen and (min-width: 641px) and (min-resolution: 192dpi), only screen and (min-width: 641px) and (min-resolution: 2dppx)';
Foundation.Interchange.SPECIAL_QUERIES['large.retina'] = 'only screen and (min-width: 1025px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 1025px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 1025px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 1025px) and (min-device-pixel-ratio: 2), only screen and (min-width: 1025px) and (min-resolution: 192dpi), only screen and (min-width: 1025px) and (min-resolution: 2dppx)';
Foundation.Interchange.SPECIAL_QUERIES['xlarge.retina'] = 'only screen and (min-width: 1921px) and (-webkit-min-device-pixel-ratio: 2), only screen and (min-width: 1921px) and (min--moz-device-pixel-ratio: 2), only screen and (min-width: 1921px) and (-o-min-device-pixel-ratio: 2/1), only screen and (min-width: 1921px) and (min-device-pixel-ratio: 2), only screen and (min-width: 1921px) and (min-resolution: 192dpi), only screen and (min-width: 1921px) and (min-resolution: 2dppx)';
`

**Comment by mrscharf** [comment]
Glad I could help!

In FF concole, I'm seeing the error:

`TypeError: $ is not a function`

Try changing the '$' shorthand to 'jQuery'.

**Comment by gabrielbajada** [comment]
@mrscharf, you are the king of anyone who thinks they're the man.

Thank you.

**Comment by JeremyEnglert** [comment]
> By the way @JeremyEnglert, as we were testing this out we noticed that scripts.js compiles the files in the scripts folder in alphabetical order, so we had to name our .js files starting with a 1 e.g. 1-interchange-retina.js to make sure that the interchange script was before jQuery(document).foundation();.

Ahhh. Nice catch. Let me see if there is a way to define which scripts get called first. 

PS - @mrscharf may be my new favorite person. HUGE thanks for all the help! :+1:

**Comment by gabrielbajada** [comment]
:+1:

**Comment by JeremyEnglert** [comment]
@gabrielbajada you can specify the order of the script by declaring them in the gulpfile.

So something like this:

```JAVASCRIPT
// JSHint, concat, and minify JavaScript
gulp.task('site-js', function() {
  return gulp.src([	
	  
           // Grab your custom scripts
                  '/link/to/script1.js',
                  '/link/to/script2.js',
  		  './assets/js/scripts/*.js'
  		  
  ])
    .pipe(plumber())
    .pipe(sourcemaps.init())
    .pipe(jshint())
    .pipe(jshint.reporter('jshint-stylish'))
    .pipe(concat('scripts.js'))
    .pipe(gulp.dest('./assets/js'))
    .pipe(rename({suffix: '.min'}))
    .pipe(uglify())
    .pipe(sourcemaps.write('.')) // Creates sourcemap for minified JS
    .pipe(gulp.dest('./assets/js'))
});    
```

**Comment by gabrielbajada** [comment]
Thanks @JeremyEnglert, I'll try this out and let you know how it goes.

**Comment by gabrielbajada** [comment]
I know I'm too late because I just downloaded Joints again and found it already in gulpfile.js, but yes, it does work.

Thanks so much.
