### ISSUE TITLE
[3.0] Menus Break After 4.4.2 Update

### ISSUE THREAD

**Issue by JeremyEnglert** [JeremyEnglert/JointsWP#164]
Issue reported by multiple users. 

https://disqus.com/home/discussion/jointswp/requesting_support/#comment-2503106159

**Comment by JeremyEnglert** [comment]
It appears that the 4.4.2 update is adding unnecessary junk to the URL's for the Foundation JS files. (See attached).  

This doesn't appear to happen with a fresh install. I setup a new, local instal using Joints 3.0 and didn't have any issues. 

Still trying to find a solution. Does the issue persist when all plugins are disabled? 

![screen shot 2016-02-09 at 4 29 10 pm](https://cloud.githubusercontent.com/assets/6110968/12934434/c14c9168-cf4b-11e5-9268-7472cab9e327.png)
![screen shot 2016-02-09 at 4 39 28 pm](https://cloud.githubusercontent.com/assets/6110968/12934435/c14cc4ee-cf4b-11e5-9e51-87d7d3f988fb.png)

**Comment by ellin07** [comment]
It still happens with plugins disabled. The version I am using is Version: 2.0 (CSS). The new joointswp with foundation 6 appears to work, I just have a lot of styling ahead of me. Do you have a version of the old one I can unpack and replace elements with? Or will I need to rebuild those files as well?

**Comment by JeremyEnglert** [comment]
I tested it with JointsWP 3 (which uses F5) and wasn't able to replicate the issue. It appears the issue only occurs when updating a website, not when starting from scratch.

I've talked to a few people and one user suggested changing to a default theme (such as Twentysixteen), then switching back. This may resolve the issue. Can you try that?

Your theme is 100% fine. Something in the database is adding extra junk to your asset URL's which is causing them to not load. 

Converting from F5 to F6 would be very difficult - I normally recommend starting out fresh in those instances. Many items, such as the topbar navigation, have been completely reworked in F6.

**Comment by ellin07** [comment]
Switching themes back and forth didn't help. Is there a place I can download the JointsWP 3? I can try that, most of my configuration is in the CSS. Outside of that a few custom things.

**Comment by ellin07** [comment]
It doesn't look like anything extra is being added to my URLs. 

![screen shot 2016-02-09 at 7 46 55 pm](https://cloud.githubusercontent.com/assets/10143985/12935713/ebe294e4-cf65-11e5-8bc9-52d7f209376d.png)

**Comment by JeremyEnglert** [comment]
See the %20 at the end of the JS URL? That's the issue.

**Comment by ellin07** [comment]
I have another site that the same thing happened with. It isn't currently in use by the company so I decided to mess around with that one. http://drdavidbakerhargrove.kineticcreative.com/

I loaded a fresh jointswp theme and there are still issues.

**Comment by JeremyEnglert** [comment]
Same error. WP is adding a bunch of junk to your URLs (see attached). Can you send me a screenshot of your functions.php file?

If you tried a fresh install and you're still having the issue, this is definitely a database related issue. Something happened to the database when WP updated.

Do you use any security plugins or caching plugins? 

![screen shot 2016-02-10 at 10 44 34 am](https://cloud.githubusercontent.com/assets/6110968/12956066/58c0aba0-cfe3-11e5-9da0-0d359aefaf46.png)

**Comment by ellin07** [comment]
No security or caching plugins used. 

![screen shot 2016-02-10 at 12 54 48 pm](https://cloud.githubusercontent.com/assets/10143985/12956337/85166d40-cff5-11e5-874d-cc9d0232ca16.png)
![screen shot 2016-02-10 at 12 55 00 pm](https://cloud.githubusercontent.com/assets/10143985/12956338/8518caa4-cff5-11e5-8a93-52c6597226e7.png)
![screen shot 2016-02-10 at 12 55 08 pm](https://cloud.githubusercontent.com/assets/10143985/12956336/8516218c-cff5-11e5-83b4-6e3c87a46586.png)

**Comment by ellin07** [comment]
These are the only plugins active

![screen shot 2016-02-10 at 12 57 46 pm](https://cloud.githubusercontent.com/assets/10143985/12956403/de5d3370-cff5-11e5-9fa4-d01014ac220f.png)

**Comment by JeremyEnglert** [comment]
Thanks! Sorry for all the questions - just trying to narrow this down. I can't apologize enough for the inconvenience this has caused. 

Can I also see your Joints.php file?

**Comment by ellin07** [comment]
![screen shot 2016-02-10 at 1 00 45 pm](https://cloud.githubusercontent.com/assets/10143985/12956561/9e813c78-cff6-11e5-93e9-f4ba68c07719.png)
![screen shot 2016-02-10 at 1 01 50 pm](https://cloud.githubusercontent.com/assets/10143985/12956560/9e811964-cff6-11e5-99fc-5374591c2a3e.png)
![screen shot 2016-02-10 at 1 02 01 pm](https://cloud.githubusercontent.com/assets/10143985/12956564/9e821d6e-cff6-11e5-8133-6a358b4f77f8.png)
![screen shot 2016-02-10 at 1 02 35 pm](https://cloud.githubusercontent.com/assets/10143985/12956559/9e7e7e16-cff6-11e5-9b39-b0dcfa9d978d.png)
![screen shot 2016-02-10 at 1 02 42 pm](https://cloud.githubusercontent.com/assets/10143985/12956563/9e822e26-cff6-11e5-9bfc-0e06dbccd569.png)
![screen shot 2016-02-10 at 1 02 47 pm](https://cloud.githubusercontent.com/assets/10143985/12956562/9e81696e-cff6-11e5-9912-ae4048704e0e.png)

**Comment by JeremyEnglert** [comment]
On line 123/124, can you replace $theme_version with '5.0' (with the single quotes). I'm thinking the theme name and/or theme version got messed up in the database somehow. 

You can see how the never version calls scripts here: https://github.com/JeremyEnglert/JointsWP/blob/master/assets/functions/enqueue-scripts.php

I hate to ask, but if you can provide temporary admin access and phpMyAdmin access, I may have a better chance at locating the issue. I'm really leaning towards this being some kind of database bug.

**Comment by ellin07** [comment]
I sent you an email. I also thought I'd let you know that I also tried a fresh local install of WP and just copied my theme to it, I didn't duplicate the database there and had the same issues.

**Comment by JeremyEnglert** [comment]
Found it.

Line 123/124 of joints.php is broken onto too lines - it looks like additional spaces were added that was breaking things. The line should read:

`// adding Foundation scripts file in the footer
    wp_enqueue_script( 'foundation-js', get_template_directory_uri() . '/foundation/js/foundation.min.js', array( 'jquery' ), '5.0', true );`

**Comment by swwhitted** [comment]
Hi Jeremy,

having same issue with "%20%20%20%20" showing up in theme folder name. Line fix onf 123/124 of joints didn't seem to fix. Any thoughts on where in DB the extra spaces maybe coming from? Seems to only be that foundation min js call that it happens with.

**Comment by JeremyEnglert** [comment]
Can you send me a Gist of what your Joints.php file looks like?

https://gist.github.com/

**Comment by swwhitted** [comment]
Sure - https://gist.github.com/swwhitted/fd0486c5913886ef9e16

**Comment by JeremyEnglert** [comment]
I replied to your Gist - did that fix it?

**Comment by swwhitted** [comment]
Don't think it did. Still not working on mobile and still seeing extra spaces in theme folder.
![screenshot 2016-02-22 17 44 25](https://cloud.githubusercontent.com/assets/6153548/13235464/06c984e0-d98c-11e5-8958-8c1b02be245d.png)

**Comment by JeremyEnglert** [comment]
I added another comment to the Gist.

Essentially the error is saying there is an extra space after the theme name/directory. We just gotta find that extra space.

**Comment by swwhitted** [comment]
Right. Still no dice with the 2nd try. It's freaking me out, lol.

**Comment by JeremyEnglert** [comment]
Can you email me the theme files? Jeremy@joints.io

Sorry about the inconvenience!

**Comment by swwhitted** [comment]
No problem.Thanks for the fast help, too. Files sent.
