### ISSUE TITLE
Erratic Scrolling and Extra Space Below <body>

### ISSUE THREAD

**Issue by gingerlyco** [JeremyEnglert/JointsWP#167]
I can't seem to figure out what's causing the page scrolling to hang when when I make sudden motion. Chrome kind of handles is okay, but Safari and Firefox both get stuck and then keep scrolling.

Additionally, there is extra space below the <body> tag on multiple breakpoints. My guess is that they're related. I attempted to remove all the off canvas wrappers, since I'm adding my own off canvas menu, but I was hit with the same issues.

Demo site at: http://654.e92.mwp.accessdomain.com

**Comment by mrscharf** [comment]
I'm not noticing any scroll hang here on either FF or Chrome.

**Comment by JeremyEnglert** [comment]
I don't notice anything either. Can you take a quick screencast?

**Comment by gingerlyco** [comment]
I will try to get a screencast of it.

In the meantime, do you see the extra space at the bottom of the page? Like, 15-20px with a drop shadow on a 'large' view.

**Comment by gingerlyco** [comment]
Scroll lag seems to mostly happen when the scroll bar auto hides after a period of non-scroll (Mac setting). Could it be a z-index confusion?

**Comment by JeremyEnglert** [comment]
That's coming from the .off-canvas-wrapper class. You can eliminate that since you aren't using the off-canvas.

**Comment by gingerlyco** [comment]
I've removed .off-canvas-wrapper, .off-canvas-wrapper-inner, & .off-canvas-content, but still see the space at the bottom.

I believe I fixed the scrolling. Set the body height to 'auto' instead of 100%.

**Comment by gingerlyco** [comment]
Ah, looks like something was overflowing in the footer. Good now. Thanks for your time!
