### ISSUE TITLE
[Feedback Wanted] Directory structure question

### ISSUE THREAD

**Issue by thefrosty** [JeremyEnglert/JointsWP#171]
Just curious why your /functions/ are located in your /assets/ directory? Shouldn't they be in an /includes/ directory?

Edit from @JeremyEnglert - should the functions be moved from assets/functions to an includes/ directory? This seems to be how many themes have it setup.

**Comment by JeremyEnglert** [comment]
Some themes use /includes/ others use /assets/, some even use /library/. Unless there is some kind of standard I missed? (Which is likely). 

To me, "assets" makes the most sense as they are pieces of code that belong to the theme.

**Comment by thefrosty** [comment]
Thanks. 

To me assets is more CSS, JS, Images. But just wanted to ask the question.

**Comment by JeremyEnglert** [comment]
That's actually a great point. Definitely something to think about - especially since many themes seem to take that route.

**Comment by thefrosty** [comment]
Just dropping my 2 cents for what it's worth.

**Comment by JeremyEnglert** [comment]
I'd love for WP to have some kind of standards/best practices when it came to file structure.

**Comment by JeremyEnglert** [comment]
Made some changes to the original post to get feedback from more users. :+1:

**Comment by mrscharf** [comment]
I've always thought of includes to indicate server side and assets to indicate front end. Since the functions file uses include() to call up the functions files, it would probably make more sense for them to be in an includes directory.

**Comment by anyway** [comment]
I'm also slightly irritated that the functions folder is located under assets. I would leave the name "functions", because of the relationship to functions.php, and would place the folder directly into the theme root.

**Comment by iamchaka** [comment]
I'm still a pup learning WP, but when I worked with another CMS and it was set up just as @mrscharf stated. Is there any other files that would benefit from this?  Also are you thinking having the includes folder on the same directory level as parts, assets, etc?

**Comment by JeremyEnglert** [comment]
@iamchaka - correct! If this change were to happen, the `includes` directory would be in the root of the theme.

**Comment by JeremyEnglert** [comment]
This change will happen in the next update.

https://github.com/JeremyEnglert/JointsWP/issues/185
