### ISSUE TITLE
Active state not working

### ISSUE THREAD

**Issue by dritter** [JeremyEnglert/JointsWP#172]
Hi there!

The active state of the navigation doesn't seem to work right. Wordpress sets the class "current-menu-item", but Foundation6 wants "active". In the Foundation5-Variant of this theme, there was a function `required_active_nav_class`, which added this functionality. I ported that feature over by adding this function to `assets/functions/menu.php`:
```php
//Use the active class of the ZURB Foundation for the current menu item. (From: https://github.com/milohuang/reverie/blob/master/functions.php)
function required_active_nav_class( $classes, $item ) {
	if ( $item->current == 1 || $item->current_item_ancestor == true ) {
		$classes[] = 'active';
	}
	return $classes;
}
add_filter( 'nav_menu_css_class', 'required_active_nav_class', 10, 2 );
```

**Comment by JeremyEnglert** [comment]
Big thanks! This has been fixed. 

https://github.com/JeremyEnglert/JointsWP/commit/a83c9a1aac7c9b9679216283c77f2eba902146b0
