### ISSUE TITLE
Use minified version of Foundation

### ISSUE THREAD

**Issue by dritter** [JeremyEnglert/JointsWP#173]
Is there any reason why not to use the minified versions of Foundation in `assets/functions/enqueue-scripts.php`?
All enqueued scripts and styles are currently the un-minified versions..

**Comment by JeremyEnglert** [comment]
There's a reason - it's just not a reason I'm a huge fan of.

Essentially, many people who use the theme also use a compiler that doesn't automatically create a minified file. So many users were downloading the theme, making changes, but then not seeing those changes (as the theme originally enqueued the minified files).

This way, the theme works for everyone out of the box - but can be easily adjusted to enqueue minified files.

I've also had some developers say they like working with non-minified files until they are ready for production (I think _s uses a similar approach).

**Comment by dritter** [comment]
Hmm. In my opinion the theme should provide good defaults. Minified JS/CSS files are such a good default (unless we get a good coverage of HTTP2).

But I can see your point and the benefit of new users changing the theme easily. Case closed ;)
