### ISSUE TITLE
updating theme?

### ISSUE THREAD

**Issue by titaniumbones** [JeremyEnglert/JointsWP#174]
Any guidance on how best to update the theme once one's started making changes to templates and assets/scss/? 

My current version of gulpfile.js throws an unhandled error when I try to run gulp foundation-js (it chokes on "uglify", which I guess is not really so important). THis makes me wonder whether I'd be better off updating but somehow preserving my changes. Any guidance?

**Comment by JeremyEnglert** [comment]
Updating the entire theme would be rough - but you should be able to fix this issue by grabbing the newest gulpfile.js and package.json and replacing the ones you have. 

Let me know if that fixes the issue for you.

**Comment by kemie** [comment]
I did it, but it required a lot of manual work- checking commit dates to find which files had changed and using a diff tool to update conflicting files. The biggest  pain was settings.scss, where I had to figure out what to take from each version.

**Comment by JeremyEnglert** [comment]
@kemie, you're a champ!
