### ISSUE TITLE
[Feedback Wanted] Is it time to remove some rarely used functions & files?

### ISSUE THREAD

**Issue by JeremyEnglert** [JeremyEnglert/JointsWP#175]
As many of you know, JointsWP was originally forked from Bones. One of the great things about Bones was how well it is commented and how it included many files that beginners may not even know existed (for example, in my newb days, I first learned how to create custom post types by using Bones). Because of this, I always thought it was a good idea to keep those files/functions included with JointsWP.

However, it seems that the JointsWP audience is a bit more advanced and may not find these types of files as useful. Which then turns them into additional junk that must be deleted.

With that in mind, here are some of the files and functions potentially on the chopping block. I'd love to get feedback on these files/functions as well as feedback on additional files/functions that you think could be removed.

**Potential functions to be removed:**
- `custom-post-type.php` - allows users to create custom post types, but many will argue this is best left to a plugin
- `joints_rss_dashboard_widget()` (inside of admin.php) - this is actually a pretty cool function that allows you to run your own RSS feed on the dashboard, but does anyone really use it?

**Potential files to be removed:**
- `archive-custom_type.php`
- `single-custom_type.php`
- `taxonomy-custom_cat.php`

**Comment by Xavvi** [comment]
Hi Jeremy. Here's my two cents:

`custom-post-type.php`: 95% of the time I'll use the Custom Post Types UI plugin to create new CPTs. It's just quicker and although it may offer slightly less control, it usually gets the job done. 

`joints_rss_dashboard_widget()`: This is one of the first things I usually remove on a new install. Perhaps snippets like this would be better off as Gists with a note of where best to put them within a JointsWP theme. 

`archive-custom_type.php`, `single-custom_type.php` and `taxonomy-custom_cat.php`: I'm ok with these personally as it makes development a _fraction_ faster, but I wouldn't be against them being removed for the sake of slimming things down. 

Thanks for all your work on this

**Comment by andycochran** [comment]
You probably know my take on this, especially if you've looked at my [wp-foundation-sites](https://github.com/andycochran/wp-foundation-sites) theme (which does virtually nothing). I think starter themes are most helpful when the developer knows exactly everything the theme is doing. Given the plethora of WP resources, I'd rather write a new feature from scratch than hunt down the methods of a feature that's already integrated. 

A bit of context: I'm just getting back into WP development after ~3 years of working exclusively with [Django](https://www.djangoproject.com/). I love Foundation, and was psyched when I found JointsWP. It's rad! I was just wary of diving into a fleshed out theme and not knowing why/how it did what it did. So I stripped it of everything. Did I go too far? Probably. There are many features that one always adds to every theme. So in many ways, JointsWP is way more useful than wp-foundation-sites—especially once you're more familiar with it. 

When deciding which features to cut/add, consider the audience and the project description: 

> A blank WordPress theme built with Foundation 6, giving you all the power and flexibility you need to build complex, mobile friendly websites without having to start from scratch.

Is JointsWP built for designers that wanna style something that just works? Or is it a starting point for developers to build complex sites? Does a theme that's too feature-rich lend itself to cargo cult programming? 

I think you're on the right track with the features on your chopping block. But you probably don't need to chop much else. Maybe JointsWP just needs more inline code documentation on every file to explain how features work and which other files contain related functions & markup, so when I want to deleted a feature, I can find all its parts. 

I hope my rambling is helpful and I didn't just raise more questions.

**Comment by mrscharf** [comment]
I wouldn't miss the RSS feed.

The 3 template files are simple to delete in 1 second if I don't need them. Although I always find myself copying those and renaming them just to have a basic starting point with the loop structure in place.

I would miss the `custom-post-type.php` file because I use this on every project. Having all the settings right there makes it very easy to setup a CPT and know I haven't missed anything critical. I generally avoid plugins for simple things like CTPs to maintain performance, reduce the nagging to update and keep things under my own control rather than obscuring them through a plugin.

**Comment by andycochran** [comment]
I agree w/ @mrscharf; I avoid plugins for anything WP does easily on its own.

**Comment by JeremyEnglert** [comment]
The argument against including CPT's inside of the theme is that the data is saved to the theme - which means if you change themes, the data also goes away as well. Which is a great point if you're developing websites for the WP Theme Directory. But for custom sites, I don't see this as a huge issue. 

If I'm developing a custom website for a client, I'm not going to worry about whether or not they're going to change the theme down the road. If they're having us build them a custom site, they're most likely not going to be switching between themes anyway.

Maybe this should stay. It seems a lot of users are utilizing it.

**Comment by jessefisher** [comment]
I've never used the CPT's in the theme, because of what I've read about the theme/plugin debate. The Custom Post Types UI plugin always does the job pretty easily and it now has an option to rename a post type without losing the data. I haven't felt the need to remove it from the theme though, because it's commented out by default now.

I use the RSS widget on every client site I build now. Our company writes new posts regularly to attract potential clients and help existing clients improve their business. Having the RSS feed on the dashboard helps to keep our clients up to date with what we're doing and fresh in their minds. It can very easily be disabled by us or them in the dashboard too.

The extra templates aren't needed in every project, but I'd rather spend 3 seconds deleting them than a few minutes looking up the relevant code and template slug rules again.

**Comment by iamchaka** [comment]
I don't use all the pages, and frankly I'm fine cherry picking files out if other find them useful.  I might use them one day after I graduate from these WP diapers. 

Not sure if there would ever need to be a JointsWP and JointsWP-lite down the road. Not trying to make extra work, but you clearly have advanced users that use JointsWP to jump start workflow and you also have a group of novice folks that are using the theme to cut their teach and learn WP (I'm in this group).  I'm thinking as I'm typing at this point.

**Comment by kemie** [comment]
I use the CPT file, and also the templates, again to have a quick boilerplate to rename and customize. 
the rss function i don't use and i don't see myself using it ever.

**Comment by bpongvh** [comment]
I'm with @kemie. CPT file is useful. Caveat: I'm a WP newbie, but I've worked on plenty of CMS packages. The plugin mania among WPers makes me crazy--don't people look at all the crappy code they're recommending? I ended up just rolling my own CPT boilerplate. Not as snazzy as having it built in to JointsWP, so I use the one here. Like @jessiefisher, I find boilerplates useful to remind me of all possible API options without a trip to the codex.

**Comment by Warkman** [comment]
Im of the nature (for now) of leaving it there, could use a special name convention for easy to identify, nice to haves bit not needed eg. 

*__taxonomy-custom_cat.php
*__single-custom_type.php

**Comment by JeremyEnglert** [comment]
Love all the feedback! Big thanks everyone.

--

>  @andycochran - Maybe JointsWP just needs more inline code documentation on every file to explain how features work and which other files contain related functions & markup, so when I want to deleted a feature, I can find all its parts.

This definitely needs to happen. As well as better overall documentation on JointsWP.com.

--

> @mrscharf - The 3 template files are simple to delete in 1 second if I don't need them. Although I always find myself copying those and renaming them just to have a basic starting point with the loop structure in place.

I do the same thing. But recently, I've found myself copying archive.php and renaming it (it's the same thing as archive-custom_type.php). However, I agree, it doesn't take much to delete them if they aren't being used. So maybe it's best if they stick around.

--

> @mrscharf  - I generally avoid plugins for simple things like CTPs to maintain performance, reduce the nagging to update and keep things under my own control rather than obscuring them through a plugin.

Great point. The CPT function will stay.

--

> @jessefisher - I use the RSS widget on every client site I build now.

Maybe this will stick around with better documentation. Potentially split off into it's own file so it can be more easily disabled.

--

> @iamchaka - Not sure if there would ever need to be a JointsWP and JointsWP-lite down the road.

I'm looking into ways to potentially have a gulp task that would remove comments/rarely used files. 

--

> Im of the nature (for now) of leaving it there, could use a special name convention for easy to identify, nice to haves but not needed in general eg.

Very interesting idea. Definitely going to think about this!

**Comment by JeremyEnglert** [comment]
Closing in favor of this thread: https://github.com/JeremyEnglert/JointsWP/issues/185
