### ISSUE TITLE
Slow Sass compiling after F6 Upgrade

### ISSUE THREAD

**Issue by JeremyEnglert** [JeremyEnglert/JointsWP#176]
Reported on JointsWP.com - I'm noticing this as well.

It's taking between 6-10 seconds to complete the `gulp styles` task.

It appears to be caused by all of the includes from Foundation. If those are removed, the task completes in under a second. 

I wonder if this can be fixed by changing how the files are referenced or if it's something we have to learn to live with when using F6.

**Comment by JeremyEnglert** [comment]
Note: This may be related to source-maps. As a user is reporting it works fine with Foundation 6.0.2 (which was prior to source-maps being added.

**Comment by bpongvh** [comment]
Not sure if there's anything useful in this note, but I got frustrated by this and plugged in my trusty Grunt scripts. Seems to run like normal without slowdown. Maybe it's a conflict with gulp-sass.

Cheers,
Robert

**Comment by JeremyEnglert** [comment]
That helps a lot actually. I'm thinking this is related to source-maps. Checking now.

**Comment by JeremyEnglert** [comment]
Looks like it is related to the sourcemaps: https://github.com/postcss/postcss/issues/317

Which leads to an interesting discussion. Should we set the gulpfile to only run certain tasks when a production flag is added to a gulp command?

For example, with the `styles` task, a user could run `gulp styles --production` to have the styles minified and sourcemaps created.

**Comment by JeremyEnglert** [comment]
This will be added in the next version.

https://github.com/JeremyEnglert/JointsWP/issues/185
