### ISSUE TITLE
Problem with the flex-grid

### ISSUE THREAD

**Issue by papaponmx** [JeremyEnglert/JointsWP#180]
Using sass --watch 
When I uncomment @include foundation-flex-grid, this error shows up in terminal: 

```

>>> Change detected to: scss/style.scss
      error ../vendor/foundation-sites/scss/grid/_flex-grid.scss (Line 250: Undefined variable: "$gutter".)
#
```

**Comment by JeremyEnglert** [comment]
Are you including foundation-flex-classes too?

**Comment by JeremyEnglert** [comment]
I can't replicate even if foundation-flex-classes are not included.

I'm going to close this for now, but let me know if you're still having issues.
