### ISSUE TITLE
offset height btwn top-bar-right and top-bar-left in header

### ISSUE THREAD

**Issue by titaniumbones** [JeremyEnglert/JointsWP#181]
I have a student group working on a site using Jointswp. They've noticed that there is a slight height offset between the site title (top-bar-left) and the main menu (top-bar-right) in the topbar.  I'm not sure what causes this -- possible the existence of submenus items pushes the top-level menu items up towards the top of the bar.  

You can see what I mean on their site here:

http://flynnhouse.hackinghistory.ca/flynn-house/

Any suggestions? thanks as always for your help.

**Comment by mrscharf** [comment]
Having a look at your demo site, it seems to be doing what is described here:

[Foundation 6 Top Bar Documentation](http://foundation.zurb.com/sites/docs/top-bar.html)

By default the .top-bar-left and .top-bar-right stack on small screens.

**Comment by titaniumbones** [comment]
hey @mrscharf , thx for the reply. I think I mean something else though -- on a large screen, you can see a slight offset between the right and left sections of the top bar. The left section is perfectly centered, while the right section is just a little bit above the center of the bar. Are you seeing that? It's more obvious when you inspect element & get a look at at the whole element box for the relevant divs.

**Comment by mrscharf** [comment]
Ahh, I see. Under the `.top-bar-left` div is a ul > li and the li has a `.menu-text` class which has padding applied to it. If I remove this class name (which removes the padding), the site title is perfectly aligned with the menu items.

It looks like not long ago the `.menu-text` was removed from JointsWP, so should be safe to remove from your site as well if need be.

**Comment by JeremyEnglert** [comment]
> It looks like not long ago the .menu-text was removed from JointsWP, so should be safe to remove from your site as well if need be.

@mrscharf is 100% correct. .menu-text was needed in the original release of Foundation 6 but has since been removed. 

I'm going to close this for now, but if the above doesn't fix the issue, feel free to reopen.
