### ISSUE TITLE
Dropping Bones & combine  JointsWP with  _s

### ISSUE THREAD

**Issue by Warkman** [JeremyEnglert/JointsWP#182]
This is just a suggestion of dropping Bones (due to it being no longer supported by it Author) and looking at combining WP Joints with _s instead? 

Main thinking for this is that _s is maintained by Automattic and would be using the most relevant code practices to use with a WordPress theme. One less to think about.

What do you think?

**Comment by JeremyEnglert** [comment]
Couldn't agree more! 

90% of Bones has been stripped out of JointsWP (not purposely, just general progression over time). 

Many of the newer functions/code are "borrowed" for _s. In fact, I was just going over the _s repo to see how they implemented wp_page_links. 

JointsWP will also probably "borrow" how _s sets up post_formats on the single.php pages. 

Sad to see Bones no longer being maintained :(

**Comment by Warkman** [comment]
Well I would be more then happy to make this happen & available to chat more about it if you like.
