### ISSUE TITLE
JS  scripts not loading on single.php

### ISSUE THREAD

**Issue by benoitjupille** [JeremyEnglert/JointsWP#183]
Hi Jeremy, 

I have a weird thing : my JS scripts (foundation.min.js, what-input.js, scripts.min.js...) are not loading when a page using the single.php template is loaded... 

Did you already faced this ?

**Comment by benoitjupille** [comment]
My bad, I should have set the WP_DEBUG to true before asking ;)

**Comment by JeremyEnglert** [comment]
Glad you got it worked out! Was it a theme related issue?

**Comment by benoitjupille** [comment]
No it was related to the Facebook php api, which was called without api key. The reason was that I migrated my website, and somehow the api key field value hasn't been migrated. 

Thanks for that excellent starter theme by the way ;)
