### ISSUE TITLE
Why vendor folder?

### ISSUE THREAD

**Issue by hartwm** [JeremyEnglert/JointsWP#186]
most people got rid of vendor file for consistent naming of bower_components.  I went to change it because I saw no use, then I realized you were enqueue script from the vendor, but the vendor is just a direct copy of bower? you wouldn't want to upload all your bower files to server... 

all this is a round about way of saying probably implement wiredep? and are there any other hidden hooks for vendor?

**Comment by JeremyEnglert** [comment]
This is actually something I've always been on the fence about.

In an older version of JointsWP, files were enqueued directly from bower_components. However, this seemed to "scare" off some users are it made it appears as if bower was a requirement to use the theme (it isn't).

So that is why those files were moved into a 'vendor' directory.

Running `gulp bower` will create a bower_components directory with updated files and automatically move them into your 'vendor' directory.

I'm thinking of changing this up in an upcoming release - but not sure of the best approach to take.

**Comment by COLABORATI** [comment]
I would like to propose to add a ```.bowerrc``` file that just points to the ```vendor``` dir. But also I would like it much better if ```assets``` contained only files that need to be used (uploaded) by the theme, this requires some changes in the ```gulpfile.js```. 

From my pov the current directory structure is a little bit confusing, I believe it would be better to have all the files that might be edited for F6 customization in a folder ```src```, also keeping the ```translation``` and ```functions``` folder on top level of the theme, as there is ```parts``` already. Gulp should then copy / compile all files to assets and ```enqueue-scripts.php``` should only use files from ```assets``` - so it would be better to automate deployment with just excluding ```vendor```, ```node_modules``` and ```src```.

Directory structure would look like: 
```
assets/css
assets/img
assets/js
functions
[node_modules]
src/scss
src/js
parts
translation
[vendor]
```
Maybe even a little bit cleaner with php includes in the "traditional" ```inc``` folder: 
```
assets/css
assets/img
assets/js
inc/functions
inc/translation
inc/parts
[node_modules]
src/scss
src/js
[vendor]
```
However the main benefit of this is to have the foundation customizations in ```src``` and have the theme more easily deployable. There could be also a gulp task ('deploy' or similar) that would generate a new theme folder with only the needed files.

(I am not sure about ```translations``` - current official themes use ```languages``` - I am not aware of any tools that expect that folder to be on theme top-level and have a special name.)  

Are you open to discuss this?

**Comment by COLABORATI** [comment]
BTW also that way (if I am not missing anything) ```vendor``` could be added to ```.gitignore``` and you could distribute jointswp without that folder with all the needed foundation files in ```assets```. People who like to customize the theme "old-school" by just editing css files could just do it, while sass- and gulp-aware folks will have no problem with a ```npm install```.

**Comment by kemie** [comment]
just a reminder, not all sass users are gulp users. Some of us compile it with other workflows.

**Comment by JeremyEnglert** [comment]
@Colaborati, I really like your suggestion and the theme structure is actually a big part of our discussion in upcoming changes. 

Another proposed approach was to not include any of the vendor related files at all and have users install them using npm install when they download the theme. This means the theme would always be using the latest version of Foundation (for the most part). 

However, as noted above, there are a decent amount of JointsWP users who utilize Sass but do not use Gulp/NPM. That's the curveball here.

**Comment by JeremyEnglert** [comment]
Additional thoughts here: https://github.com/JeremyEnglert/JointsWP/issues/213

**Comment by JeremyEnglert** [comment]
So JointsWP is already good at making it easier to build themes - the next version will put a focus on making it easier to deploy super optimized themes. A lot of the feedback from this thread is going to be used.

**Comment by JeremyEnglert** [comment]
Does using "build" instead of "src" make sense"? Originally that was the direction I wanted to go - as that is where you would "build" your theme.

But I think some frameworks/tools use "build" as the output directory. Or am I over thinking this?

**Comment by garrett-eclipse** [comment]
Hi @JeremyEnglert, correct me if I'm wrong but this suggestion is to have workflow so you compile locally and then deploy without the vendor files and only compiled css?
Would there still be the option of bundling the vendor files in the theme uploaded to WP?
We've customized JointsWP to bundle scssphp by leafo with our theme and make some scss settings available to through options, saving them recompiles scss including foundation.
With the new proposed direction will that affect how we do our set-up? 
Thank you

**Comment by JeremyEnglert** [comment]
@garrett-eclipse, I'm not completely familiar with scssphp - but at a quick glance, it looks like it's a tool that allows you to compile Scss on a server. 

> correct me if I'm wrong but this suggestion is to have workflow so you compile locally and then deploy without the vendor files and only compiled css?
You are correct. 

> Would there still be the option of bundling the vendor files in the theme uploaded to WP?
There will be a version of JointsWP called something like "JointsWP Vanilla" that includes the necessary vendor files - this will replace the CSS version but support CSS and Scss.

**Comment by JeremyEnglert** [comment]
Closing this as it is implemented in JointsWP 5. Feel free to keep the conversation going.

**Comment by garrett-eclipse** [comment]
Thanks @JeremyEnglert will keep an eye on it for JointsWP 5 and test out the Vanilla version to see if I can keep my server rendering of SCSS working as we've found it really nice to tie our ACF options page to the SCSS of foundation, etc to override variables and re-render. Found scssphp worked really well with the existing Joints. Appreciate all your work and look forward to working with V5
