### ISSUE TITLE
Parent Menu Link Not Clickable

### ISSUE THREAD

**Issue by huwrowlands** [JeremyEnglert/JointsWP#187]
Hi

How come my parent menu link is not wrapped within an anchor tag? Is this something that will be updated so that it is clickable?

**Comment by JeremyEnglert** [comment]
Do you have a link?

**Comment by dritter** [comment]
I had the same Issue. The problem occurs on the smaller devices. For example on the [demo site](http://jointswp.com/demo/). If "Archive Styles" would be a regular page with subpages, you won't be able to click on that link in the off-canvas menu.

Try to click on that link:
![menu](https://cloud.githubusercontent.com/assets/1544760/14120172/ec640da0-f5f1-11e5-83ec-2cd6b8c7a82a.png)

**Comment by JeremyEnglert** [comment]
The accordion doesn't provide that option. However, it would be a great add-on to Foundation. Someone should open a ticket on the Foundation repo. :+1: 

However, if you use the drilldown menu, you can add the `data-parent-link` option that duplicates the parent link as the first child link.

http://foundation.zurb.com/sites/docs/drilldown-menu.html#js-options

**Comment by huwrowlands** [comment]
Sorry.. updated to the latest theme files and topbar menu, parent link now working. Thanks

**Comment by Warkman** [comment]
Hi @huwrowlands can you share the code you added to get this to work?

**Comment by huwrowlands** [comment]
Hi @Warkman I used the updated (latest) version of the theme which contains Foundation 6.2

**Comment by Warkman** [comment]
Okay @huwrowlands thanks.
