### ISSUE TITLE
Unnecessary Grid classes in comments

### ISSUE THREAD

**Issue by andycochran** [JeremyEnglert/JointsWP#188]
Is there a reason for these grid classes here? 
https://github.com/JeremyEnglert/JointsWP/blob/master/assets/functions/comments.php#L11

**Comment by JeremyEnglert** [comment]
Looks like it may have been from before the media object component was created. I'll get it pulled out.

Nice catch! :+1:

**Comment by JeremyEnglert** [comment]
Been slacking lately! But this has been fixed.

https://github.com/JeremyEnglert/JointsWP/commit/f08bff34fc554a4c9677494bf122d2a8cec9543e
