### ISSUE TITLE
gulp-minify-css depreciated

### ISSUE THREAD

**Issue by MkBeeCtrl** [JeremyEnglert/JointsWP#189]
Hey Jeremy!

I'd like to remind that gulp-minify-css is depreciated and we (jointswp users and developers :) ) should use gulp-minify-css instead. Can you please update gulpfile.js?

Best regards,

Nicholas

**Comment by JeremyEnglert** [comment]
css-nano was added recently.

https://github.com/JeremyEnglert/JointsWP/blob/master/gulpfile.js#L5
