### ISSUE TITLE
Additional Content in the Off-Canvas area

### ISSUE THREAD

**Issue by gabrielbajada** [JeremyEnglert/JointsWP#194]
Hi @JeremyEnglert,

I'm using nav-offcanvas-topbar.php and would like some additional content (which includes a sidebar) to live alongside the menu when tapping the hamburger icon. I can't figure out where to start from. Where does the additional code go?

Help please!

Gabriel & @lukexiki.

**Comment by JeremyEnglert** [comment]
Sorry for the slow response!

The off-canvas menu is F6 is alot different than F5.

The content for off-canvas is found in: parts/content-offcanvas.php

**Comment by gabrielbajada** [comment]
Thanks @JeremyEnglert. We sorted it out a different way, but this is great to know.

Thanks again,

Gabriel & @lukexiki.
