### ISSUE TITLE
Flex grid column stacking (class needed)

### ISSUE THREAD

**Issue by beardsavvy** [JeremyEnglert/JointsWP#195]
I'm trying out the flex grid and I noticed that columns don't stack below the small breakpoint. I think this is because they need an explicit `small-12` class added to the column div. Could you confirm, or did I miss something?

**Comment by JeremyEnglert** [comment]
This sounds like a Foundation bug. Have you tried it on a default Foundation install? (Without WordPress)

**Comment by beardsavvy** [comment]
It's in the [flex grid Foundation docs (see Responsive Adjustments)](http://foundation.zurb.com/sites/docs/flex-grid.html#responsive-adjustments). I think Joints needs the `small-12` class added to containers in files like page.php, archive.php, sidebar.php, etc. This won't affect sizing in other cases and will ensure the intended behaviour in the flex grid.

**Comment by JeremyEnglert** [comment]
This has been corrected in the upcoming version. 

https://github.com/JeremyEnglert/JointsWP/pull/230
