### ISSUE TITLE
Switched offcanvas from left to ride side, dropdown portions don't work?

### ISSUE THREAD

**Issue by jdfweb** [JeremyEnglert/JointsWP#196]
Hey Jeremy,

Here's the link: http://bit.ly/1Qucvu9. So yeah, if you click open the menu and try clicking on Products, it doesn't open to the menu items underneath it. I switched the menu from the left side (as it is default) to the right side. Do I have to change something else in order to make this show the other dropdown items when clicked?

Please let me know!

**Comment by JeremyEnglert** [comment]
Can you share the piece of code you changed?

**Comment by jdfweb** [comment]
I believe it was in nav-top-offcanvas.php, here's my code:

`<div class="sticky show-for-small-up contain-to-grid">
	<nav class="tab-bar">
		<section class="tab-bar-section">
			<a href="/rock/" title="<?php bloginfo('name'); ?>">
				<img class="logo" src="<?php echo get_template_directory_uri(); ?>/assets/images/home/logo.png" alt="Rock With Us - Logo" title="Rock With Us - Logo"/>
			</a>
		</section>
		<section class="right-small">
			<a href="#" class="right-off-canvas-toggle"><span class="menu">MENU</span></a>
		</section>
	</nav>
</div>

<aside class="right-off-canvas-menu show-for-small-up">
	<?php joints_off_canvas(); ?>
</aside>

<a class="exit-off-canvas"></a>
`

Also, this is F5! Not F6.

**Comment by jdfweb** [comment]
Any fix for this?

**Comment by JeremyEnglert** [comment]
Looks like you got this figured out - sorry for the super slow follow up. It's hard to troubleshoot the older versions.
