### ISSUE TITLE
Translation not working.

### ISSUE THREAD

**Issue by alexberny** [JeremyEnglert/JointsWP#197]
Hey Jeremy,

I'm an italian developer. I have installed the theme but the translation function is not working properly. I try to change different languages but I can only see English.
Other themes are working greet.

Please let me know,
Alessandro

**Comment by DesignMitZweiS** [comment]
Same here, german translation doesn't work. The content of the .mo file looks right tho.

**Comment by dimbak** [comment]
Hi, how do you test this? how do you change language?

**Comment by alexberny** [comment]
Hi,

In one project Ijust replace searchform.php with the original form:

`<form role="search" method="get" class="search-form" action="<?php echo home_url( '/' ); ?>">
	<label>
		<span class="screen-reader-text"><?php echo _x( 'Search for:', 'label' ) ?></span>
		<input type="search" class="search-field" placeholder="<?php echo esc_attr_x( 'Search &hellip;', 'placeholder' ) ?>" value="<?php echo get_search_query() ?>" name="s" title="<?php echo esc_attr_x( 'Search for:', 'jointswp' ) ?>" />
	</label>
	<input type="submit" class="search-submit button" value="<?php echo esc_attr_x( 'Search', 'submit button' ) ?>" />
</form>
`

In another project i used WMPL plugin (It was a multilanguage site)

**Comment by dimbak** [comment]
it looks like the parameter $context is missing from searchform.php https://codex.wordpress.org/Function_Reference/esc_attr_x

you can change these strings 

` esc_attr_x( 'Search...', 'jointswp' ) 
esc_attr_x( 'Search', 'jointswp' )
`
to

`esc_attr_x( 'Search...','label', 'kmills' )
esc_attr_x( 'Search', 'submit input','kmills' )`

I am not sure how WPML works with the theme, i have not tested it.

**Comment by oleva** [comment]
Hi!

Has somebody got the translations working? I'm now on JointsWP 5 Beta and they are not working.

I got all the new translation strings with Poedit, no problems. But they just don't work. I tried what dimbak suggested but that removed the entire string.

**Comment by dimbak** [comment]
do you mean that none works?

**Comment by oleva** [comment]
Yep, can't get any to work. The plugins and wordpress are translated, but the theme doesn't get any translations. This should be automatic, right? So that it gets the correct translation needed from Wordpress and not from some setting?

**Comment by dimbak** [comment]
I dont think so, the automatic translations are coming from wordpress.org but Joints is not there, you have to translate the theme and move the mo files in the wp-content/languages/themes folder

**Comment by oleva** [comment]
Well, that doesn't seem to work.

I also thought that Joints gets the translations straight from functions/translation/

Or atleast it has in functions/translation/translation.php
~~~
add_action('after_setup_theme', 'load_translations');
function load_translations(){
	load_theme_textdomain( 'jointswp', get_template_directory() .'/assets/translation' );
}
~~~

Now, this /assets/translation folder does not exist, but even if I create it and upload the translations there, they still don't work. Translations are by default in /functions/translation

**Comment by dimbak** [comment]
you are right, there are no translation yet for 5.0, they will be added later i believe.

**Comment by oleva** [comment]
Yep. I got them to work now. I had the wrong locale set for the file name.

In Finland it's only fi.mo, not FI_fi.mo. Silly me. Been working on Magento so much lately that forgot these Wordpres quirks.
https://wpcentral.codekitchen.eu/internationalization/

I got the translation straight with PO-edit from the theme files. There's not much changes from older version, for search there's some extra dots etc.

I can upload the entire Finnish translation once the 5.0 comes out of Beta.

So just setup the correct file path in functions/translation/translation.php and make sure you have the correct locale for FILENAME :P

Thanks for your help dimbak!

**Comment by Mace76** [comment]
Hi,

could someone provide a way to get the translations to work? I'm pretty stuck because it looks like everything is in place (functions, translation files, the path to the translation assets) but nothing seems to work. I also used wp's theme check plugin to get a hint and there it says that the theme uses more than one text domain and that this makes it uncompatiple with the wordpress language packs.

Hope someone can help because I'm already half way through my first jointswp project and now realize that some features do not work that much out of the box as I'd hoped.

I'm using the css version of jointswp by the way.

Thanks in advance. Mace

**Comment by dimbak** [comment]
Hi Mace, you are using the 4.0 version thats great, could you post the path the language files and their filenames and the language you want to use?

**Comment by Mace76** [comment]
Hey dimbak,

my functions.php says this:
// Adds support for multiple languages
require_once(get_template_directory().'/assets/translation/translation.php'); 

the translation.php in this folder says:
// Adding Translation Option
add_action('after_setup_theme', 'load_translations');
function load_translations(){
	load_theme_textdomain( 'jointswp', get_template_directory() .'/assets/translation' );
}

both de_DE.po and de_DE.mo are in the same "translation" folder the translation.php is in.
I see no reason why it shouldn't work.

Let me knwo when you need more info and thanks.

**Comment by dimbak** [comment]
You don't need to change anything in the php files, check [here ](https://codex.wordpress.org/Installing_WordPress_in_Your_Language) the manually installing part.Create the directories and move the mo file there with the filename like jointswp-de_DE.mo 

more info [here ](https://developer.wordpress.org/themes/functionality/localization/)

**Comment by Mace76** [comment]
Hi dimbak,

thanks for the hints, but unfortunately it didn't work out.
there had been a language directory already so I didn't need to create one. so far so good.
there is also another directory inside "languages" called "themes". does the jointswp-de_DE.mo need to go there as it already contains mo files from the default wordpress themes?

Some of the translations seem work because it displays things like category and archive in the sidebar in german but the search field and its button or the read more from the excerpt are still in English.

By the way my textdomain isn't jointswp anymore because I don't use a child theme and Theme Check still says that due to several text domains the theme is not compatible with Wordpress' language packs.

**Comment by dimbak** [comment]
something else is happening here, i am looking in to it, i will update you when i have news.

**Comment by Mace76** [comment]
if you need further infos let me know and thanks in advance for the helping hand.

**Comment by dimbak** [comment]
It's okay, found the issue, the po files need updating that is all.You can do that using Poedit or some other method.With Poedit the easiest way is to follow the instructions [here](https://github.com/fxbenard/Blank-WordPress-Pot).I personally prefixed the _x and esc_attr_x functions just in case 

example

`<form role="search" method="get" class="search-form" action="<?php echo home_url( '/' ); ?>">
	<label>
		<span class="screen-reader-text"><?php _x( 'Search for:','jointwp-screen', 'jointswp') ?></span>
		<input type="search" class="search-field" placeholder="<?php echo esc_attr_x( 'Search...','joints-placeholder','jointswp' ) ?>" value="<?php echo get_search_query() ?>" name="s" title="<?php echo esc_attr_x( 'Search for:','jointswp-search-string','jointswp' ) ?>" />
	</label>
	<input type="submit" class="search-submit button" value="<?php echo esc_attr_x( 'Search','joints-submit-button', 'jointswp' ) ?>" />
</form>`

[here](https://www.cssigniter.com/ignite/wordpress-poedit-translation-secrets/) is an article explaining some secrets about the process 

you can choose the file and its filename depending on where you want to place it, if in the theme's assets/translations folder name it like you see the po/mo files there, if in wp-content/languages/themes then you can name it with the theme's name and the locale.

Important don't forget to add the text domain in the style.css and rename your JointsWP folder theme to the same name.

**Comment by JeremyEnglert** [comment]
Hi everyone,

Sorry for the holdup on this. I'm going to be diving into it this weekend to see what needs to be adjusted.

**Comment by Mace76** [comment]
@dimbak thanks man, had no time so far to give it a try but will report as soon as I get it going.
@JeremyEnglert cool, please keep us updated. cheers!

**Comment by JeremyEnglert** [comment]
This should fix the issue most people were having: https://github.com/JeremyEnglert/JointsWP/pull/363
