### ISSUE TITLE
non-minified scripts loaded in enqueue-scripts.php file

### ISSUE THREAD

**Issue by vibrantpress** [JeremyEnglert/JointsWP#198]
Hi Jeremy,

I noticed 2 foundation scripts were being loaded rather than the minified version in the enqueue-scripts.php file. Not sure if this was intentional or not. I've edited these lines of code in my local files to the minified versions without issue.

Thanks,
John

// Adding Foundation scripts file in the footer
    wp_enqueue_script( 'foundation-js', get_template_directory_uri() . '/assets/js/foundation.js', array( 'jquery' ), '6.2', true );

// Adding scripts file in the footer
    wp_enqueue_script( 'site-js', get_template_directory_uri() . '/assets/js/scripts.js', array( 'jquery' ), '', true );

**Comment by vibrantpress** [comment]
Perhaps this is related to your plan to update the theme as you've described in another thread?

**Comment by JeremyEnglert** [comment]
You are correct! The new workflow will address this.
