### ISSUE TITLE
Changing the_content to the_excerpt doesn't pull in custom button content.

### ISSUE THREAD

**Issue by iamchaka** [JeremyEnglert/JointsWP#199]
Hi,

In the loop-archive.php, I changed the_content to the_excerpt. All fine there, works great. But it still shows the default WP read more link: … Read more »

Is there a different approach to this, am I not activating it properly?  Thanks for your time.

**Comment by ayezee33** [comment]
You could use a filter and remove the read more link from the_excerpt and you might even be able to do it conditionally (never tried it)

**Comment by iamchaka** [comment]
Thanks @ayezee33 , I ended up building a work around. Thanks for the feed back and sorry for the late reply.
