### ISSUE TITLE
Off Canvas Fails to open in Safari 8.0.8

### ISSUE THREAD

**Issue by damacs** [JeremyEnglert/JointsWP#200]
Hi Jeremy, in Safari 8.0.8 on Mac (release dec 2015) the Off Canvas Menu fails to open upon compiling of SCSS. See following link: http://e-i-eng.wurkhouse.com - any idea of why this may be happening? Thanks for any help or advice in advance.

**Comment by fabianbluesplat** [comment]
Problem resolved by commenting out line 28 of gulp file.js:

`
// browsers: ['last 2 versions'],
`

**Comment by JeremyEnglert** [comment]
8.0.8 is pretty old. Safari 10 has been out for a bit.

Foundation supports the latest two versions of Safari (9 and 10). So 8 may be hit-or-miss.

Tested in Safari 9 - works as expected.
