### ISSUE TITLE
Monster Widget Plugin shown Notices

### ISSUE THREAD

**Issue by MrShabir** [JeremyEnglert/JointsWP#203]
Hello Everything is working fine without Monster Widgets Plugin. But When i Install Monster Widget Plugin and Place this as a widget to test WordPress All Widgets its shown notices.

NOTICE: E:\VertrigoServ\www\wp\wp-includes\widgets.php:1039 - Undefined index: WP_Widget_Archives
NOTICE: E:\VertrigoServ\www\wp\wp-includes\widgets.php:1039 - Undefined index: WP_Widget_Calendar
NOTICE: E:\VertrigoServ\www\wp\wp-includes\widgets.php:1039 - Undefined index: WP_Widget_Categories
NOTICE: E:\VertrigoServ\www\wp\wp-includes\widgets.php:1039 - Undefined index: WP_Widget_Pages
NOTICE: E:\VertrigoServ\www\wp\wp-includes\widgets.php:1039 - Undefined index: WP_Widget_Meta
NOTICE: E:\VertrigoServ\www\wp\wp-includes\widgets.php:1039 - Undefined index: WP_Widget_Recent_Comments
NOTICE: E:\VertrigoServ\www\wp\wp-includes\widgets.php:1039 - Undefined index: WP_Widget_Recent_Posts

**Comment by JeremyEnglert** [comment]
The error appears to be coming from wp-includes, which means it would be an issue with WP and/or the plugin. Does this happen with other themes?
