### ISSUE TITLE
Gravity Forms - Disabling AJAX & CSS leaves the validation fields visible

### ISSUE THREAD

**Issue by garrett-eclipse** [JeremyEnglert/JointsWP#204]
Hello,

I followed the instructions here;
http://jointswp.com/demo/gravity-forms/

Which prompted me to disable the css from Gravity Forms.

Initially this worked nicely, however I've recently had to disable AJAX on Gravity Forms as they have a bug introducing a iframe with about:blank src causing 403 on the site.

Anyway, with AJAX disabled and the Gravity Forms CSS disabled as well the form ends up with the validation fields visible.

Please update the Gravity Forms integration to anticipate this and hide the validation fields so that the integration works on forms with AJAX disabled.

Thank you

**Comment by JeremyEnglert** [comment]
I tested this locally using the following method:

1. Installed fresh version of Gravity Forms
2. Disabled CSS
3. Disabled AJAX
4. Submitted a form with an error, the validation error appeared
5. Fixed error, submitted form. 
6. Reloaded page, the error is gone.
7. 

This seems like expected behavior. Did you get something different?

**Comment by garrett-eclipse** [comment]
Sorry @JeremyEnglert I completely overlooked your response, coming back to this the missing piece is honeypot anti-spam is enabled in Settings;
<img width="470" alt="screen shot 2017-11-23 at 11 31 30 pm" src="https://user-images.githubusercontent.com/8726005/33199737-765fd602-d0a6-11e7-9dd1-5c7f83e2c3a4.png">

With this setup the Validation field becomes visible (below it's label is Phone, don't ask me why);
<img width="635" alt="screen shot 2017-11-23 at 11 29 25 pm" src="https://user-images.githubusercontent.com/8726005/33199748-8da3747c-d0a6-11e7-924b-5f8b69ce6881.png">

Looking at it with CSS Enabled the validation container is hidden as follows;
```
.gform_validation_container, .gform_wrapper .gform_validation_container, body .gform_wrapper .gform_body ul.gform_fields li.gfield.gform_validation_container, body .gform_wrapper li.gform_validation_container, body .gform_wrapper ul.gform_fields li.gfield.gform_validation_container {
    display: none!important;
    position: absolute!important;
    left: -9000px;
}
```

With that in mind I'll put a PR together so the JointsWP accounts for the honeypot field.

Cheers

**Comment by garrett-eclipse** [comment]
Actually, @JeremyEnglert can I get your input?
Should the css to hide honeypot be injected as part of JointsWP here;
https://github.com/JeremyEnglert/JointsWP/blob/master/assets/styles/scss/_global.scss

Or should it be kept out of the theme and placed on the tutorial page?
http://jointswp.com/demo/gravity-forms/

Thanks

**Comment by garrett-eclipse** [comment]
Taking a look back at this I decided to merge with the code rather than document as the documentation for GF is succinct and it'd be best not to convolute that. PR coming
