### ISSUE TITLE
Dropdown Submenu Transparency

### ISSUE THREAD

**Issue by ksascomm** [JeremyEnglert/JointsWP#206]
Noticed that if you have a dropdown menu, regardless of the `.dropdown.menu .submenu` background-color, there is still an element of transparency and the body text appears. 

I've reverted to the stock main.scss and the problem still exists, so don't think it's any customization I've done. My [forked repo is here](https://github.com/ksascomm/ksas_cross_divisional_humanities).

![dropdrown submenu transparency](https://cloud.githubusercontent.com/assets/7167138/18326414/9b7098e0-7513-11e6-84d4-8e235887def9.png)

**Comment by andycochran** [comment]
Hard to tell from an image, but this looks like a `z-index` issue to me, not transparency.

**Comment by mmcshinsky** [comment]
I agree with @andycochran. Based on the word "advance" covering the border on the menu, I would have to say z-index issue as well.

**Comment by JeremyEnglert** [comment]
@ksascomm I'm going to close this as it seems theme specific. But I would agree with @andycochran and @mmcshinsky, it appears to be a z-index issue.
