### ISSUE TITLE
Navigation options in demos

### ISSUE THREAD

**Issue by dimbak** [JeremyEnglert/JointsWP#208]
Hi, i am new to this, i may have misunderstood something, 

i am looking your demos and checking the navigations options, when resizing the window to see the small types i always see the same (off-canvas), is that correct? 

Thanks

**Comment by JeremyEnglert** [comment]
It looks like I need to fix the demos - thanks for the heads up!

**Comment by JeremyEnglert** [comment]
This has been fixed. :)
