### ISSUE TITLE
Foundation JS Compile

### ISSUE THREAD

**Issue by jackfearing** [JeremyEnglert/JointsWP#209]
Hi Jeremy, where are you pulling the 6.2.3 files? Are you using the sass download from foundation via this link? http://foundation.zurb.com/sites/download/

Reason I ask is because when I complied there scripts and inspect the 'foundation.min.js' files it seems to still use v.6.2.2. When I inspected the the 'foundation.core.js' file located in the vendor/foundation-sites/js folder is still had v6.2.2 which is what I think was causing it. Any thoughts or maybe I'm looking at it incorrectly? I also noticed this in your compiled version as well. See screen shot.
![screen shot 2016-10-25 at 8 24 23 am](https://cloud.githubusercontent.com/assets/6834687/19692423/bc243ea4-9a8c-11e6-946d-fe8d4fbfd5f2.png)

**Comment by DesignMitZweiS** [comment]
yes, it's still using 6.2.2 in assets/js directory

**Comment by JeremyEnglert** [comment]
I updated the theme to 6.2.4 and corrected this. Thanks guys!
