### ISSUE TITLE
bower + npm

### ISSUE THREAD

**Issue by johnReeve** [JeremyEnglert/JointsWP#211]
I was curious... would you be open to installing the dependencies via bower, and then adding a npm postinstall hook to run bower?  I think it might be more robust than having a vendor/ direcotry already populated with the packages.  If you're interested I'll write that and submit a pull request.

**Comment by JeremyEnglert** [comment]
Personally, I think that's a great idea. But about 50% of people using JointsWP don't use Gulp/Bower/NPM. So for those users, it's helpful to have the necessary files already included.

**Comment by johnReeve** [comment]
Okay; that's good to know.  It makes sense to include the built files if your users cannot build them :D
