### ISSUE TITLE
Feature Request - Foundation Shortcodes

### ISSUE THREAD

**Issue by garrett-eclipse** [JeremyEnglert/JointsWP#212]
HI @JeremyEnglert,

Not sure if this is out of scope for JointsWP, but I saw you were thinking about your next update and was wondering if including Shortcodes for Foundation would be a nice compliment for JointsWP.

Currently, there are three plugins out there for Foundation Shortcodes, but all are for Foundation 5 and they don't seem to be overly well supported or updated;
Easy Foundation Shortcode - https://en-ca.wordpress.org/plugins/easy-foundation-shortcodes/
WP Foundation Shortcodes - https://wordpress.org/plugins/wp-foundation-shortcodes/
Foundation Shortcodes - https://wordpress.org/plugins/foundation-shortcodes/

Bundling a suite of shortcodes in JointsWP for Foundation 6 would be a godsend.

Thank you

**Comment by JeremyEnglert** [comment]
Funny enough, this is actually near the top of our to-do list. However, It will be a separate plugin instead of being baked into the theme.

**Comment by garrett-eclipse** [comment]
I love it @JeremyEnglert thanks for the heads up. Would be happy to help or test for ya. Cheers
