### ISSUE TITLE
Do Foundation files ever "REALLY" need to be included in production?

### ISSUE THREAD

**Issue by JeremyEnglert** [JeremyEnglert/JointsWP#213]
Is there any reason Foundation can't be treated like other "build" tools? As in, do those files ever REALLY need to be on the server?

We can use NPM to install Foundation. Then setup Gulp/Sass to compile custom styles/scripts with the Foundation styles/scripts directly from node_modules.

The "raw" Foundation files never see the server. Also, every time you install the theme, you'll be using the newest version of Foundation. 

@COLABORATI @andycochran @mrscharf

**Comment by mrscharf** [comment]
I think the Foundation files (and entire vendor folder) should stay in the JointsWP repo for a couple reasons. 

First, there seem to be regular breaking changes in Foundation from one version to the next (as was the case in issue #159), and some of these are largely undocumented and very difficult to find. Having the files in the repo helps ensure that we are all looking at and working on the exact same code. Besides, it's possible that they could introduce breaking changes to code that JointsWP has built-in and the version of Foundation specified in the config would be the only one that works correctly anyway.

Second, if this is really a starter theme then I feel that the theme should just work out of the box. I like to drop it in and start editing. Some folks don't always use these tools, so lets not make things more complicated for them. For those who do use the tools, it's quite simple for someone to edit the configs and change/update versions and such.

**Comment by JeremyEnglert** [comment]
Great points. 

If the theme does go in this direction, I would still like to include a version that simply has all of the necessary files and no implied workflow (similar to the CSS version that already exists). 

Currently, the theme attempts to "work for everyone", but that means a lot of compromises. 

For example, if we can assume everyone is using NPM/Gulp, then we can have all JS concatonate into one JS file. Currently we have to load Foundation separately as we can't assume the user is using any type of JS tools. Also, What-Input is called separately. 

That's just one example of where setting an established workflow may have benefits. However, I'd love to continue hearing feedback and arguments for both sides.

**Comment by JeremyEnglert** [comment]
We could also specify a Foundation version in the package.json file if a specific version is problematic.

**Comment by johnReeve** [comment]
Personally, I'd like to see a like to a downloadable zip file with all the assets built (and the node_modules directory removed.  That would give folks who want it to "just work and give me a place to put my css" an option while letting folks (like me) who are going to work with a file watcher have everything all setup to roll with a single JS file.  

Could we just have a zip file that contains a version of the repo after running the build, (probably without the node_modules directory)?  Then folks could dl and unzip that and use it with no build tools, but then if folks are using build tools, they can clone the repo and run some kind of build script that pulls down stuff via bower?  

And then there would be no compiled assets in the repo.  I started on building a branch with this that worked, but it breaks it for the users who want it to work "out of the box" so I didn't pursue it.

I agree that it's a problem to not specify a version number in bower or to require folks to use a build process in order to use it.  But personally, I don't like having dependencies inside a repo.

**Comment by JeremyEnglert** [comment]
> Personally, I'd like to see a like to a downloadable zip file with all the assets built (and the node_modules directory removed. That would give folks who want it to "just work and give me a place to put my css" an option
I like that idea. We're already supporting two versions. So the CSS version could really become a CSS/Sass version with no implied workflow. Just everything you need to get up and running. This is actually very similar to how ZURB handles things. They have a "vanilla" download and then they have the ZURB workflow version of Foundation. 

> I agree that it's a problem to not specify a version number in bower...
I think we can declare a specific version number in the package.json for NPM to download. That way we can check for breaking changes before "officially" supporting a specific version of Foundation. 

> I agree that it's a problem ... to require folks to use a build process in order to use it.
This is probably my biggest concern. It would require a bit of a "start up" process, but FoundationPress and Sage/Roots both require something similar.

Everything would be installed when you ran npm install, so the process would be the exact same if you're already using Gulp.

**Comment by JeremyEnglert** [comment]
Rough version of this up and running on the "4.5" branch. 

https://github.com/JeremyEnglert/JointsWP/tree/4.5

**Comment by kemie** [comment]
So to use the 5.0 branch with codekit I'd have to manually download foundation and set it up to compile to the right folder? In my case it'd be a step backwards in terms of ease of use and potential problems. I might be a small minority though.

**Comment by JeremyEnglert** [comment]
There will be a separate version with everything included. 

However, I strongly encourage you to give NPM and Gulp a try. 

With Joints, everything is already setup. So you don't even need to "learn" NPM or Gulp. You just need to remember 2-3 basic commands and you're set. Here to help if you need it.

**Comment by kemie** [comment]
I might just become a gulp convert, I just have an allergy to the command line :)
