### ISSUE TITLE
JS Off-Canvas-Exit Breaking footer

### ISSUE THREAD

**Issue by AndrewSepic** [JeremyEnglert/JointsWP#219]
Hi Jeremy, 
I'm having a issue where the `<div class="js-off-canvas-exit"></div>` is being injected into my `<footer>` element and breaking the DOM hierarchy. ie: .inner-footer is no longer in the `<footer>` element.  See this screenshot..
<img width="1440" alt="screenshot 2016-12-23 13 50 07" src="https://cloud.githubusercontent.com/assets/1304666/21460522/2e2ce0a6-c917-11e6-9822-697d635ce886.png">

I've made minor edits to footer.php to include some widgets above the .inner-footer div.  Here's my new Footer.php

`<footer class="footer" role="contentinfo">

						
						<?php if ( is_active_sidebar( 'footer' ) ) : ?>
							<div class="row footerWidgets">
								<?php dynamic_sidebar('footer'); ?>
							</div>
						<?php  endif; ?>

						<div id="inner-footer" class="row">
							<div class="large-12 medium-12 columns">
								<nav role="navigation">
		    						<?php joints_footer_links(); ?>
		    					</nav>
		    				</div>
							<div class="large-12 medium-12 columns">
								<p class="source-org copyright">&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?>.</p>
							</div>
						</div> 
					</footer> 
				</div>  
			</div> 
		</div> 
		<?php wp_footer(); ?>
	</body>
</html> 
`
So you can see from the screenshot, the .js-off-canvas-exit div is breaking the hierarchy outlined by the footer.php template.  My sidebar code is correct and there isn't any open tags.  Not sure what's happening or which file controls where that .js-off-canvas-exit div is injected.

**Comment by AndrewSepic** [comment]
#OhCrap I had some bad code in my widget that was causing this.  Closing this!

**Comment by JeremyEnglert** [comment]
Sorry for my slow response! Glad you got this worked out!
