### ISSUE TITLE
Contact Form 7 no success message

### ISSUE THREAD

**Issue by davestyp** [JeremyEnglert/JointsWP#221]
On a default install of joints-wp the popular plugin CF7 doesn't generate a success message.

js?

**Comment by AndrewSepic** [comment]
You should be able to check console in Developer tools to see if there's a JS error being thrown..

**Comment by davestyp** [comment]
Nothing in the console

**Comment by AndrewSepic** [comment]
@davestyp I've just loaded up CF7 into a new site build and the success message works fine for me. You can [see it here](www.openrangesg.com/contact-us)  I've done very little CSS or theme customization at this point.  Do you have something online to look at?

**Comment by JeremyEnglert** [comment]
I can not replicate this either. @davestyp, can you provide a link?

**Comment by davestyp** [comment]
No link right now. Probably just me then :)
