### ISSUE TITLE
Responsive dropdown menu

### ISSUE THREAD

**Issue by dimbak** [JeremyEnglert/JointsWP#223]
Hi, i am working on a site using JointsWP (thanks!) and i saw my menus 'jumping' , i looked your demo and i can see it there too.I think the 'dropdown' class has to do with it.

If you click on the 'Foundation Features' menu you should be able to see it.I am on a pc and i can see it with all browsers.

Any ideas what is causing it?

Thanks

**Comment by JeremyEnglert** [comment]
I believe the "jump" you are seeing is from the dropdown arrows being added. They are added via JavaScript, so the page does fully load before they are inserted - causing a slight jump/flicker.

**Comment by newdesignideas** [comment]
Perhaps we can add the arrows smoothly via CSS (transforms or something simpler) and have JavaScript as a fallback.

I mark a sample up later today evening.

**Comment by JeremyEnglert** [comment]
I was wondering why this issue sounded familiar. I had the same problem when Foundation 6 launched. I wrote docs that explain how to fix it: https://foundation.zurb.com/sites/docs/dropdown-menu.html#preventing-fouc

Note: this is a Foundation component. So if there is a better way to handle it, the change will need to be added to Foundation (not JointsWP).

**Comment by dimbak** [comment]
Thanks,  i see they included it already, in my case the problem was coming from this code

https://foundation.zurb.com/sites/docs/responsive-navigation.html#preventing-fouc

still trying to figure out why

**Comment by JeremyEnglert** [comment]
You'll need to write a custom menu walker that adds the `.is-dropdown-submenu-parent` class to menu LI elements that have children elements.

**Comment by dimbak** [comment]
I just downloaded the 6..3.0 version and i can see the class included by default, i am sorry if i misunderstood you.

**Comment by JeremyEnglert** [comment]
You'll see the class in the inspector tools as it is added dynamically with JS when the page loads. But the class isn't hard coded in. You'll need to hard code it to avoid the flicker. 

I'm going to leave this open for now. Maybe it's something that can be addressed in JointsWP 5.

**Comment by JeremyEnglert** [comment]
Closing this. This is default Foundation 6 behavior. Hopefully we can handle this better with Foundation 7.
