### ISSUE TITLE
'buildScripts' errored during npm install

### ISSUE THREAD

**Issue by blueocto** [JeremyEnglert/JointsWP#228]
Trying JointsWP 5.0 for the first time. Ran 'npm install' as per README.

If it help's I've attached the Terminal output, so you can see what it did.
[Terminal Saved Output.txt](https://github.com/JeremyEnglert/JointsWP/files/790603/Terminal.Saved.Output.txt)

**Comment by JeremyEnglert** [comment]
Very odd. It looks like it is having a hard time finding the what-input.js file.

Look in your "node_modules" directory. Is the what-input being downloaded?

**Comment by JeremyEnglert** [comment]
Run this: `rm -rf node_modules && npm install`

Does that fix the issue?

**Comment by blueocto** [comment]
Hey Jeremy,

Sadly not - I've attached the output. 
[Terminal Saved Output 2.txt](https://github.com/JeremyEnglert/JointsWP/files/797071/Terminal.Saved.Output.2.txt)

**Comment by blueocto** [comment]
If I search the folder it can find the what-input.js in the directory : node_modules/foundation-sites/node_modules/what-input/src/ and /dist/

**Comment by JeremyEnglert** [comment]
That's odd. It should be here: 'node_modules/what-input/dist/what-input.js',

**Comment by JeremyEnglert** [comment]
What version of NPM are you running?

**Comment by blueocto** [comment]
Version 2.14.20

**Comment by JeremyEnglert** [comment]
Thanks for hanging in there with me while I try to replicate this. 

What version of Node are you currently running?

**Comment by antistenes** [comment]
I ran into a different but similar install related problem during. Here's the Terminal output: 
[terminal_saved_output.txt](https://github.com/JeremyEnglert/JointsWP/files/830973/terminal_saved_output.txt)

**Comment by JeremyEnglert** [comment]
@antistenes, the theme will work fine despite those warnings. I'm looking for a way to ignore those warnings as they aren't "real" errors.
