### ISSUE TITLE
Breakpoints Offsetting

### ISSUE THREAD

**Issue by webfolkcreative** [JeremyEnglert/JointsWP#229]
I have found that when multiple custom breakpoints are created, using `@include breakpoint()` actually creates an "offset" effect where `@include breakpoint(tabletport down)` actually takes effect where `@include breakpint(tabletland down)` would. In order to stop this I have had to create a `offset: 2651px` breakpoint to stop it from happening (see below):
```
$breakpoints: (
  small: 0,
  medphoneport: 320px,
  lrgphoneport: 375px,
  xlrgphoneport: 414px,
  medium: 640px,
  tabletport: 768px, 
  tabletland: 1024px,
  large: 1024px,
  xlarge: 1200px,
  xlrgtablet: 1366px,
  desktop: 1440px,
  lrgdesktop: 1920px,
  xlrgdesktop: 2650px,
  offset: 2651px;
);
```

**Comment by JeremyEnglert** [comment]
At first look, this seems like a Foundation issue. Have you tested it with a blank Foundation install (non-JointsWP)?

**Comment by webfolkcreative** [comment]
Apologies, I did not receive a notice that a response had been given. I have not, but I will explore that and post back with findings.

**Comment by JeremyEnglert** [comment]
I'm having a hard time replicating this issue. What version of Foundation are you using?

**Comment by webfolkcreative** [comment]
Sorry for the delay! Seems this was a misconfiguration on my end!
