### ISSUE TITLE
Can we use Codekit with this version?

### ISSUE THREAD

**Issue by Warkman** [JeremyEnglert/JointsWP#234]
Setting up codekit and would get the following error when trying to compile style.scss: 

Libsass: Error: File to import not found or unreadable: ../../node_modules/foundation-sites/scss/util/util.
       Parent style sheet: /_MAMP/test/wp-content/themes/where/styles/scss/_settings.scss
        on line 44 of /_MAMP/test/wp-content/themes/where/styles/scss/_settings.scss
>> @import '../../node_modules/foundation-sites/scss/util/util';
   ^

Seems some folders are missing or I am missing something ;)

**Comment by JeremyEnglert** [comment]
You'll need to follow the setup instructions here: https://github.com/JeremyEnglert/JointsWP/tree/5.0#download-jointswp-and-install-dependencies-with-npm

I'm on the fence on whether or not Codekit will be supported "out of the box", as NPM/Gulp seems to be the way forward.

**Comment by Warkman** [comment]
Fair enough, I will have to learn NPN/Gulp before I can use this version.

**Comment by JeremyEnglert** [comment]
The great thing about how it is setup is that you won't need to know much about Gulp or NPM to use it. Everything is already setup - so you'll just need to run basic commands like `npm run watch`.
