### ISSUE TITLE
footer.php

### ISSUE THREAD

**Issue by Warkman** [JeremyEnglert/JointsWP#235]
With line 13 in the footer file I wanted to ask where the opening `<div>` file is located, I've checked the header, index and page files and I seem to not be able to find it?

`</div> <!-- end .main-content -->`

**Comment by garrett-eclipse** [comment]
Hey @Warkman 
That's the end for .off-canvas-content found in the header.php which I believe used to be called main-content.
@JeremyEnglert can you update that comment in the footer to refer to the proper class.
Thanks

**Comment by JeremyEnglert** [comment]
Thanks guys! This has been fixed in 5.0.

https://github.com/JeremyEnglert/JointsWP/commit/63df2ae984250924bac63d4692e3a27b90448a18
