### ISSUE TITLE
Update error "Unexpected token } in JSON at position 114"

### ISSUE THREAD

**Issue by oleva** [JeremyEnglert/JointsWP#236]
Hi.

Trying to update the foundation for the first time and get an bower error, same happens with gulp.

"Unexpected token } in JSON at position 114"

Gulp gives a little more detailed error, but still can't say what it is. Is this even a syntax error?

```
[15:23:36] Using gulpfile \wp-content\themes\mytheme\gulpfile.js
[15:23:36] Starting 'bower'...
[15:23:36] Using cwd:  \wp-content\themes\mytheme
[15:23:36] Using bower dir:  ./bower_components

\wp-content\themes\mytheme\node_modules\bower\lib\node_modules\q\q.js:155
                throw e;
                ^
SyntaxError: Unexpected token } in JSON at position 114
    at Object.parse (native)
    at \wp-content\themes\mytheme\node_modules\bower\lib\node_modules\bower-json\lib\json.js:42:29
    at \wp-content\themes\mytheme\node_modules\bower\lib\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

The only thing close I found was this: https://github.com/bower/bower/issues/2268

Can it be related? The 'gulp watch' still works perfectly fine.

**Comment by Warkman** [comment]
I had similar problems but I am new to gulp.

**Comment by JeremyEnglert** [comment]
Bower was giving us issues in 4.0, which is why we're moving to NPM in 5.0. If you need to update Foundation in 4.0, it will have to be done manually. 

http://jointswp.com/docs/updating-foundation/
