### ISSUE TITLE
Jquery document ready

### ISSUE THREAD

**Issue by oleva** [JeremyEnglert/JointsWP#237]
Hi, I know this is kinda stupid to ask here and most likely it has nothing to do with JoinstWP :P

But, I'm trying to add Zurbs Pizza chart to the theme:
http://zurb.com/playground/pizza-pie-charts

All seems to work fine with the scripts being loaded from the folder etc.

I just get the typical error for wordpress :

~~~
Uncaught TypeError: $ is not a function
    at Object.init (pizza.js:24)
    at HTMLDocument.<anonymous> (myinitfile.js:6)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
init @ pizza.js:24
(anonymous) @ myinitfile.js:6
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
~~~

Normally I just use this in Wordpress, but now it doesn't seem to work:
~~~
jQuery(document).ready(function($){
    Pizza.init();
}); 
~~~

So I thought I drop the question here, just in case there's some quirks with JointsWP.

Thanks in advance!

**Comment by garrett-eclipse** [comment]
It appears the pizza.js file itself is using $ without initializing it, open your pizza.js and then wrap it all in this;
(function($) {
** PIZZA CODE **
})( jQuery );
That should fix your issue.

And you're right this isn't really the right place, you'll want to open a ticket here;
https://github.com/zurb/pizza

And then they'll be able to update pizza.js to be ready for WP as it currently isn't.

Cheers

**Comment by oleva** [comment]
Thanks for that!

For some reason it just didn't take off.

So for someone trying to add charts, I give my thumbs up to C3.JS.
http://c3js.org/

Just add:
"c3": "^0.4.11"
To package.json and add the styles in styles.scss... super simple, easy to update and everything works.

Thanks again Garrett and keep up the good work!

**Comment by garrett-eclipse** [comment]
No worries @oleva
