### ISSUE TITLE
Bower 

### ISSUE THREAD

**Issue by Shipwreck** [JeremyEnglert/JointsWP#238]
Bower commands are returning:

`bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes`

Adding `--verbose --force` is a solution, but I am curious why `"name": "JointsWP",` in bower.json is CamelCase?

**Comment by JeremyEnglert** [comment]
Learn something new everyday! 

This has been fixed here: https://github.com/JeremyEnglert/JointsWP/commit/174d2c889ecc01651ebb4ebccaeec6e623bbe184

Just a heads up, we'll be dropping Bower support in JointsWP 5 in favor of NPM.
