### ISSUE TITLE
Add vendor to Git Ignore?

### ISSUE THREAD

**Issue by Shipwreck** [JeremyEnglert/JointsWP#239]
Trying to tighten up my installations and get them under version control.  Is the `vendor` folder for local development only?

`bower_components` is a temporary staging area where files are extracted to during the bower updating process, from there they are moved to `vendor`, and from there they are minified to their respective files in `assets`?

Should I add `vendor ` to Git Ignore? 

I see `wp_enqueue_script( 'what-input', get_template_directory_uri() . '/vendor/what-input/what-input.min.js', array(), '', true );` but other than that the references I see to the vendor folder are all for sass stuff that gets compiled and minified. 

I have been happily using `browsersync`, do I also need to use the Gulp Task `foundation-js` to minify Foundation files to assets before deployment? 

I've used JointsWP happily for a number of sites but I feel like I'm not totally understanding what is going on. Speaks highly of JointsWP being able to work out of the box, but some of the docs could be more detailed for less savvy users. I'd like to contribute to the docs once I wrap my head around this.

Thanks!

**Comment by JeremyEnglert** [comment]
You are correct! You can definitely add 'vendor' to .gitignore, as long as you move what-input.js somewhere else. 

We're working on a new version of JointsWP that includes improved documentation. Check out the readme file, it does a pretty good job of explaining the workflow and which files go where.

https://github.com/JeremyEnglert/JointsWP/tree/5.0

**Comment by Shipwreck** [comment]
Great! Thanks for everything.

**Comment by Shipwreck** [comment]
JointsWP 5 looks awesome and I see the new `gulpfile` with `what-input` in `node_modules`.  

Overall project simplification with clear docs. Would you suggest moving to 5 pre-emptively with real projects or is it still being heavily worked on? Having a hard time going back to what I'm working on after looking at the new setup...
