### ISSUE TITLE
BrowserSync

### ISSUE THREAD

**Issue by raejlong** [JeremyEnglert/JointsWP#242]
Browser sync does not update to host using WAMP.

**Comment by raejlong** [comment]
gulp browsersync 
not gulp watch

**Comment by JeremyEnglert** [comment]
Did you update the URL in the Gulpfile?

**Comment by raejlong** [comment]
that is the first thing one does :))) thank you !
I saw a lot of folks scratching their head over this...messing with files...and one person had written a month ago he used gulp browsersync
This is working really well...by the way. thank you!

**Comment by JeremyEnglert** [comment]
Glad you got it working!
