### ISSUE TITLE
header.php / off-canvas wrapper

### ISSUE THREAD

**Issue by AmyGail** [JeremyEnglert/JointsWP#243]
On line 37 of header.php, I see this:
	 
I don't see a line commented out. 
Is there a line that I should uncomment if I don't want to use the Off-Canvas-Menu?
(I was able to change the menu to 'title-bar'. Just unclear what to do with the off canvas container.
Thanks, in advance.

**Comment by linuxbastard** [comment]
Look for this part in the `header.php` file:

```
<!-- This navs will be applied to the topbar, above all content
To see additional nav styles, visit the /parts directory -->
<?php get_template_part( 'parts/nav', 'offcanvas-topbar' ); ?>
```

**Comment by JeremyEnglert** [comment]
That's an old note. It's been removed from 5.0.

And @linuxbastard is correct - that is the best way to change the navigation.
