### ISSUE TITLE
Beta 5 - Browsersync + SCSS, CSS Not Loading Immediately

### ISSUE THREAD

**Issue by ukgda** [JeremyEnglert/JointsWP#244]
Hello

Using Beta 5 with browsersync:

When I make changes to SCSS files (e.g. _main.scss) and save the file, browsersync reloads the page but the changes to the css are not shown. If I save the file again, browsersync reloads the page again and this time the changes are visible.

With php files however the behaviour is as expected - change the file, save, browsersync reloads page, changes show.

For information - the browser cache is turned off.

Thank you for making this brilliant tool available!

**Comment by JeremyEnglert** [comment]
Thank you!

This has been fixed here: https://github.com/JeremyEnglert/JointsWP/commit/8f2f7e80bc9d2817232774bb8e4fecf275f62648
