### ISSUE TITLE
jointswp.com is not working

### ISSUE THREAD

**Issue by bmakowski** [JeremyEnglert/JointsWP#245]
Check the website because it's down.

**Comment by linuxbastard** [comment]
yep. been that way for a couple of days. If you need the docs, the site is available on the internet archive 

[JointsWP on the internet archive](https://web.archive.org/web/20160708171337/http://jointswp.com/)

**Comment by linuxbastard** [comment]
The site is now back up. It was a DNS issue according to a tweet from @JeremyEnglert 
[https://twitter.com/JeremyEnglert/status/867059599047745536](https://twitter.com/JeremyEnglert/status/867059599047745536)

**Comment by bmakowski** [comment]
Thanks for letting me know.
