### ISSUE TITLE
HTTPS, javascript and mixed content

### ISSUE THREAD

**Issue by tuomase** [JeremyEnglert/JointsWP#246]
I'm getting mixed content errors when using HTTPS. "Mixed Content: The page at '#' was loaded over HTTPS, but requested an insecure stylesheet '#. This request has been blocked; the content must be served over HTTPS."

What is the file which loads style files that I can change the URL to https?

**Comment by linuxbastard** [comment]
There shouldn't be anything that you need to change, but the file that loads scripts and styles is at:

`asstes > function > enqueue-scipts.php`

Could you double check that your site settings is set to https:// and not http://?

**Comment by tuomase** [comment]
Solved! The problem was a plugin, not the theme.  Thanks anyway linuxbastard!
