### ISSUE TITLE
Package script

### ISSUE THREAD

**Issue by dtlevin** [JeremyEnglert/JointsWP#250]
Is there a script you can run to package up your finished JointsWP template? I know FoundationPress has a "npm run package" that creates a zip file for you to then install. I couldn't fins anything in the docs

**Comment by webfolkcreative** [comment]
I don't believe JointsWP has such script. Might be a nice feature enhancement if enough people find it handy though!

**Comment by JeremyEnglert** [comment]
Great idea! We'll keep this in mind for the next version that will launch with Foundation 7. Putting a "freeze" on all new features for the current version.
