### ISSUE TITLE
Foundation 6.4.0 update

### ISSUE THREAD

**Issue by wgstjf** [JeremyEnglert/JointsWP#253]
Hi Jeremy,

Are you planning on releasing a 6.4.0 update for Joints?

Cheers,

Will

**Comment by ukgda** [comment]
Yes please, I would also very much value an update to 6.4.

Thank you

**Comment by rinseringma** [comment]
Oh yeah, can't wait to get my hands on the new XY Grid! Tried to update myself, but that failed..

**Comment by ukgda** [comment]
I did a bower update 

and then amended my style.scss file to include mixins:

@include foundation-flex-classes;
@include xy-grid;
 @include foundation-xy-grid-classes(
  $base-grid: true,
  $margin-grid: true,
  $padding-grid: true,
  $block-grid: true,
  $collapse: true,
  $offset: true,
  $vertical-grid: true
);

Seems to be working but I certainly wouldn't consider I know enough to use this for prime time!

**Comment by Superanton** [comment]
I would also love to see 6.4 support!

**Comment by codep0et** [comment]
+1 For me, the biggest problem is the gulp babel and minify not working since F6.4+ uses ES2016 and webpack.

**Comment by JeremyEnglert** [comment]
Hi everyone,

We're working on JointsWP 5, which will include 6.4 and the XY grid.

If you want to take it for a spin, the beta can be found here: https://github.com/JeremyEnglert/JointsWP/tree/5.0

Note: We haven't updated the classes to use the new XY grid yet. However, 6.4.1 is running on the 5.0 branch.

**Comment by wgstjf** [comment]
Jeremy,

Thanks for the update and great news about v5!  

We have a project that we need to get cracking on and will massively benefit from the XY grid.  With the exception of the classes is v.5 production ready?  If not, do you have any idea when it will be released?

Cheers,

Will

**Comment by JeremyEnglert** [comment]
We've been using JWP5 Beta with 6.3 for the last few months on many projects - including some very large ones. If you need it right now, you should be good. Most of the changes moving forward will be pretty minor. Nothing you can't implement on your own as you go!

**Comment by wgstjf** [comment]
Perfect, thanks for that and the quick response.  We'll dive straight in then :-)

**Comment by JeremyEnglert** [comment]
Closing this. We're close!
