### ISSUE TITLE
scripts.js not taking affect

### ISSUE THREAD

**Issue by JCarl1989** [JeremyEnglert/JointsWP#255]
I am having trouble adding Slick-1.6.0 to Joints WP, and noticed that the pre-existing js:

// Makes sure last grid item floats left
  jQuery('.archive-grid .columns').last().addClass( 'end' );

is not taking affect as no 'end' class is being added to the last column of a row so (so columns in incomplete rows are not floating left like in all my other Joints WP themes).

my custom scripts are located at js/scripts/*.js and do appear to have been copied/compiled in the  js/scripts.js file.

I am still relatively new to Joints WP - can anyone help?

**Comment by JeremyEnglert** [comment]
Oh wow - that looks like some legacy code.

Older versions of JWP had a "archive-grid" (it allowed you to display posts in a grid format). That particular piece of code you are sharing made sure the last item in the grid didn't float right.

If you want this to apply to all of the columns, remove the `.archive grid.` part of the code - however, I would not recommend that. You'd be better off adjusting this script to be used in specific places.

PS - This chunk of code is going to be removed from JWP 5.
