### ISSUE TITLE
jQuery compile

### ISSUE THREAD

**Issue by jackfearing** [JeremyEnglert/JointsWP#257]
I noticed that when running the build script I'm getting a message of "Use the function form of "use strict". when it hits the js files with jQuery. (See attached). 

Besides commenting out the jshint reference in the gulp file I was wondering if there is a better way to resolve this?

![screen shot 2017-07-06 at 1 33 14 pm](https://user-images.githubusercontent.com/6834687/27931706-02e48854-6250-11e7-866d-2bc5c2918e33.png)

**Comment by jackfearing** [comment]
+1

**Comment by jpagano** [comment]
This commit address this issue
https://github.com/jpagano/JointsWP/commit/511bb30065fc3d2ab7312e45481d6c60796eee87

**Comment by jackfearing** [comment]
That did the trick -- thanks!

**Comment by JeremyEnglert** [comment]
Thanks @jpagano! This has been fixed in the upcoming version as well.
