### ISSUE TITLE
Gulp Watch error on Joints v.5.0

### ISSUE THREAD

**Issue by wgstjf** [JeremyEnglert/JointsWP#258]
Jeremy,

This might not be project related but hoping you might be able to help. 

I have cloned from git JointsWP v.5, installed NodeJS v.6.11.0 and run `npm install` on the relevant folder.  The script completed successfully but when I try `npm run watch` I get the following error.  Any thoughts on how to fix this would be greatly appreciated.  I am using a Windows PC should that have any bearing on the answer:

``` 
jointswp-sass@5.0.0 watch J:\test.com\wp-content\themes\JointsWP
> gulp watch

[11:01:24] Using gulpfile J:\test.com\wp-content\themes\JointsWP\gulpfile.js
[11:01:24] Starting 'watch'...
[11:01:24] 'watch' errored after 63 ms
[11:01:24] Error: Error watching file for changes: UNKNOWN
    at exports._errnoException (util.js:1018:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! jointswp-sass@5.0.0 watch: `gulp watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jointswp-sass@5.0.0 watch script 'gulp watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jointswp-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jointswp-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jointswp-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     J:\test.com\wp-content\themes\JointsWP\npm-debug.log
```

Cheers,

Will

**Comment by wgstjf** [comment]
Further investigation seems to indicate it is a problem only when accessing via the network drive path.  

Do you know of a way around this issue?

Cheers,

Will

**Comment by dabockster** [comment]
Does the error still occur when the project is copied to your local machine? Running executables from network drives has always been an issue (for all programs, not just gulp).

**Comment by wgstjf** [comment]
@dabockster - sorry for the late reply.  

We use a cloud storage app (pCloud) to sync our files (enables us to 'ignore' syncing node_modules folders etc).  The files are all located locally on each machine and we use Mapped Network Drives to provide a navigable location to these files that is the same on each machine.  

If we try to run the 'build' command from the network drive location it errors out.  If we run them from the local folder then all works fine.  It is not the end of the world that we have to navigate to the actual folder before running commands but it is a bit of a time waster and prevents things like running gulp commands from within Atom.

Cheers,

Will

**Comment by JeremyEnglert** [comment]
Is this only an issue with JWP or any Gulp command running on your cloud?

**Comment by wgstjf** [comment]
Jeremy,

Thanks for coming back to me on this.  It seems to be all gulp stuff now though never used to be.  Pretty sure it is not JWP specific.  Unless you have any clever ideas on this I am happy for this to be closed as we have now got into the habit of opening a Powershell window from the local folder rather than the (preferable) mapped network drive.

Cheers,

Will

**Comment by mlangone** [comment]
I am getting gulp watch issues as well this may be a different issue, but whenever I run gulp watch and change any image or add an image to the images folder - Starting 'images' compresses images then continues to run in an endless loop. Is this expected behaviour?

![screen shot 2017-11-09 at 10 15 31 am](https://user-images.githubusercontent.com/4027703/32619284-7fb57556-c537-11e7-95ca-4e1dd6c981da.png)

**Comment by jackfearing** [comment]
I'm having the same issue. The original gulp file was using the newer plugin below but none of the images were compressing since the dest was the same. The latest gulpfile.js version removed the newer plugin which I think is causing the issue so as a band-aid I reverted back and pt the original line of code back. Not really fix just a stop gap to resolve the image loop.
`		.pipe(plugin.newer(ASSETS.images))
`

**Comment by mlangone** [comment]
@jackfearing Thank you I can confirm that this works.
