### ISSUE TITLE
Page builder to use with JointsWP

### ISSUE THREAD

**Issue by pablopaul** [JeremyEnglert/JointsWP#261]
@JeremyEnglert can you recommend a page builder which works with JointsWP and outputs Zurb Foundation markup?

**Comment by JeremyEnglert** [comment]
Personally, I use Advanced Custom Fields Flexible Fields (https://www.advancedcustomfields.com/resources/flexible-content/). It's not so much a "page builder" as it is a "content builder", but it gives you completely control over the markup. We use this on a lot of client sites as it gives them a ton of flexibility without giving them control over markup.

We're also working on a Foundation Shortcodes plugin, but we've put that on the backburner a bit as we were going to rely on Shortcake.

**Comment by garrett-eclipse** [comment]
I'll second @JeremyEnglert on the ACF Flexible Content, it's the direction we took as well
