### ISSUE TITLE
support for Woocommerce

### ISSUE THREAD

**Issue by hazephase** [JeremyEnglert/JointsWP#262]
there is no support for WooCommerce can we have it in the future?

**Comment by bradfranklin** [comment]
Possibly this will help. I haven't tried this yet but will be throwing it in week of Aug 8 2017
https://woocommerce.wordpress.com/2017/02/28/adding-support-for-woocommerce-2-7s-new-gallery-feature-to-your-theme/

**Comment by bradfranklin** [comment]
https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/

**Comment by webfolkcreative** [comment]
It's pretty easy to add. Create a woocommerce.php file in the theme and put something like this in it:

`<?php get_header(); ?>
	<div id="content">
		<div id="inner-content" class="row">
		    <main id="main" class="large-12 medium-12" role="main">
				<?php woocommerce_content(); ?>					
			</main> 
		</div> 
	</div> 
<?php get_footer(); ?>`

**Comment by JeremyEnglert** [comment]
Let's consider adding this to the next version. I think it's a solid idea.

**Comment by johnw6761** [comment]
Did this get added?
