### ISSUE TITLE
tinymce advanced does not recognize add-editor-style

### ISSUE THREAD

**Issue by rfkeller** [JeremyEnglert/JointsWP#263]
I changed the jointswp 4.0 functions.php to require editor_styles.php.

Tinymce advanced 4.6.3 does not recognize the editor style.  In the tinymce editor options page I get this

Create CSS classes menu
Load the CSS classes used in editor-style.css and replace the Formats menu.	
ERROR: A stylesheet file named editor-style.css was not added by your theme.	To use this option, add editor-style.css to your theme or a child theme. Enabling this option will also load that stylesheet in the editor.  

Is this a jointswp or tinymce bug?

**Comment by JeremyEnglert** [comment]
I wasn't able to replicate the issue, but the CSS path was wrong. This has been corrected. 

https://github.com/JeremyEnglert/JointsWP/commit/6deb37a2aa7cb11368b7e3edf723463863b0662a
