### ISSUE TITLE
Using Slick Carousel with JointsWP

### ISSUE THREAD

**Issue by sarahb1206** [JeremyEnglert/JointsWP#264]
I'm running into an issue installing https://github.com/kenwheeler/slick in coordination with JointsWP scss version.

After installing JointsWP, I ran <code>npm install slick-carousel</code>, and then <code>gulp</code>.

Am I supposed to manually add the library to the vendor folder?  I know I need to reference the slick.scss and slick-theme.scss files in the /assets/scss/style.scss, but where do I add the slick.js reference?

I'm sorry if this is rudimentary, I'm new to JointsWP, and determined to learn. Thank you so much for your help.

**Comment by JeremyEnglert** [comment]
Hu @sarahb1206, great choice using Slick! It works really well with Foundation/JointsWP.

Now that you've installed Slick, you'll need to call the JS for Slick. In the 5.0 branch, we've made it much easier to install third party scripts using NPM, but you should be able to apply the same concept to whatever version of JWP you're using. Check it out here: https://github.com/JeremyEnglert/JointsWP/blob/5.0/gulpfile.js#L33

You'll see that we are calling in what-input and then combining it with other scripts - you can do the same thing with Slick. It'll look something like this: `'node_modules/slick-carousel/slick/slick.js'`

You could also just move the files to the vendor folder and enqueue them from there. 

Let me know if this helps! I'm going to "close" this issue, but feel free to continue to ask any questions you have.

**Comment by sarahb1206** [comment]
Thank you so much @JeremyEnglert! I'm using the 5.0 branch now, and love the new organization.  Now that Slick is pulled in from the node_modules folder, I'm running into is loading the resources from Slick. The slick.woff, ajax-loader.gif, and slick.ttf files are throwing a 404.  Is there a way to include these using the gulfile.js as well? Thank you!
