### ISSUE TITLE
Joints v.5.0 - compiling JS

### ISSUE THREAD

**Issue by wgstjf** [JeremyEnglert/JointsWP#265]
Jeremy,

Sorry - one more question for you.

JWP 5.0 (correctly) compiles all the javascript into one file but, one of the benefits of the previous versions was the speed at which the JS compiled due to it not having to incorporate all the Foundation JS when building.  When developing this faster compile was really handy.  I don't suppose there is anyway to keep them separate when in a 'DEV' mode (thus speeding up the compiling) and then combine and compile it all to one file when in 'PRODUCTION' mode?

Not sure if this is of interest to anyone else but, being a gulp novice, I would appreciate any pointers you may have in accomplishing this.

Cheers,

Will

**Comment by JeremyEnglert** [comment]
We're working on improvements so only changes files are linted, which will improve the overall speed. 

Or you could modify your Gulp file to generate separate JS files for Foundation and for Custom scripts. With HTTP/2 becoming more popular, that may be a good route to go. I'll keep that in mind as we work on updates.

Thanks!
