### ISSUE TITLE
Jointswp Version 5 - Codekit option?

### ISSUE THREAD

**Issue by vibrantj** [JeremyEnglert/JointsWP#266]
Hello Jeremy

Is it possible that the jointswp 5 SASS version will be available as a similar version to the current jointswp 6.3.1 SASS version? I've attempted (yet, again) to go the node.js route as described on the github page. It works. However, I would love to take advantage of Foundation's new grid system, while using SASS and Codekit. It seems the newer version of Jointswp is moving away from this model.

Any possibility of maintaining a version that includes the vendor files without having to use node.js?

Thank you for your hard work!

**Comment by Warkman** [comment]
+1 for the above or will that been a tonne of new work and more maintenance?

**Comment by pronkman** [comment]
+1

**Comment by JeremyEnglert** [comment]
After you run `npm install` to install Foundation, you should be able to setup Codekit just like before. The only difference is we're using NPM to maintain Foundation instead of including it with the repo. 

This will also keep your themes smaller, as you'll only be pulling in the pieces of Foundation you need.

**Comment by Warkman** [comment]
Thanks for the update.

**Comment by vibrantj** [comment]
+1 This was my thinking as well.

**Comment by Warkman** [comment]
Im still struggling to get the site working with the new instructions of using node.js, by chance can anyone step me through the process?

**Comment by JeremyEnglert** [comment]
I don't think we'll release a Codekit config file for JointsWP 5, but if someone wants to create one and submit a pull request, I'd be interested in taking a look!

We're shifting gears to focus on JointsWP 6. JointsWP 6 will also rely on NPM/Node for the initial setup.
