### ISSUE TITLE
Question - Using 6.4 xy grid in jwp5 default template files

### ISSUE THREAD

**Issue by bradfranklin** [JeremyEnglert/JointsWP#267]
Using flexbox 6.4 xy grid in jwp5 default template files. 

Are you guys manually amending classes in default files, leaving them alone, or when creating new custom templates just coding files with xy grid classes? i'd like to take advantage of flexbox xy grid in project.  Thanks in advance for input.

**Comment by JeremyEnglert** [comment]
The files are now a part of JWP. It can be found here: https://github.com/JeremyEnglert/JointsWP/tree/5.0
