### ISSUE TITLE
WordPress Standard Photogallery single column only

### ISSUE THREAD

**Issue by vikcon** [JeremyEnglert/JointsWP#268]
I am trying to create a photogallery via WordPress media section, but it is appearing single column only.
Online demo can be checked at https://vikconconsulting.in/ind/facilities/animal-house/

Tried with latest WordPress & fresh copy of JointsWP-SASS locally on WAMP as well as VVV (Ubuntu) same problem.

Can anyone confirm or suggest some fix? 

Backend Gallery created
![backend](https://user-images.githubusercontent.com/1099303/29036368-cdd612e6-7bbc-11e7-926a-294db36de43f.jpg)

Frontend - 
![image](https://user-images.githubusercontent.com/1099303/29036354-c0f3c92e-7bbc-11e7-96cd-b29ca20cf5b3.png)

**Comment by jackfearing** [comment]
You could try adding display inline-block to the .gallery-item class.

.gallery dl.gallery-item {
display: inline-block;
}

**Comment by vikcon** [comment]
Thanks a lot, it works, but there is no padding. 
![image](https://user-images.githubusercontent.com/1099303/29036694-0b95da52-7bbe-11e7-951a-bd2a1328b99c.png)


I will play with CSS for that. 
Many thanks.

Have a great day.

**Comment by jackfearing** [comment]
You could always try applying padding or margin right to the same class. (See updated example below) If you need the last item to be flush then you may need to use last-child or last-of-type to remove the padding-right. Here is a run down of last-of-type from CSS-Tricks: https://css-tricks.com/almanac/selectors/l/last-of-type/

.gallery dl.gallery-item {
display: inline-block;
padding-right:10px;
}

**Comment by vikcon** [comment]
Resolved. You may close the issue now.
