### ISSUE TITLE
SASS node_modules folder

### ISSUE THREAD

**Issue by johnw6761** [JeremyEnglert/JointsWP#269]
I am new to node, command line and SASS but I am trying.

I followed the install instructions in the docs and I now have a 250mb folder in my theme directory called node_modules with over 30k files in it. Is this normal? For every theme I create I am going to have this huge folder? It is playing havoc with my dropbox syncing.

If anyone can shine any light on this I would really appreciate it.

Thanks

**Comment by linuxbastard** [comment]
I too used to suffer from that pain. What I did was create manual a manual node_modules folder before I even run `npm install` and use dropbox selective sync to ignore it. Downside of course is that you have to keep doing this for all your projects, but only once per new project.

**Comment by JeremyEnglert** [comment]
You shouldn't include `node_modules` when you upload the theme or as part of your repos - it's only needed for your local development. 

When working as a team, each user can simply run `npm install` and everyone will have the same dependencies on their local setups.

**Comment by johnw6761** [comment]
@JeremyEnglert So for every jointswp project I need to have a 250mb folder of node modules? Is that correct? 

@linuxbastard I am not on linux I am afraid :(
