### ISSUE TITLE
ID & Class - Selector mix up?

### ISSUE THREAD

**Issue by Shipwreck** [JeremyEnglert/JointsWP#270]
In the templates there are classes:
```
<div class="content">
<div class="inner-content ">
```
But the SCSS is selecting ID's?
```
#content {
	#inner-content {
		padding: 1rem 0rem;
	}
}
```
Shouldn't it be
```
.content {
	.inner-content {
	}
}
```
Looking at [single.php](https://github.com/JeremyEnglert/JointsWP/blob/5.0/single.php) and [main.scss](https://github.com/JeremyEnglert/JointsWP/blob/5.0/assets/styles/scss/_main.scss)

**Comment by linuxbastard** [comment]
What version do you have? The current single.php has:

```
<?php get_header(); ?>
			
<div id="content">

	<div id="inner-content" class="row">

		<main id="main" class="large-8 medium-8 columns" role="main">
```

**Comment by Shipwreck** [comment]
Is [this ](https://github.com/JeremyEnglert/JointsWP/tree/5.0)not the newest version?

I see a commit 8 days ago to [change ID to classes](https://github.com/JeremyEnglert/JointsWP/commit/f20ed433190459a8bccec61c5e352b1e29283cbb) but nothing for five months in [main.scss](https://github.com/JeremyEnglert/JointsWP/blob/5.0/assets/styles/scss/_main.scss).

**Comment by linuxbastard** [comment]
Ahh you're on the JWP5 branch. I don't think that's ready for production yet. I was looking at the master branch. The new 5 is going to use Foundation 6.4 and the XY grid so there may be a few changes with class names and such.

**Comment by JeremyEnglert** [comment]
Nice catch! However, since we don't really need those styles, I removed them completely. 

https://github.com/JeremyEnglert/JointsWP/commit/6307ef7628575b10f71045ea66198dcb0a0dbbb4
