### ISSUE TITLE
Flex utilities not working with XY Grid

### ISSUE THREAD

**Issue by arelidev** [JeremyEnglert/JointsWP#271]
I've noticed that as it's defaulted vertical alignments such as align-top and align-center do not work with the XY Grid components. I had to include both foundation-flex-grid; and foundation-flex-classes for them to work. Is that by design?

**Comment by JeremyEnglert** [comment]
Hi @arelidev, that sounds like it is Foundation related. XY doesn't include the helper classes - but you can still use `align-items: center;` in your Sass/CSS.
