### ISSUE TITLE
SASS, node and dropbox syncing

### ISSUE THREAD

**Issue by johnw6761** [JeremyEnglert/JointsWP#272]
I am new to node, command line and SASS but I am trying.

I have a 250mb folder in my theme directory called node_modules with over 30k files in it. Is this normal?  
For every jointswp project I need to have a 250mb folder of node modules? Is that correct?

I also have an issue when going between PC and Mac that I need to install Node each time as it comes up with an error if not. Does anyone have this same experience? This causes Dropbox to sync 30k files everytime I do this which is very unpractical.

I am sure I must be doing something wrong as this method of working is very slow.

Any help with these issues would be greatly appreciated.

Thanks

**Comment by JeremyEnglert** [comment]
> I have a 250mb folder in my theme directory called node_modules with over 30k files in it. Is this normal? For every jointswp project I need to have a 250mb folder of node modules? Is that correct?
Yup! This is correct. But you _only need these in your local environment.._ You shouldn't upload them to your server.

> I also have an issue when going between PC and Mac that I need to install Node each time as it comes up with an error if not. Does anyone have this same experience? This causes Dropbox to sync 30k files everytime I do this which is very unpractical.
Similar to the above. You shouldn't have these files synced on DropBox. But you will need to install them on every machine you work on this project on. The package.json file makes it so you can share the theme with other developers and they can easily install the same node_modules that you're using. 

I'm going to close this. But let me know if you have any other questions!

**Comment by johnw6761** [comment]
@JeremyEnglert If I have the theme in my dropbox folder and node needs to be installed into the theme directory how can I not have the node_modules folder in my dropbox?

**Comment by linuxbastard** [comment]
@johnw6761 I make it a point to do selective sync on my folders for my windows machine. There's also a command tool to ignore specific folders in linux distros (only tried it on ubuntu). That way those node_module folders don't get synced to my dropbox.

**Comment by johnw6761** [comment]
@linuxbastard @JeremyEnglert When you do selective sync doesnt it remove that folder completely from your dropbox?

**Comment by linuxbastard** [comment]
It shouldn't. It should only "not sync" the node_modules folder, not remove it. Best way is to try it. Create a new project. create a node_modules folder, use selective sync to ignore that folder. then run the npm install and check if it sync or deletes the folder.

**Comment by johnw6761** [comment]
@linuxbastard @JeremyEnglert So I use a combination of PC and Mac (Desktop and laptop) and my workflow to setup a SASS jointswp project is:
1. Download theme and add to my dropbox
2. Manually create node modules folder then tell dropbox not to sync that folder which it then removes from my dropbox folder.
3. Install node (after above step the created node modules folder will not sync)
4. Repeat steps 2 and 3 for second device (so now I have 500mb worth of node files across my two devices just for one project!)

I cant help but feel the benefits of using SASS are diminished due to the above process I need to go through particularly for smaller projects. Again I can't help but feel I am doing something wrong and there must be a more efficient workflow process.

**Comment by JeremyEnglert** [comment]
What's the idea behind developing inside of an active DropBox folder? I've never heard of this method until now.

**Comment by johnw6761** [comment]
@JeremyEnglert So my files are always synced between my two devices.

**Comment by sdatic** [comment]
I don't know if you have this setup or have considered it but your sync should be less of an issue if you use LAN sync through dropbox, make sure the ports are open, you're on the same subnet and connected to the same access point to make sure you are taking advantage of your local network for syncing. 

Based on your workflow, even if you sync all the folders, once they are in sync, they shouldn't go through the upload or sync process again unless changed. 250mb locally should take no time, 250mb is workable especially if most of the files don't change after the initial sync.

Jeremy already said that the files are required for the build so this is more of a dropbox related conversation at this point wouldn't you say? Have you ever considered hosting owncloud for an internal solution with no WAN lag?

My 2cents. Happy coding!

https://www.dropbox.com/help/syncing-uploads/lan-sync-overview

**Comment by johnw6761** [comment]
@sdatic the node folders sync because when going between PC and MAC the files get updated due to the different OS I presume. 

I think I just find it strange I require 250mb of files when most of my web projects are normally nowhere near this size. It seems very unnecessary and clunky.

**Comment by sdatic** [comment]
This is not related to JointWP, Joints just uses npm...the dependancies and file size are inherent in the npm install. Joints utilizes some of the dependancies/functions of npm to make development easier for us. The state of npm and many other libraries is unfortunate but they are created at the core to be useful tools to make things easer on us, the developer.

Here is an article about the bloat happening in these scripts. https://medium.com/friendship-dot-js/i-peeked-into-my-node-modules-directory-and-you-wont-believe-what-happened-next-b89f63d21558

At this point the project benefits from the use of npm more than it suffers with a "bloated" dependancies. I'm sure someone out there is working on another option but this isn't a JointWP thing but rather an npm thing and not required as Joint's offers a CSS version that doesn't require these dependancies. 

Hope this helps.

**Comment by JeremyEnglert** [comment]
> @JeremyEnglert So my files are always synced between my two devices.

Why not use Git? It seems like it would work just as well, plus you could avoid potential headaches like this one. 

And big thanks to @sdatic! You're spot on.
