### ISSUE TITLE
Responsive tabs

### ISSUE THREAD

**Issue by jackfearing** [JeremyEnglert/JointsWP#273]
Anybody else having issues with the responsive tabs function? Both the regular and accordion functions work fine but not the responsive tabs. When I inspect the console I'm getting a js error even though the js file for responsive tabs is being loaded.  See below.

https://user-images.githubusercontent.com/6834687/29645629-afc268c6-8833-11e7-8009-6a4e05621cc8.png

**Comment by jackfearing** [comment]
+1

**Comment by KiwiCreative** [comment]
Same as you. I couldn't get the responsive tab/accordion to work either, but regular tabs and accordions work fine.

**Comment by jackfearing** [comment]
Yes regular and accordion work but not the responsive -- strange. Not sure if this is a foundation thing or not? Have you had any luck getting it to work yet?

**Comment by jackfearing** [comment]
Anybody have a solution for this yet?

**Comment by jackfearing** [comment]
I needed up reordering the responsiveAccordionTabs.js file located in the gulp.js file which solved the issue. Just place the responsiveAccordionTabs.js after the foundation.tabs.js. See below.

FOUNDATION + '/dist/js/plugins/foundation.tabs.js',
FOUNDATION + '/dist/js/plugins/foundation.responsiveAccordionTabs.js',

**Comment by KiwiCreative** [comment]
@jackfearing unfortunately that did not work for me. After I do, I get the following console error:

foundation.core.js:358 TypeError: Right-hand side of 'instanceof' is not an object
    at e.value (foundation.responsiveAccordionTabs.js:304)
    at e.value (foundation.responsiveAccordionTabs.js:239)
    at e.value (foundation.responsiveAccordionTabs.js:200)
    at e.t (foundation.core.js:553)
    at new e (foundation.responsiveAccordionTabs.js:175)
    at HTMLUListElement.<anonymous> (foundation.core.js:356)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at String.<anonymous> (foundation.core.js:338)
    at Function.each (jquery.js?ver=1.12.4:2)

I found [this discussion](https://github.com/zurb/foundation-sites/issues/10520) in foundation's GitHub page, but unfortunately the fix is above my skill level. I don't know what Babel and Webpack are :-(

**Comment by Zimple-pro** [comment]
Helllo @KiwiCreative , did you find a solution?

Thx

**Comment by KiwiCreative** [comment]
Hi @Zimple-pro 

Unfortunately no, I ended up doing what I did not want to do...making an accordion and tabs separately, then using the visibility classes to hide and show on different screen sizes. You're best bet would be to ask the theme author directly. 

@JeremyEnglert, has this issue been addressed in the newest distribution of JointsWP 5? If not, could you possibly provide some advice on how we can fix this in the version where the responsive accordion tabs are not working? Thanks!

**Comment by garrett-eclipse** [comment]
Can any of you share a live link of this issue along with you theme packaged up for me to look at?

Also @KiwiCreative when you made the change @jackfearing indicated with moving foundation.responsiveAccordionTabs.js after foundation.tabs.js did you reset your project?
After making the changes can you purge your node_modules (run `rm -rf node_modules`) and then rerun `npm install` before checking in browser. If you just make changes to the gulpfile.js without recompiling then there'd be no change with the rendered files.
*Hoping it's that simple, but if not provide a test site w/ package so we can troubleshoot.

Thanks

**Comment by JeremyEnglert** [comment]
Im able to replicate this issue on a fresh install.

It may be an issue with Foundation's use of Webpack. Trying to troubleshoot it.

**Comment by garrett-eclipse** [comment]
Thanks @JeremyEnglert, when I looked at the npm code it was definitely littered with WEBPACK constants and many were on the right on instanceof calls so I think that's a good route to go down.

**Comment by Zimple-pro** [comment]
Hi @garrett-eclipse and @JeremyEnglert , how can I solve this?
Thanks!

**Comment by garrett-eclipse** [comment]
@JeremyEnglert is troubleshooting this.

But did you try @jackfearing solution?
> I needed up reordering the responsiveAccordionTabs.js file located in the gulp.js file which solved the issue. Just place the responsiveAccordionTabs.js after the foundation.tabs.js. See below.
> 
> FOUNDATION + '/dist/js/plugins/foundation.tabs.js',
> FOUNDATION + '/dist/js/plugins/foundation.responsiveAccordionTabs.js',
*make sure to run `npm install` again or `npm run build` (or `gulp` if using JWP 4)

Not sure if that's the solution, let us know if it works. Otherwise @JeremyEnglert will hopefully have a solution.

**Comment by jackfearing** [comment]
For reference, below is a screen shot showing how I reordered the scripts to get the responsive tabs working.

![screen shot 2018-01-16 at 12 36 03 pm](https://user-images.githubusercontent.com/6834687/35011101-ec26bd28-fab9-11e7-9831-a4abed1cef64.png)

**Comment by Zimple-pro** [comment]
@garrett-eclipse / @jackfearing I tried before and didn't work but I tried now just compiling the script and works!

@KiwiCreative you need to edit the gulpfile.js (theme root) and move the line number 40 (FOUNDATION + '/dist/js/plugins/foundation.responsiveAccordionTabs.js',) under the 48 (FOUNDATION + '/dist/js/plugins/foundation.tabs.js',)
as the picture from @jackfearing 

And go to the terminal and open the theme directory and run  'npm run scripts' without quotes

Thank you everybody!

**Comment by JeremyEnglert** [comment]
Thanks @jackfearing and everyone! I'll test that fix locally and push a fix to the master branch.

**Comment by garrett-eclipse** [comment]
Niiice, thanks for testing and confirming @Zimple-pro. Hoping that fixes this for @KiwiCreative as well, please let us know. And I'll leave the fix there for you @JeremyEnglert, glad to see this coming to a close. Cheers

**Comment by KiwiCreative** [comment]
Thanks for the info everyone, very helpful!

**Comment by garrett-eclipse** [comment]
Closing as this was resolved in PR #374.
