### ISSUE TITLE
Gulp build update

### ISSUE THREAD

**Issue by MkBeeCtrl** [JeremyEnglert/JointsWP#274]
Hey Jeremy, 

Last days I was struggling with Gulp optimization, and as I use your JointsWp a lot, I thought that I will share my discovery with you. My previous gulpfile.js was made on top of yours from Joints, so there are many similarities (I think)

My project got pretty big, with compilation up to 19seconds on my Mac Pro 2016 (ususaly it;s not longer than 9 seconds - for regular sized projects), after changing gulpfile I am not able to make it longer than 3 seconds.

Here's the stackoverflow thread where I was doing an investigation with @curveball helping me as well.
https://stackoverflow.com/questions/45893729/gulp-4-0-gulp-remember-or-gulp-cache-prevent-sass-to-compile-properly-incremen/45894977#45894977

and here's the final gist I cameup with:
https://gist.github.com/MkBeeCtrl/5a6a0900dba1c5d42dc7b6da211b3e95

It's not strictly made for Joints as this is not a wordpress project that I currently work with, but the folder structre is almost identical, so incorporating this into your code won't be difficult.

To make it work properly Gulp 4.0 should be installed

**Comment by JeremyEnglert** [comment]
@MkBeeCtrl - HUGE thanks for this and my apologies for the slow response. We reworked the Gulpfile quite a bit in the new 5.0 release, however, it does still feel a bit slow at times. I'm definitely going to be incorporating the above information in a release in the coming weeks.

**Comment by JeremyEnglert** [comment]
@MkBeeCtrl - is there a reason you used this method instead of Gulp 4's incremental builds?

https://fettblog.eu/gulp-4-incremental-builds/

**Comment by MkBeeCtrl** [comment]
Hey @JeremyEnglert incremental build were my point of entrance. My final version is an outcome of manual testing with adding and disabling stuff. If I recall correctly I had some issues with gulp not recompiling sources properly when I used last run. I would love to give you a more detaild description but in order to do so I need to check it once again. Give me about 2 days, I should be able to retrace my previous path.

**Comment by JeremyEnglert** [comment]
Closing out this issue. Many of these are being utilized in the next version of JWP. Thanks!
