### ISSUE TITLE
Source and destination images directories are the same, causing bug

### ISSUE THREAD

**Issue by Flimm** [JeremyEnglert/JointsWP#276]
I'm looking at the 5.0 branch of the code. Within `gulpfile.js`, there is this bug:

https://github.com/JeremyEnglert/JointsWP/blob/6307ef7628575b10f71045ea66198dcb0a0dbbb4/gulpfile.js#L139

```js
// Optimize images, move into assets directory
gulp.task('images', function() {
	return gulp.src(SOURCE.images)
		.pipe(plugin.newer(ASSETS.images))
		.pipe(plugin.imagemin())
		.pipe(gulp.dest(ASSETS.images))
});
```

Because `SOURCE.images` is `"assets/images/**/*"` and `ASSETS.images` is `"assets/images/"`, the source directory and the output directory are the same.

Because of this, `plugin.newer` is filtering out all files, since a file can never be newer than itself, and as a result, no images get optimised.

**Comment by JeremyEnglert** [comment]
Nice catch.

I'm thinking of removing the images function from the "watch" task and having it simply be a task that is available to run. Which means the `.pipe(plugin.newer(ASSETS.images))` line would probably just be removed.

Gotta think about this a bit.

**Comment by JeremyEnglert** [comment]
Newer has been removed from the gulpfile.
