### ISSUE TITLE
Renamed CSS-Files in Foundation 6.4.2

### ISSUE THREAD

**Issue by JanikWeb** [JeremyEnglert/JointsWP#278]
Foundation removed the file foundation-flex.css and now uses Flexbox by default.
So the option to chose a grid under functions/enqeue-scripts.php should be removed and the standart foundation.min.css should be upgraded to the newest Version.

**Comment by JeremyEnglert** [comment]
JWP 5 will be used for Foundation 6.4. Check out the branch here: https://github.com/JeremyEnglert/JointsWP/tree/5.0

This will become the official branch this week.
