### ISSUE TITLE
gulp-sass update error

### ISSUE THREAD

**Issue by jackfearing** [JeremyEnglert/JointsWP#279]
Is anyone else getting an error when trying to update gulp-sass? I was able to update the rest of the gulp plugins however gulp-sass is throwing an error even if I was SUDO. See image.
![screen shot 2017-09-16 at 8 39 59 am](https://user-images.githubusercontent.com/6834687/30513600-fc7dbc6c-9aba-11e7-8588-72967d19f2b7.png)

**Comment by JeremyEnglert** [comment]
Can you try running: `rm -rf node_modules && npm install`

**Comment by jackfearing** [comment]
Hi Jeremy, I ran the code above and received this: 
![screen shot 2017-09-19 at 8 46 53 am](https://user-images.githubusercontent.com/6834687/30601569-2c3f0498-9d17-11e7-8caa-51e603dc5111.png)

**Comment by jackfearing** [comment]
Hi Jeremy, just wanted to follow-up and find out if you had any additional suggestions based on the new error above.

**Comment by garrett-eclipse** [comment]
Hi @jackfearing 

Looking at your latest log I'm seeing two issues,
- The first is ~/.npm/_logs/2017-09-14T22_52_46_4572-debug.log permissions issue, check if that file exists and share. As well as remove. May be permissions on the .npm folder or _logs folder so check them as well
- Cannot find module 'babel-core' seems like with a gulp-babel update to 7.0 there requires a peer-dependency on babel-core as it was previously a dependency;
https://github.com/babel/gulp-babel/issues/124
Try - npm install --save-dev babel-core, if that works let me know and it should be added as a devDependency in package.json

Hope that helps,
Cheers

**Comment by jackfearing** [comment]
Thanks Garrett -- looks like it was indeed an issue with the permissions file. Once changed the permissions in the .config folder, it removed the error however when I tried to run npm install --save-dev to update the plugins the plugin versions stayed the same. I ended up installing NPM Check Updates which did the trick. https://www.npmjs.com/package/npm-check-updates

In your option is this the best way to update gulp plugins?

**Comment by garrett-eclipse** [comment]
Nice, glad to hear.

Sadly I don't have an opinion on that, I don't get to go back to projects often and update usually am working on brand new so have clean installs. But found this that might be helpful and they also suggested the npm-check-updates you mentioned;
https://stackoverflow.com/a/27026744

Hope that helps,
Cheers
