### ISSUE TITLE
Off-Canvas menu jump due to _settings.scss update

### ISSUE THREAD

**Issue by jackfearing** [JeremyEnglert/JointsWP#283]
Just for reference incase anybody else runs into this issue. I just did an update to Foundation 6.4.3 and it looks like they updated both the '$offcanvas-sizes' and '$offcanvas-vertical-sizes' variables in the _settings.scss file which was causing the off-canvas menu to jump. If you open the _settings file and scroll to the **//25. Off-canvas** section you'll need to make the following updates for the menu to function as is it before (at least in my case).

`// 25. Off-canvas
// --------------`
**Old:**
`$offcanvas-sizes: 250px;
$offcanvas-vertical-sizes: 250px;`

**New:**
`$offcanvas-sizes: (
  small: 250px,
);
$offcanvas-vertical-sizes: (
  small: 250px,
);`

**Comment by JeremyEnglert** [comment]
The newest version of JWP now includes the correct settings file - thanks!
