### ISSUE TITLE
Issue compiling SASS and watching for changes with Gulp

### ISSUE THREAD

**Issue by ash-w2** [JeremyEnglert/JointsWP#284]
Hi,

I'm just getting started with JointsWP and have installed the SASS version via Gulp. I have created my own `_test.scss` file, included this file in `style.scss` with `@import "test";` and gave a newly created div in `footer.php` a custom class with some simple styling.

All fine, except I'm not seeing these changes take effect? I am running `gulp watch` successfully but not seeing changes. Am I missing something? 

Gulp is watching changes but nothing changes when i refresh the browser. This is true even for the `_settings.scss file`. Any help appreciated

Thanks

**Comment by ashussen** [comment]
Have you try `gulp browsersync`? It is watching and refreshing the page automatically.

**Comment by JeremyEnglert** [comment]
I'm guessing you're seeing the cached CSS file. Check out the CSS file that is being called. Are the changes showing there?

**Comment by mlangone** [comment]
Did you gulp styles after you created the _test.scss file then gulp watch? I ran into that the first time I did a gulp sass install.

**Comment by ash-w2** [comment]
Thanks for all your quick responses and pushing me in the right direction. Turns out I needed to set the URL of my local site for browserSync in the gulpfile to watch for changes:

    browserSync.init(files, {
	    // Replace with URL of your local site
        proxy: "**http://your-local-site-url-here.dev/**",
    });

Here it is if anyone else needs it. Cheers

**Comment by JeremyEnglert** [comment]
Nice catch! Closing this out.
