### ISSUE TITLE
Any update for the new xy grid classes

### ISSUE THREAD

**Issue by mlangone** [JeremyEnglert/JointsWP#285]
Will there be any new instructions for updating to the new xy grid classes from foundation?

**Comment by JeremyEnglert** [comment]
I'd highly reccomend against updating any current projects. But JWP 5 uses the new XY classes. This will become the main version soon. 

https://github.com/JeremyEnglert/JointsWP/tree/5.0

**Comment by hazephase** [comment]
ok, Maybe it's better to put it in the readme file, that the  XY is in the JWP 5 branch. I had a problem with I tried to use XY classes on the master branch.

**Comment by JeremyEnglert** [comment]
JWP 5 will become the master version tonight. :)
