### ISSUE TITLE
Issue with compiling assets/style.css

### ISSUE THREAD

**Issue by maryabass** [JeremyEnglert/JointsWP#286]
Hello everybody, I am new here and I hope I am in the right place. I found JointsWP and I can finally build my Wordpress theme - the only problem I am getting is that when I try to edit the stylesheet (assets/style.css) all the edits I make don't show up.

Note: I am using the CSS version of the project. No Sass. 

Thank you in advance

**Comment by JeremyEnglert** [comment]
Do you have a link I can check out?
