### ISSUE TITLE
Translation of custom taxonomie not working 

### ISSUE THREAD

**Issue by navarts-design** [JeremyEnglert/JointsWP#288]
Hy there,
im very happy with your theme. All working fine for me excapt the tranlation of custom taxonomie labels. Did one of you have the same problem?

rest of translation ist working fine! 

if you need more information about my settings just give me a hint!

**Comment by garrett-eclipse** [comment]
Hi @navarts-design 

You'll want to provide your custom taxonomy code as a file.
Have you modified it specifically the labels?

If you customize or create new labels you'll need to update your translation files to encompass them.
You can use something like poedit for that. - https://poedit.net/

Most likely you've customized the text in your CPT implementation and will need to make sure they're still translatable `__('Custom Types', 'jointswp')` through the jointswp locale.

Now however if you've customized the locale you'll need to generate new translation files associated with the new locale.
This might help - https://www.hostinger.com/tutorials/wordpress/how-to-translate-wordpress-theme-using-poedit

Cheers
