### ISSUE TITLE
Pagination in my custom template page doesn't works (page-actualites.php)

### ISSUE THREAD

**Issue by wyde22** [JeremyEnglert/JointsWP#289]
Hi i have got a template page for my project (page-actualites.php). In this page i have got a lot of posts. I want to use the page-navi function of this starter theme but it doesn't works

My loop is here : 

`<?php
    $args = array (
        'posts_per_page'	=> 100
    );
    $queryActus = new WP_Query($args);

    if ($queryActus->have_posts()) : while ($queryActus->have_posts()) : $queryActus->the_post();

        //To see additional archive styles, visit the /parts directory
        get_template_part( 'parts/loop', 'archive-home-actus' );

    endwhile;
    endif;
    wp_reset_query();
    ?>`

and after this code i'm pasting the function page navi

`<?php joints_page_navi(); ?>`

For the pagination i'm using the new function of jointsWP version 5 

`global $wp_query;
    $big = 999999999; // This needs to be an unlikely integer
    // For more options and info view the docs for paginate_links()
    // http://codex.wordpress.org/Function_Reference/paginate_links
    $paginate_links = paginate_links( array(
        'base' => str_replace( $big, '%#%', html_entity_decode( get_pagenum_link( $big ) ) ),
        'current' => max( 1, get_query_var( 'paged' ) ),
        'total' => $wp_query->max_num_pages,
        'mid_size' => 5,
        'prev_next' => true,
        'prev_text' => __( '&laquo;', 'jointswp' ),
        'next_text' => __( '&raquo;', 'jointswp' ),
        'type' => 'list',
    ) );
    $paginate_links = str_replace( "<ul class='page-numbers'>", "<ul class='pagination'>", $paginate_links );
    $paginate_links = str_replace( '<li><span class="page-numbers dots">', "<li><a href='#'>", $paginate_links );
    $paginate_links = str_replace( "<li><span class='page-numbers current'>", "<li class='current'>", $paginate_links );
    $paginate_links = str_replace( '</span>', '</a>', $paginate_links );
    $paginate_links = str_replace( "<li><a href='#'>&hellip;</a></li>", "<li><span class='dots'>&hellip;</span></li>", $paginate_links );
    $paginate_links = preg_replace( '/\s*page-numbers/', '', $paginate_links );
    // Display the pagination if more than one page is found.
    if ( $paginate_links ) {
        echo '<div class="page-navigation">';
        echo $paginate_links;
        echo '</div>';
    }`

This function is activate in my functions.php of theme. I don't understand why my code doesn't works. Have you got an idea :)

Thanks so lot

**Comment by dfragac** [comment]
There is no pagination y your wp_query arguments... you need it to paginate. Check it out:
 [https://codex.wordpress.org/Pagination](https://codex.wordpress.org/Pagination)

**Comment by wyde22** [comment]
ok dfragac, thanks for this codex page

**Comment by mlangone** [comment]
<?php joints_page_navi(); ?> needs to be in between endwhile and else:

				<?php endwhile; ?>	

					<?php joints_page_navi(); ?>
					
				<?php else : ?>

**Comment by JeremyEnglert** [comment]
Looks like the above is the correct way to handle this. Thanks everyone.
