### ISSUE TITLE
Post Content Problem with Span and P elements

### ISSUE THREAD

**Issue by tonga73** [JeremyEnglert/JointsWP#292]
Hi! I'm pretty new at this, but thing is.. I'm working on a project for WordPress, and I'm having a problem that can't understand why.

I don't know if I'm able to explain the problem, but will try.

When you write a post and make it public, if you add "spaces" between lines, the whole thing goes wrong and wordpress does a `<p><span class="someclass">Whatever</span></p>` to every line.

It does not happens if you just paste the text. I did all the work with Lorem generator and it didn't happen. In fact, once I saw the bug, tried pasting again 15 lines of Lorem and worked perfectly. It gets responsive and all the magics. 
But if I go and edit some, do some spaces, some tabs, or whatever, it does infinites columns as if where a grid or something the post-content section.

Sorry if my English gets confusing and I wish you can help me with this because it's getting hard to find the problem by myself.

By the way, thanks a lot for all the work!! Hope I can help/collaborate some day.

Best wishes!

**Comment by garrett-eclipse** [comment]
Hi @tonga73 this repo is specifically for the JointsWP theme framework and not WordPress itself. To open a topic with WordPress please use their forums;
https://wordpress.org/support/

You'll get a more prompt reply from there.

All the best

**Comment by tonga73** [comment]
Sorry! Didn't know. Already solved it. Accidentally added a "flex" class to the post-container and it was messing the whole thing.

Again thanks for all!! :D

**Comment by garrett-eclipse** [comment]
No worries @tonga73 thanks for the update. 
Can you wrap up by closing the ticket.
Appreciated
