### ISSUE TITLE
JointsWP - 5.0 - Change Global Font

### ISSUE THREAD

**Issue by mlangone** [JeremyEnglert/JointsWP#293]
How would I go about changing the global font from 16 to 18px. Would this mess up the responsiveness of the theme?

Sass install.

Thanks!

**Comment by garrett-eclipse** [comment]
Hi @mlangone You'll find this in assets/styles/scss/_settings.scss;
$global-font-size: 100%;

Just switch that to 18px from 100%

**Comment by mlangone** [comment]
Thank you that works
