### ISSUE TITLE
Set vertical align middle with xy grid

### ISSUE THREAD

**Issue by mlangone** [JeremyEnglert/JointsWP#294]
I am looking for some help on this. I need to vertically middle some text. I have tried using the examples from here: https://foundation.zurb.com/sites/docs/flexbox-utilities.html and no matter what I do i cannot get the text to be align-middle. Does something else need to be enabled, fresh install of V.5

Thanks!

**Comment by garrett-eclipse** [comment]
Hi @mlangone how are you going about this?

Is this on an XY or Flexbox Grid? If not you can't use the document you provided.
If you are using that the .align-middle class only works on parent elements, for child elements you need the .align-self-middle class.

Now if this isn't associated with the XY/Flexbox Grid then you'll have to create your own .vertical-center class. Foundation provides a mixin for it so you can just create your class form the mixing if you're using SASS;
.vertical-center {
    @include vertical-center;
}
Reference - https://foundation.zurb.com/sites/docs/sass-mixins.html

or if you're just using CSS;
.vertical-center {
  position: relative;
  top: 50%;
  -webkit-transform: translateY(-50%);
  -moz-transform: translateY(-50%);
  -ms-transform: translateY(-50%);
  -o-transform: translateY(-50%);
  transform: translateY(-50%); 
}

Then place the vertical-center class on your element, this works outside of foundation and the grid.

Hope that helps.
Cheers

**Comment by mlangone** [comment]
I am using the sass version 5 using the xy grid. @include foundation-xy-grid-classes; is enabled in my style.scss file. I add the class align-self-middle to a div and the css for that class does not even register in dev tools. I searched the directory for that class and it appears in prototype and foundation min. 

I searched my style.css file after running npm run build and no luck. 

So that class css is not even being compiled to my style.css file.  which leads me to believe there may be either something not enabled, or disabled. Do I need to uncomment foundation-flex-classes

OR it was not included in this version of JointsWP or I am overlooking something small.

TY

**Comment by garrett-eclipse** [comment]
Interesting, I haven't made the switch to JointsWP 5 so someone else might have a better answer. But from inspecting code it looks like the align-self-middle class comes from the foundation-prototype-classes so you'll need to do a '@include foundation-prototype-classes;' to get it. 
If that's the case I'd flag this as a bug on Foundation itself as the foundation-sites package comes from them when you do an npm install on JointsWP.
You can do that here - https://github.com/zurb/foundation-sites

Also if it's the case that prototypeclasses should be included to get those classes than @JeremyEnglert can you add a line to the settings for '@include foundation-prototype-classes;'

Cheers

**Comment by mlangone** [comment]
Thanks,

**Comment by mlangone** [comment]
Hi all update on this.  I wsa running into several other issues with things like source ordering and found that to get the flex classes to compile I needed to @include foundation-flex-classes; in the styles.scss file basically uncomment line 36ish. Thanks for all the help and hopefully this may help some other people.

**Comment by garrett-eclipse** [comment]
Thanks @mlangone for the update. I was curious so looked into foundation's current styles.scss here;
https://github.com/zurb/foundation-sites/blob/develop/scss/foundation.scss

What I've discovered is they expect foundation-flex-classes to be included if you're using either flex-grid or xy-grid. And since JointsWP is currently default to xy-grid flex-classes should be included (uncommented) going to push a mini-PR.
