### ISSUE TITLE
offCanvas sidebar

### ISSUE THREAD

**Issue by dimbak** [JeremyEnglert/JointsWP#299]
Hi, i am trying to find how this sidebar is used or can be used, can someone help / explain ?

Thanks

**Comment by garrett-eclipse** [comment]
Hope this helps - https://foundation.zurb.com/sites/docs/off-canvas.html

**Comment by dimbak** [comment]
Hi, i must apologize for the not explaining my question.I am referring to the wp-admin/widgets/Offcanvas sidebar, or the registration of the sidebar in /assets/functions/sidebar.php 

how can i use this sidebar and see it on the front end.I am sorry if i misunderstood your reply

Thank you

**Comment by garrett-eclipse** [comment]
Thanks for the clarification. I'm surprised it's not currently implemented btw.

Anyway, if you follow the example of sidebar.php you can implement into your content-offcanvas.php or anywhere else. Something like this (except replace 'sidebar1' with 'offcanvas';
```
	<?php if ( is_active_sidebar( 'sidebar1' ) ) : ?>

		<?php dynamic_sidebar( 'sidebar1' ); ?>

	<?php else : ?>

	<!-- This content shows up if there are no widgets defined in the backend. -->
						
	<div class="alert help">
		<p><?php _e( 'Please activate some Widgets.', 'jointswp' );  ?></p>
	</div>

	<?php endif; ?>
```

I hope that helps.

**Comment by dimbak** [comment]
Yes, i thought i was missing something :) thank you Garrett
