### ISSUE TITLE
JointsWP 5 CSS version

### ISSUE THREAD

**Issue by vibrantj** [JeremyEnglert/JointsWP#305]
Hello Jeremy,

Do you plan on creating a CSS only version of JointsWP 5?

Thanks, John

**Comment by dancrowe** [comment]
second this question, looking for the updated CSS version with the new XY grid pages and templates. 

Great work on the theme in general.

Thanks
-Dan

**Comment by JeremyEnglert** [comment]
This has been updated on the CSS repo.
