### ISSUE TITLE
Restructure Sidebar setup to make it easy to disable

### ISSUE THREAD

**Issue by garrett-eclipse** [JeremyEnglert/JointsWP#307]
Currently the sidebar.php file contains the joints_register_sidebars which is registered in the cleanup.php function joints_start. So to disable sidebars you not only have to comment out the include for sidebar.php but also have to go into cleanup.php and comment out the following;
```
// adding sidebars to Wordpress
add_action( 'widgets_init', 'joints_register_sidebars' );
```

To simplify things we should move this add_action directly into the sidebar.php so it's only one step of commenting out the include in functions.php to disable sidebars.

**Comment by JeremyEnglert** [comment]
Closing this in favor of the PR. Great work!
