### ISSUE TITLE
🍻 Discussion: Improving Gulp Workflow!

### ISSUE THREAD

**Issue by JeremyEnglert** [JeremyEnglert/JointsWP#310]
Many of the open issues have to do with improving the overall Gulp workflow. I'd like to open up that discussion here to see what improvements we can make to the current Gulp setup. 

Please comment below with any ideas, thoughts, concerns or if you want to tackle one of these tasks!

I'm going to create a new branch, `gulp-improvements`, so please push all pull requests (related to this) to that branch.

**Separating Source and Destination (Assets) Directories**

**Updating from JSHint to ESLint**

**Move variables/config to a separate config.js file**
This will clean up the gulpfile.js a lot and make it easier for new users to change the project configuration without needing to understand Gulp completely.

I'll handle this task, as I've already started on it.

**Add better Gulp WPpot Integration**
https://www.npmjs.com/package/gulp-wp-pot

**Comment by garrett-eclipse** [comment]
Thanks @JeremyEnglert can you look at #306 as well, it's proposing a delete function so when you remove source images they remove from assets, it's not quite ready for a PR but could use a Gulp pro's attention.

**Comment by JeremyEnglert** [comment]
@garrett-eclipse - what is the best email to reach you at? garrett@eclipsecreative.ca?

**Comment by garrett-eclipse** [comment]
@JeremyEnglert we've rebranded so you can reach me now at garrett@eclipse3sixty.com

**Comment by JeremyEnglert** [comment]
Sweet! Shot you an email.

**Comment by garrett-eclipse** [comment]
Thanks mate, I'll try and get back to you after hours today.

**Comment by arjendejong12** [comment]
Hey @JeremyEnglert, I've modified your theme to a certain extent for a company I'm working for and as gratitude for creating this theme, I would like to contribute some code, like using webpack to fix Foundation JS issues with Responsive Accordeon Tabs and custom breadcrumbs. Have you created this branch already?

**Comment by jfgodin** [comment]
I would like to suggest adding SVGO to the workflow. Thanks!

**Comment by JeremyEnglert** [comment]
> I would like to contribute some code, like using webpack to fix Foundation JS issues with Responsive Accordeon Tabs and custom breadcrumbs. Have you created this branch already?

That'd be great! And since it's an issue with the current version, you can push to the master branch.

There's actually a ticket about that specific issue: https://github.com/JeremyEnglert/JointsWP/issues/273

**Comment by garrett-eclipse** [comment]
Nice @arjendejong12 that's awesome. For my workflow I fork master, create a branch on my repo and use that to create a PR to the core master branch. Seems to have worked nicely so far.
And do check #273 because it sounds like just switching the order of js and re-running the build script seems to have fixed the JS issues. You'll know better once you've taken a look.

**Comment by JeremyEnglert** [comment]
If we can't get the Foundation project in order soon, it may be time to also think about introducing a new framework or removing the framework completely. This wouldn't be something that would immediately effect the project. 

But the momentum on the Foundation project appears to be quickly fading. :(

**Comment by arjendejong12** [comment]
Yeah the Foundation repo was silent for like three months. Not sure what's happening there right now.

**Comment by arjendejong12** [comment]
I've created a PR (#319) with some changes I've made and found useful for this theme. Please let me know what you think of it!

**Comment by MrSpecific** [comment]
Not sure if anyone else is experiencing this, but I'm having issues with Gulp not updating the timestamps on `style.css` and `scripts.js`, so when I sync files with a remote server, those files aren't updated. I resolved it for my workflow by adding [gulp-touch](https://www.npmjs.com/package/gulp-touch) and using that at the end of `styles` and `scripts`.

Probably not the most ideal solution, I'd definitely be open to other options in a new Gulp workflow.

**Comment by garrett-eclipse** [comment]
Thanks @arjendejong12 I'll leave PR and code reviews to @JeremyEnglert as he has the keys

**Comment by garrett-eclipse** [comment]
@jfgodin can you open a issue with your feature request so it doesn't get lost in the discussion thread. Thanks

**Comment by garrett-eclipse** [comment]
Thanks for the heads up @MrSpecific can you open a ticket and we'll look into this.
