### ISSUE TITLE
NPM Error - Missing Script : Watch

### ISSUE THREAD

**Issue by johnw6761** [JeremyEnglert/JointsWP#313]
I am getting an error when running npm run watch. This was working fine but now not.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose stack Error: missing script: watch
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:456:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
5 verbose cwd C:\Users\John\repos\voltamp
6 error Windows_NT 10.0.16299
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
8 error node v6.11.0
9 error npm  v3.10.10
10 error missing script: watch
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

  
![npm](https://user-images.githubusercontent.com/9976925/34725345-8520b4ba-f548-11e7-9fbc-fdd11612c2d3.PNG)

**Comment by garrett-eclipse** [comment]
Check that you have the latest [package.json](https://github.com/JeremyEnglert/JointsWP/blob/master/package.json) file on your dev environment. If something is missing, please add it and run npm install

**Comment by johnw6761** [comment]
No, It doesnt look like I have the latest one. I am not sure why that would be and why it suddenly stopped working?

**Comment by johnw6761** [comment]
Tried this and now has a different error, do I also need to update nodejs?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle jointswp-sass@5.0.0~prewatch: jointswp-sass@5.0.0
6 silly lifecycle jointswp-sass@5.0.0~prewatch: no script for prewatch, continuing
7 info lifecycle jointswp-sass@5.0.0~watch: jointswp-sass@5.0.0
8 verbose lifecycle jointswp-sass@5.0.0~watch: unsafe-perm in lifecycle true
9 verbose lifecycle jointswp-sass@5.0.0~watch: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\John\repos\voltamp\node_modules\.bin;C:\Users\John\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Common Files\Roxio Shared\10.0\DLLShared\;C:\Program Files (x86)\Common Files\Autodesk Shared\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Users\John\AppData\Local\Microsoft\WindowsApps;C:\Users\John\AppData\Roaming\npm;
10 verbose lifecycle jointswp-sass@5.0.0~watch: CWD: C:\Users\John\repos\voltamp
11 silly lifecycle jointswp-sass@5.0.0~watch: Args: [ '/d /s /c', 'gulp watch' ]
12 silly lifecycle jointswp-sass@5.0.0~watch: Returned: code: 1  signal: null
13 info lifecycle jointswp-sass@5.0.0~watch: Failed to exec watch script
14 verbose stack Error: jointswp-sass@5.0.0 watch: `gulp watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid jointswp-sass@5.0.0
16 verbose cwd C:\Users\John\repos\voltamp
17 error Windows_NT 10.0.16299
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error jointswp-sass@5.0.0 watch: `gulp watch`
22 error Exit status 1
23 error Failed at the jointswp-sass@5.0.0 watch script 'gulp watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the jointswp-sass package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs jointswp-sass
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls jointswp-sass
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

![npm](https://user-images.githubusercontent.com/9976925/34735406-3e857bde-f567-11e7-98ff-d15214f54fd2.PNG)

**Comment by garrett-eclipse** [comment]
Hmm, I feel your node modules may be convoluted.
Try `rm -rf node_modules`, you made need to do that as sudo
Then run `npm install`
And finally you can try the `gulp watch` command again.

**Comment by johnw6761** [comment]
I tried rm -rf node_modules and npm install and got the following

![npm](https://user-images.githubusercontent.com/9976925/34772539-29611f12-f600-11e7-9a2e-8de014005c42.PNG)

**Comment by garrett-eclipse** [comment]
Hi @johnw6761 the first line of `rm -rf node_modules` shouldn't be run with npm as the screen shows, should be a command on it's own. Following that the other error you're getting on `npm run build` indicates that Gulp isn't installed on your system, to do that run `npm install --global gulp-cli` before running your `npm run build` command. Hope that helps

**Comment by johnw6761** [comment]
I get an error on rm -rf node_modules too :( 
I don't understand why everything has suddenly stopped working, it all seemed fine before.

![image](https://user-images.githubusercontent.com/9976925/34787349-dddb7ce8-f62e-11e7-90da-493a54b09d31.png)

**Comment by garrett-eclipse** [comment]
Ooo sorry my bad, you're on Windows which doesn't support the rm or mv commands as they're linux.
kk instead just delete the node_modules folder manually from your file browser.
And then go into doing the `npm install --global gulp-cli`, then `npm install` and finally the `npm run build`

**Comment by JeremyEnglert** [comment]
You shouldn't need to install Gulp globally. That's why we use `npm run TASK`.

But I think your best bet would be to remove your `npm_modules` and rerun `npm install`.

**Comment by johnw6761** [comment]
Got this after deleting the node modules folder and running npm install

![image](https://user-images.githubusercontent.com/9976925/34828264-df599400-f6d4-11e7-97e2-bcb61ec0a853.png)

**Comment by garrett-eclipse** [comment]
@JeremyEnglert I'm not so sure Gulp isn't needed there as the error shows gulp-bower is missing. Or maybe gulp-bower is not needed specifically as a dependency in package.json

@johnw6761 Can you run an `npm update` followed by `npm install gulp-bower --save-dev` and then run `npm install` again to kick off the build again. This should install the gulp-bower module for you.

**Comment by garrett-eclipse** [comment]
*And if that doesn't work try installing gulp globally as a test - `npm install --global gulp-cli`

**Comment by johnw6761** [comment]
![image](https://user-images.githubusercontent.com/9976925/34840804-093f0ee8-f6fe-11e7-8eac-8ae37fd64871.png)

![image](https://user-images.githubusercontent.com/9976925/34840817-13ca4c7e-f6fe-11e7-916a-bc4e1f454ccc.png)

**Comment by garrett-eclipse** [comment]
Hi @johnw6761 I'm sorry I was looking at this with JointsWP 5.0 in mind which doesn't hold any gulp start commands but looking back at JointsWP 4.0 the start command was part of the default task;
https://github.com/JeremyEnglert/JointsWP/blob/4.0/gulpfile.js#L142

This also explains why your package.json was different. If you're sticking with JWP 4.0 then you'll want to revert the package.json, I'm sorry, and clear your node_modules and run npm install again.

This should bring us all the way back to your original issue of npm run watch isn't a command because in JWP 4.0 it wasn't instead you'd run `gulp watch`, but you may need to globally install gulp if it says gulp doesn't exist. 
`npm install --global gulp-cli`

So sorry I should have asked which version of JWP you were using to start with.

If we're still stuck, can you package your whole theme for me to look at and understand what you have setup.

Thanks

**Comment by johnw6761** [comment]
Yaaaay that worked!! I think the confusion was I hadnt worked with joints for a while so went back to the site to check the commands but was obviously checking the documentation for the wrong version.

**Comment by garrett-eclipse** [comment]
Niice, glad that worked sorry for the run around.

And you're definitely not alone... my primary theme project is still on JWP 4 so when everyone is talking able `npm run` commands I still use `gulp` version.
If you ever need to go back to JWP4 source, etc it's tagged on Github here;
https://github.com/JeremyEnglert/JointsWP/tree/4.0

Sadly I wasn't able to find 4.0 documentation on jointswp.com, @JeremyEnglert is any of the old documentation still available for historic reference? If you have it and don't want to put on jointswp.com maybe we can just post old docs to wiki for posterity.

**Comment by JeremyEnglert** [comment]
I did a terrible job at versioning docs. So I don't think those are available anymore. :(

Something I'll keep in mind as we prepare for V6.

**Comment by garrett-eclipse** [comment]
No worries @JeremyEnglert thanks for the follow-up.
