### ISSUE TITLE
Drilldown offcanvas menu

### ISSUE THREAD

**Issue by mlangone** [JeremyEnglert/JointsWP#316]
I have offcanvas menu on the left, when drilling down it opens from the right any way to switch this so it stays consistent
![ezgif-4-3eabe2e709](https://user-images.githubusercontent.com/4027703/34908260-05e70f5a-f84a-11e7-829e-a3e964d7d88d.gif)
?

**Comment by garrett-eclipse** [comment]
Hey @mlangone I wasn't able to find any documentation on this through foundation;
https://foundation.zurb.com/sites/docs/drilldown-menu.html

As this is Foundation specific you may have better luck on Zurbs forums or slack. It animation direction may not currently be supported and may require a feature request or custom code.

**Comment by JeremyEnglert** [comment]
I agree with @garrett-eclipse. It looks like this isn't something "built in" - so you'll have to come up with something custom or put in a feature request for Foundation (but that backlog is pretty intense at the moment).

**Comment by mlangone** [comment]
Setting scroll true in off canvas topbar did the trick
