### ISSUE TITLE
Display console.log

### ISSUE THREAD

**Issue by mlangone** [JeremyEnglert/JointsWP#318]
Sorry if this is a basic question but how and where do i put this to get a console.log to show?

`    jQuery(window).on('changed.zf.mediaquery', function(event, newSize, oldSize){
        // Inital state small -> medium
        console.log(newSize); // should return medium
        console.log(oldSize); // should return small
    });`

I tried in wp-foundation.js and gulp compiled it. But no luck.

ML

**Comment by garrett-eclipse** [comment]
Hey @mlangone from your code sample it appears the console.log is commented out. you put it in the right place but try with this code;
```
jQuery(window).on('changed.zf.mediaquery', function(event, newSize, oldSize){
    console.log(newSize); 
    console.log(oldSize);
});
```

Hope that works, Cheers

**Comment by JeremyEnglert** [comment]
@garrett-eclipse's answer looks correct! 

Also, you may have better luck with this particular question in the Foundation repo, as it looks to be Foundation specific.
