### ISSUE TITLE
Pagination doesn't work with Foundation tabs

### ISSUE THREAD

**Issue by cordial** [JeremyEnglert/JointsWP#320]
hey,

Firstly, great theme, used it many times, love the workflow and tools/framework included. 

I have some foundation tabs working where each tab displays a custom taxonomy (news category) of a custom post type (in my case news). However, when i tried to add pagination to the tabs, it doesnt work. The tab links are formatted as such -

- http://sitename/news/#tab-name

I added the jointsWP pagination code and I got this for my pagination links (as I was half expecting / fearing)   

- http://sitename/news/page/2 

I understand that this is all driven from the server side wheras the foundation tab links are just client side, so obviously this isn't going to find any data to link up with the tab URL and currently displaying a 404 (as you would expect). 

I then tried fiddling with the joints_page_nav() function to try and add in the tab part into the URL, but couldn't get it to be added into the correct part of the URL. I then realised I didn't actually know where I should put, or whether any URL structure would have the desired effect. However, either of these two seem vaguely plausible -  

- http://sitename/news/page/2/#tab-name (although this makes me think the server is now just returning page 2 of news without the tab querying)
or
- http://sitename/news/#tab-name/page/2/ (this makes me think the server is going to say, err what's this tab name nonsense in the middle)

It's possible I am overreaching what foundation tabs can do i.e. using tabs in this situation isn't correct, but it seems a fairly plausible idea that you might want to do custom taxonomy queries that are shown over tabs that may then require pagination. 

Is this something you'd expect to work or could work? Anyone tried it? Any 

cheers
David

p.s. I currently have deep linking set to True, not sure if this is information that would pertain to finding a solution or not. 
p.p.s I've also posted this to the foundation forums, as I'm not entirely sure this counts as a JointsWP issue. If you think not, feel free to tell me to move along :)

**Comment by garrett-eclipse** [comment]
Hi @cordial 
You're right this isn't a standard feature of JointsWP, nor really of Foundation. You'll have to setup some custom ajax pagination for your tabs.
I can point you in some direction here but am really just Googling...
https://www.bobz.co/filter-wordpress-posts-by-custom-taxonomy-term-with-ajax-and-pagination/
https://github.com/malinky/malinky-ajax-pagination

Hope you can sort out the customization you seek.
Cheers

**Comment by JeremyEnglert** [comment]
Garret is correct.

You could also look into using the WP API to make this work.
