### ISSUE TITLE
joints_footer_links shouldn't use menu attribute only theme_location

### ISSUE THREAD

**Issue by garrett-eclipse** [JeremyEnglert/JointsWP#321]
In the menu.php there's the joints_footer_links function which calls wp_nav_menu with the menu attribute along with the theme_location. It's best to stick with theme_location as the menu attribute indicates it'll use a specific menu by name which if you don't setup a menu with that exact name won't function.

**Comment by JeremyEnglert** [comment]
Fixed in https://github.com/JeremyEnglert/JointsWP/pull/322.
