### ISSUE TITLE
Change menu link size

### ISSUE THREAD

**Issue by mlangone** [JeremyEnglert/JointsWP#323]
I am getting some jumps in the menu, I believe it is due to **my menu item font size being smaller** than the default, not the js  fouc issue. I was able to adjust the $global-menu-padding: to what i need. 

My question is where can I adjust the the .dropdown.menu a - Im using top-bar accordion menu. I believe if I set this early and not at the end of the style loading the jump will be gone.

![ezgif-3-a199dd72a2](https://user-images.githubusercontent.com/4027703/35404836-7ea7bcc0-01c1-11e8-879a-2fa0c4d7fc73.gif)

**Comment by garrett-eclipse** [comment]
Hey @mlangone 
That's more of a foundation issue than Joints but I'll try to point you in the right direction.

In the _settings.scss;
https://github.com/JeremyEnglert/JointsWP/blob/master/assets/styles/scss/_settings.scss
You'll find settings for numerous items. I'm not too versed in them but if you go to Foundation documentation for specific items like the Menu at the bottom you'll fine a SASS reference.

Specific settings for...
Drilldown - https://github.com/JeremyEnglert/JointsWP/blob/master/assets/styles/scss/_settings.scss#L357
Dropdown - https://github.com/JeremyEnglert/JointsWP/blob/master/assets/styles/scss/_settings.scss#L370
Dropdown Menu - https://github.com/JeremyEnglert/JointsWP/blob/master/assets/styles/scss/_settings.scss#L385
Menu - https://github.com/JeremyEnglert/JointsWP/blob/master/assets/styles/scss/_settings.scss#L468
Titlebar - https://github.com/JeremyEnglert/JointsWP/blob/master/assets/styles/scss/_settings.scss#L819
Topbar - https://github.com/JeremyEnglert/JointsWP/blob/master/assets/styles/scss/_settings.scss#L845

You can try searching the _settings.scss file for size and see if any make sense.


OR what I'd probably do is just put the css I want into _global.scss as it gets compiled into the style.css so would load around the same time as if you had changed settings.

Hope that helps,
Cheers

**Comment by JeremyEnglert** [comment]
I have a feeling your targeting the JS generated classes with your CSS. Which is why it changes after the JS loads.
