### ISSUE TITLE
Visual Editor Styles Not Effecting TinyMCE

### ISSUE THREAD

**Issue by jwindeknecht** [JeremyEnglert/JointsWP#325]
Here are the steps I took to activate these styles, though they don't seem to be taking affect.

1. Uncommented _require_once(get_template_directory().'/functions/editor-styles.php');_ in **functions.php**.
2. I didn't touch anything in **/functions/editor-styles.php**.
3. Added _font-family: sans-serif;_ to the _body#tinymce_ selector in **/assets/styles/scss/_global.scss**.
4. Verified _@import "global";_ was in **/assets/styles/scss/style.scss**.
5. Verified the _font-family_ code had been compiled in **/assets/styles/style.css**.
6. I logged out of Wordpress and logged back in.

When editing a post, the font is still serif. I inspected the element and the styles are not being pulled in, nor is _margin: 20px;_ that came preset within **/assets/styles/scss/_global.scss**.

Let me know if I can provide more information or answer any questions. Thanks!

P.S. Using Wordpress 4.9.4

**Comment by garrett-eclipse** [comment]
Thanks for pointing this out @jwindeknecht 

I forget what version dropped the .min stylesheets but there's no longer a style.min.css only a style.css, except the editor-styles.php references a style.min.css. If you go into the editor-styles.php file and drop the .min portion from the style.css filename that should resolve this and I'll correct in the repo here.

Cheers

**Comment by jwindeknecht** [comment]
Oh wow, I totally overlooked the _.min_. Removed that and it works, thanks!
