### ISSUE TITLE
Added some custom scripts and getting an "'$' is not defined." when compiling.

### ISSUE THREAD

**Issue by jwindeknecht** [JeremyEnglert/JointsWP#330]
I created a new script in *assets/scripts/js/* and upon compiling, I'm getting the mentioned warning.

I can fix most of these by replacing *$* with *jQuery*, but I'm wondering if there isn't a better way to go about this or if I'm missing something. Example below:

    $(document).ready(function () {
      $(".hamburger").click(function () {
        $(this).toggleClass("is-active");
      });
    });

Thanks for your time!

**Comment by garrett-eclipse** [comment]
Hey @jwindeknecht 
This article will hopefully help;
https://digwp.com/2011/09/using-instead-of-jquery-in-wordpress/

If you update your document ready call you won't ahve to modify any calls to $ within it, change to;
jQuery(document).ready(function( $ ) {

Cheers

**Comment by jwindeknecht** [comment]
@garrett-eclipse Perfect! Thanks for the article, that really helped me understand what is happening with these scripts.

**Comment by garrett-eclipse** [comment]
No worries @jwindeknecht
