### ISSUE TITLE
Gulp task processing is far slower than Codekit

### ISSUE THREAD

**Issue by VeVas** [JeremyEnglert/JointsWP#337]
Hi!

I've been a long time JointsWP user, and used CodeKit to handle the processing of css/js. As of the last version it does not detect the files in the scripts-folder, so I installed the theme as described in the docs, with the npm run to do the processing. But this is significantly slower than CodekKit, is this correct?

Processing times with a fresh theme installation:
CodeKit: 2-400ms
npm run styles: 2,61s
npm run scripts: 3,41s
npm run build: 5,95s

Tried removing mapping and prefixes etc. but it still styles takes around 2s.

If anyone can share some experiences that would be great, is these times normal?

**Comment by JeremyEnglert** [comment]
We're working on improving these speeds. The newest version of Gulp allows us to cache un-changed files. 

Also, if you're using `npm run watch`, those times should improve.
