### ISSUE TITLE
Adding NPM module

### ISSUE THREAD

**Issue by meiskv** [JeremyEnglert/JointsWP#339]
I just wanted to ask how can I properly add a javascript library on JointWP using npm install package? Cause right now I'm only adding all the javascript library on the header.php.

Cheers!

**Comment by garrett-eclipse** [comment]
Hi @meiskv, that's a great question.

Once you've npm install'ed your package you'll find it in the node_modules folder, note the path.
Then in the gulpfile.js find the scripts array which is part of the SOURCE const;
https://github.com/JeremyEnglert/JointsWP/blob/master/gulpfile.js#L20

Add a new line to the array with the path to your script, this supports regex as seen with the *.js inclusion;
'assets/scripts/js/**/*.js',

Once it's added in you'll be able to run gulp or npm build depending on your JointsWP version and your scripts will be merged in with foundation, etc.

Let me know if you have any issues, or questions.
Cheers
