### ISSUE TITLE
TypeError, message: "this.rules[t] is undefined" in Script Console

### ISSUE THREAD

**Issue by jwindeknecht** [JeremyEnglert/JointsWP#340]
I keep receiving an error in my Javascript console with the message _"this.rules[t] is undefined"._ It's in _foundation.core.js:358:10_.

Apologies if this is really vague, but I'm not sure how to even approach this. Please let me know if I can any more information. Thank you!

`TypeError`
`columnNumber: 8711`
`fileName: "http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168"`
`lineNumber: 6`
`message: "this.rules[t] is undefined"`
`stack: "value@http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168:6:8711\nvalue@http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168:6:8333\nvalue@http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168:6:8023\nt@http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168:1:9405\ne@http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168:6:7762\nreflow/</<@http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168:1:6636\neach@http://yadayada.com/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:2879\neach@http://yadayada.com/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:844\nreflow/<@http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168:1:6285\neach@http://yadayada.com/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:2879\nreflow@http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168:1:6186\ne@http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168:1:6886\n@http://yadayada.com/wp-content/themes/Joints/assets/scripts/scripts.js?ver=1524518168:9:3352\n"`
`__proto__: Object { stack: "", … }`

**Comment by garrett-eclipse** [comment]
Hi @jwindeknecht this looks to be more of a Foundation issue than JointsWP. You'll be best served over at their support forums here;
https://foundation.zurb.com/get-involved/support.html
Github - https://github.com/zurb/foundation-sites

Make sure to indicate the version of Foundation you're using and provide a copy of your scripts.js. YOu can post those things here as well and I'll take a quick look but most likely you'll get help over at Foundation.

Cheers
