### ISSUE TITLE
Imagemin not minifying images

### ISSUE THREAD

**Issue by RicardoRVM** [JeremyEnglert/JointsWP#342]
First of all, sorry for my bad english.

When I execute build or images commands, the images ar copied from assets/images/src to assets/images, but they are not minifyed. The height is the same. I am new with JointsWo, but I´ve installed the theme as it is, witout no changes, for the moment.

![images](https://user-images.githubusercontent.com/39798736/40966808-c96883aa-68b1-11e8-90d9-ae89b6809940.png)

**Comment by garrett-eclipse** [comment]
Can you share your console output after you run the command so we can see the process. As well those images are already quite small and may not have much to optimize, if you try a larger image say > 200KB is there any minification difference?

**Comment by senlin** [comment]
@RicardoRVM 

> The height is the same.

The dimensions should remain the same, what changes is the file**size**:

<img width="885" alt="imagemin" src="https://user-images.githubusercontent.com/650066/45300825-49a8d500-b507-11e8-968a-08e208667741.png">

**Comment by JeremyEnglert** [comment]
@senlin is correct! The height/width stays the same. The file size is reduced.
