### ISSUE TITLE
Discussion: JointsWP 6 - Framework Options, Zero Config, CLI Tools & More

### ISSUE THREAD

**Issue by JeremyEnglert** [JeremyEnglert/JointsWP#343]
This is meant to open the discussion about the next version of JointsWP. Nothing is set in stone.

## Framework Options - No Framework, Foundation, Bootstrap (maybe more)
With flexbox & CSS grid gaining popularity everyday, there is less need for a CSS framework - especially on small projects. However, there are still an extremely valuable tool for teams and/or large projects. Instead of having separate starter themes for different projects (which means different workflows and configs), the new version of JointsWP will be framework independent. 

The "base" theme will not include a framework at all. But you will _easily_ be able to add frameworks such as Foundation and Bootstrap (and really any framework we want to support). 

```bash
create-wp-theme --name="new-theme" // Creates new theme without a CSS framework
create-wp-theme --name="new-theme" --framework="foundation" // Creates a new theme with Foundation installled
create-wp-theme --name="new-theme" --framework="bootstrap" // Creates a new theme with Bootstrap installed
```

## Theme Setup - Lets Make it Even Easier
If you have Node/NPM installed, you'll be able to download, configure and install the theme in a single command.

```bash
npx create-wp-theme --name="new-theme"
```

This command will also install the necessary dependencies.  Ideally, the "name" argument will also be used to set the theme's text-domain.

We can even expand on this to add niche features that probably do not belong in the base theme, but are used enough to be valuable. For example, we could add WooCommerce support doing the following:

```bash
npx create-wp-theme --name="new-theme" --support="woocommerce"
```

## 100% Accessible 
No ifs, ands or buts. 

## Webpack for JS Compiling
I think Gulp still makes sense for the majority of automated tasks. But we should probably move to Webpack for JS.

**Comment by Warkman** [comment]
Love the idea of no framework though d like the idea of having something like http://refills.bourbon.io/ but that should be a tool I need to get sorted for the box.

**Comment by RexSeven** [comment]
Plans sound good. One question, is node a requirement once you've ran npm run build? If so could this be changed?

**Comment by senlin** [comment]
Sounds great, can you give any indication on when this will become actual?

**Comment by senlin** [comment]
Could have been an idea to leave a comment before closing this?

**Comment by garrett-eclipse** [comment]
That's awesome, I see you've gotten started here - https://github.com/JeremyEnglert/JointsWP/tree/6.0-dev

Sorry I overlooked this post initially. If you need help hit me up.

Also reviewing the move towards a framework-less build system I almost wonder if this is evolving into a new project separate from JointsWP as those who use or are aware of JointsWP have it synonymous with the Foundation framework as the unofficial Foundation theme starter for WordPress. Just thinking by segregating the project this one can continue to evolve aligned with Foundation as existing users expect and the new build system can be completely unfettered from Joints.

Just some initial thoughts, looking forward to the future ;)
