### ISSUE TITLE
Help orbit and tabs not working jointswp 5

### ISSUE THREAD

**Issue by mjcproductions** [JeremyEnglert/JointsWP#344]
I just installed jointswp 5 css version x y grid and anything that uses jquery is not working orbit slider, tabs, etc. How do I get this to work?

**Comment by JeremyEnglert** [comment]
Do you have a link i can check out?

**Comment by garrett-eclipse** [comment]
I'm going to close this for now.

@mjcproductions If you could provide more information such as console logs, screenshots, browser verions, live links or code samples that would assist in us reproducing the issue.

Thank you
