### ISSUE TITLE
Building scripts.

### ISSUE THREAD

**Issue by meiskv** [JeremyEnglert/JointsWP#346]
It may not be related but. I just wanted to know what is the best practice or approach can I take to make the build faster?

Cause right now my javascript codes are too long and I am using browsersync and whenever I save my script it takes me 1 min to build it before I saw the output on the web.

Cheers!

**Comment by JeremyEnglert** [comment]
The next version of JWP will use caching to help reduce compile times. Leaving this open as a reminder.

**Comment by meiskv** [comment]
Thank you @JeremyEnglert !
