### ISSUE TITLE
Bringing in Interchange

### ISSUE THREAD

**Issue by bleuchill** [JeremyEnglert/JointsWP#347]
Hello Jeremy!
I hope this is going to be an easy question.
I would like to include interchange to a WordPress site I'm using JointsWP with. I'm not really sure where or how to go about it. It's not in the style.scss document, and although it's in the node_modules folder, I'm not quite sure whether I should be touching that.
I downloaded the theme using NPM.

**Comment by sgjackman** [comment]
Hey @bleuchill 
Interchange is a part of Foundation, which JointsWP is using as a responsive framework. It's already included in the theme, but you will need to enable it by uncommenting a line in your gulpfile.js file.  

Look fo this line and uncomment it:
`FOUNDATION + '/dist/js/plugins/foundation.interchange.js',`
Then run:
`npm run build`
And interchange will be available in your theme.

**Comment by bleuchill** [comment]
Thanks @sgjackman. I did everything you said and I'm all set!
