### ISSUE TITLE
Archive Grid not working in Firefox 

### ISSUE THREAD

**Issue by johnbsingfield** [JeremyEnglert/JointsWP#349]
Hi,

I installed a brand new Jointswp installation with no modifications and switched to the archive-grid to display my posts. I have made many tests across different machines and I can see the grid system is breaking down in some cases. 

It seems the equalizer is not doing it's job properly and the rows are overlapping. So far I noted that it only happens in Firefox, and hitting the reload button seems to fix the issue on screen...But as soon you navigate inside the site the problem comes back.

Since I'm a beginner, I thought I coded something badly but, using a default install of JointWP, I feel now that it might be an issue with the theme or Foundation itself. 

Let me know if you have any solution to this. Thank you.

**Comment by sgjackman** [comment]
@johnbsingfield I have noticed that equalizer can fail if the height calculations it needs to make are dependent on images with no manually set dimensions. Make sure all of your images have height and width tags.

**Comment by johnbsingfield** [comment]
Thanks @sgjackman . I tried to use predefined width using this and it finally worked:

`<img src="<?php the_post_thumbnail_url( array(1500, 1000) ) ?>">`

**Comment by sgjackman** [comment]
Hey @johnbsingfield , that's great, but are you sure you want your images that size?  I would be more inclined to use the pre-defined wordpress image sizes:

From the codex: https://codex.wordpress.org/Function_Reference/the_post_thumbnail_url

the_post_thumbnail_url( 'thumbnail' );       // Thumbnail (default 150px x 150px max)
the_post_thumbnail_url( 'medium' );          // Medium resolution (default 300px x 300px max)
the_post_thumbnail_url( 'large' );           // Large resolution (default 640px x 640px max)
the_post_thumbnail_url( 'full' );            // Full resolution (original size uploaded)
