### ISSUE TITLE
Vulnerable npm packages

### ISSUE THREAD

**Issue by garrett-eclipse** [JeremyEnglert/JointsWP#355]
While setting up a fresh install I got a `npm audit` alert which I ran and ended up finding a few vulnerable packages.

gulp-jshint;
![screen shot 2018-09-11 at 10 33 32 am](https://user-images.githubusercontent.com/8726005/45378250-c7c1b600-b5b1-11e8-8a7a-0b87c1191595.png)

gulp-imagemin;
![screen shot 2018-09-11 at 10 34 17 am](https://user-images.githubusercontent.com/8726005/45378278-d8722c00-b5b1-11e8-8698-78977671fd44.png)

**Comment by JeremyEnglert** [comment]
Fixing this in JWP 6. 

https://github.com/JeremyEnglert/JointsWP/tree/6.0-dev

**Comment by garrett-eclipse** [comment]
Nice thanks @JeremyEnglert glad to hear you're moving forward with V6. Here to help as needed
