### ISSUE TITLE
Change for v6.5.0-rc.2 foundation-sites

### ISSUE THREAD

**Issue by mjezegou** [JeremyEnglert/JointsWP#356]
I have some problem with safari and foundation (grid and orbit). I try to upgrade foundation-sites in this theme. https://github.com/zurb/foundation-sites/releases

I had to add : 
"glob": "^7.1.3",
"what-input": "^5.1.2",
"glob-stream": "^6.1.0",
in my package.json. Compile is ok !

but the styles.css not include all of foundation css.

Is it possible to upgrade foundation-sites ?

**Comment by JeremyEnglert** [comment]
You should be able to upgrade by running `npm run update-foundation`. However, as 6.5 isn't official, it may still have bugs. (Which is why it hasn't been upgraded in JWP yet).

**Comment by mjezegou** [comment]
Thank you Jeremy.
