### ISSUE TITLE
WP Customizer not working

### ISSUE THREAD

**Issue by mlangone** [JeremyEnglert/JointsWP#358]
Is there a setting or function that needs to be enabled to allow for editing through the Wordpress customize for custom css?

**Comment by garrett-eclipse** [comment]
Hi @mlangone as of WP 4.7 the 'Additional CSS' functionality found in Customizer is enabled by default. 

Nothing in joints is setup to remove or modify that so check your plugins or custom code for anything.

Here's how to remove it so maybe do a search for these functions in your site and see if you have any code removing it.

Closing this as it's not a JointsWP issue, but feel free to ping back and I'll see if I can give you a hand.
