### ISSUE TITLE
Updates to _settings.scss not being reflected on WP site (dev mode)

### ISSUE THREAD

**Issue by jedwards22** [JeremyEnglert/JointsWP#361]
I'm just starting out using JointsWP to build a new site.  I've installed WordPress and the JointsWP theme without any issues, and development is being done locally using MAMP.  

I'm making a simple change to _settings.scss to change the background color of the .top-bar class, however after I save my updates, the changes are reflected in the style.css file but they are not being reflected on my localhost WP site (_localhost:8888/wp_site_name_).  It appears that the styles for .top-bar are still being pulled from the foundation-sites directory under "node-modules".   Screenshots are available below.

Any idea on how to get this fixed so that changes made to _settings.scss are reflected on the WP site preview?

**_settings.scss Change**
![_settings scss change](https://user-images.githubusercontent.com/3277679/46428605-6b663800-c712-11e8-99f6-661e4b86d656.png)

**WP Site Preview**
![wp_site_preview](https://user-images.githubusercontent.com/3277679/46428599-673a1a80-c712-11e8-97c1-ec0fdb49b50c.png)

**Comment by garrett-eclipse** [comment]
Hi @jedwards22 have you recompiled the styles?
`npm run build`
Reference - https://github.com/JeremyEnglert/JointsWP#compile-and-minify-all-theme-assets

You can also run `npm run watch` or `npm run browsersync` for active development.

Hope that helps

**Comment by jedwards22** [comment]
Hi @garrett-eclipse, 
Thanks for the quick reply!  I am using `npm run watch` and this did pick up the change (reflected in style.css).  Do I need to run `npm run build` in addition to `npm run watch`?

**Comment by garrett-eclipse** [comment]
No worries @jedwards22 this might be a browser caching issue if you're using `npm run watch` instead of `npm run browsersync`. So try a hard refresh or clear your cache. Hoping it's just something simple like that. You should be able to tell it's browser cache if the `npm run watch`  is showing the compile and checking your files they're updated properly.

**Comment by jedwards22** [comment]
Thanks @garrett-eclipse.  Looks like that did the trick!  Switched over to using browsersync and we're good to go.
