### ISSUE TITLE
Wrong path in the function load_translations

### ISSUE THREAD

**Issue by benny-ben** [JeremyEnglert/JointsWP#362]
In the `/functions/translation/translation.php` is indicated this wrong path `'/assets/translation'` instead of `'/functions/translation'`

**Comment by garrett-eclipse** [comment]
Thanks @benny-ben

It appears the translation folder was moved from /assets to /functions here;
https://github.com/JeremyEnglert/JointsWP/commit/3b703249a129ee5a994ba23b06ba0115b7979df5#diff-32bb636196f91ed59d7a49190e26b42c

Appreciate the reference fix.
