### ISSUE TITLE
Wrong path in /header.php for the apple-icon-touch.png icon

### ISSUE THREAD

**Issue by benny-ben** [JeremyEnglert/JointsWP#364]
Wrong path to [/assets/images/apple-icon-touch.png](https://github.com/benny-ben/JointsWP/blob/ba97cb29fb4f10bc536b6057cb559b5673ba8373/header.php#L28) because the icon is in [/assets/images/src/](https://github.com/benny-ben/JointsWP/tree/master/assets/images/src)

**Comment by garrett-eclipse** [comment]
Hi @benny-ben 

The source images are found in `/assets/images/src/` but upon compiling them they're duplicated and optimized into `/assets/images/` so the path is correct.

Any of the following commands will run the images script resulting in images being found in the correct location;
`npm run watch`
`npm run browsersync`
`npm run build`
`npm run images`

I appreciate the PR but won't be needed in this case.

**Comment by benny-ben** [comment]
Sorry @garrett-eclipse you are right, I'm practicing :)

**Comment by garrett-eclipse** [comment]
No worries @benny-ben keep playing around its new users like you who help us find new issues
