### ISSUE TITLE
Using Grunt + Libsass in JointsWP?

### ISSUE THREAD

**Issue by firelite** [JeremyEnglert/JointsWP#37]
Hey,

JointsWP has been working great for my projects. 

I have been trying out the Grunt + Libsass workflow for faster sass compiling based on the instructions from http://foundation.zurb.com/docs/sass.html. and I am wondering what's the best method to get that going for JointsWP?  The CLI update function for Foundation is real nice too.  Can that work within JointsWP, as well?

Thanks!

**Comment by NRG-R9T** [comment]
I just started to fidle with this great theme and Grunt. For starters: What's the recommended or best way to use it together? For example to combine all Javascript files into one: all scripts are supposed to be located in scripts.js, right? if somebody would like to share a gruntfile.js for JointsWP, I'd really appreciate at this point.

**Comment by JeremyEnglert** [comment]
The scripts.js file is where you put all of your custom scripts - Foundation specific scripts are in the foundation.min.js file. Both are enqueued in the joints.php file. 

JointsWP 3 will support Grunt.js out of the box. The issue right now is making the theme flexible enough to use for any workflow. For example, if everyone was using Grunt (or even CodeKit), it would be really easy to setup the theme to minify and enqueue all scripts from one minified JS file. However, not everyone is using those tools. 

If you take a look at a lot of other blank themes, you'll notice they require specific workflows/tools - I don't want JointsWP to be like that. I want it to be flexible for almost any workflow. 

Side Note: Someone forked an old version of JointsWP to work with Grunt, but I can't find that link to save my life.

**Comment by NRG-R9T** [comment]
Thanks for your fast reply. It's really hard to serve many kings. ;-) 
I prefer flexibility too, as I'm looking into different tools oftenly to research as a journalist and to improve as a programmer.

I've found a [JointsWP child theme with a gruntfile.js](http://google.com)https://github.com/JoshEllinger/JointsWP-child/blob/master/Gruntfile.js), if that helps, but it's based on JointsWP 1, has Bourbon.io built in and I prefer autoprefixer.

**Comment by JeremyEnglert** [comment]
Gulp is now included in JointsWP 3. Grunt should also easily integrate into the platform. if someone wants to make a Grunt file that mimics the Gulp file, I will gladly include it with JointsWP.
