### ISSUE TITLE
Depreciation Warnings when compiling styles

### ISSUE THREAD

**Issue by gabrielbajada** [JeremyEnglert/JointsWP#370]
Hey @JeremyEnglert and all at JointsWP,

I've been using JointsWP for about 5 years now. Great work as always, guys!

I've got a little issue, does anyone know why I'm getting the below warnings? They're not hindering me from compiling the styles but I'm getting the warnings every time the styles compile. 

I installed the SASS version of JointsWP with npm, as instructed in the documentation.

Cheers,

Gabriel

> [10:04:45] Starting 'styles'...
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("shake")) instead.
> 
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("shake")) instead.
> 
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("spin")) instead.
> 
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("spin")) instead.
> 
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("wiggle")) instead.
> 
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("wiggle")) instead.
> 
> [10:05:12] Finished 'styles' after 27 s

**Comment by matirosero** [comment]
I'm getting the same warnings

**Comment by garrett-eclipse** [comment]
Hi @matirosero this is a duplicate of #371 which provides links and information on the issue. Cheers
