### ISSUE TITLE
Depreciation warnings when compiling styles

### ISSUE THREAD

**Issue by gabrielbajada** [JeremyEnglert/JointsWP#371]
Hey @JeremyEnglert and all at JointsWP,

I've been using JointsWP for about 5 years now. Great work as always, guys!

I've got a little issue, does anyone know why I'm getting the below warnings? They're not hindering me from compiling the styles but I'm getting the warnings every time the styles compile. 

I installed the SASS version of JointsWP with npm, as instructed in the documentation.

Cheers,

Gabriel

> [10:04:45] Starting 'styles'...
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("shake")) instead.
> 
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("shake")) instead.
> 
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("spin")) instead.
> 
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("spin")) instead.
> 
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("wiggle")) instead.
> 
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("wiggle")) instead.
> 
> [10:05:12] Finished 'styles' after 27 s

**Comment by garrett-eclipse** [comment]
Hi @gabrielbajada 

This is a foundation issue which has been resolved upstream;
Issue - https://github.com/zurb/motion-ui/issues/99
PR - https://github.com/zurb/motion-ui/pull/100

I wouldn't be worried about it as it's a warning and not a real issue as they indicated in the issue thread;
Reference - https://github.com/zurb/motion-ui/issues/99#issuecomment-375459392

If you want to try it they did suggest the following - `npm i zurb/motion-ui#master`
Reference - https://github.com/zurb/motion-ui/issues/99#issuecomment-382471773

Hope you have another 5 great years working with Joints ;)
