### ISSUE TITLE
Warning: printf(): Too few arguments if i remove get_the_author_posts_link(), from content-byline.php

### ISSUE THREAD

**Issue by bobbytv** [JeremyEnglert/JointsWP#376]
If I'm doing a 1 author blog and hence won't be needing the author name in the byline, what's the best way to remove that?

I tried just deleting 
`get_the_author_posts_link(),`

but then I get 

> Warning: printf(): Too few arguments in /opt/lampp/htdocs/bobby/wp-content/themes/bobby/parts/content-byline.php on line 11

And the categories won't render. Any advice on how to proceed? Thanks.

**Comment by garrett-eclipse** [comment]
Hi @bobbytv 

If you're removing a param from the printf you also have to remove the placeholder. So try this in your content-byline.php;
```
<p class="byline">
	<?php
	printf( __( 'Posted on %1$s - %2$s', 'jointswp' ),
		get_the_time( __('F j, Y', 'jointswp') ),
		get_the_category_list(', ')
	);
	?>
</p>
```

Hope that helps,
Cheers
