### ISSUE TITLE
cssnano vs gulp-clean-css

### ISSUE THREAD

**Issue by garrett-eclipse** [JeremyEnglert/JointsWP#379]
Moving the conversation from #333 about cssnano vs gulp-clean-css.

replying to @JeremyEnglert  
> Im still on the fence of cssnano vs gulp-clean-css. After doing some reading, it seems like people are moving away from CSSNano. But I need to investigate more.

I got the same feeling but can't find any evidence in posts or forums. I'll keep looking but here's some initial info. I haven't played with enough of either of them yet to have a preference myself. If anyone else does their opinion is appreciated (hence the ticket).

From NPM trends;
https://www.npmtrends.com/gulp-clean-css-vs-gulp-cssnano

cssnano
site - https://cssnano.co/
npm - https://www.npmjs.com/package/gulp-cssnano
git - https://github.com/ben-eb/gulp-cssnano

clean-css
site - https://jakubpawlowicz.github.io/clean-css/
npm - https://www.npmjs.com/package/gulp-clean-css
git - https://github.com/jakubpawlowicz/clean-css

**Comment by JoshEllinger** [comment]
;) might want to check your @ label @garrett-eclipse

**Comment by JeremyEnglert** [comment]
Webpack uses CSS Nano to minify assets by default. So unless anyone has an objection, lets stick with it.

**Comment by garrett-eclipse** [comment]
Good call @JeremyEnglert always good to stick with the default, and anyone needing to switch to clean-css can definitely do so
