### ISSUE TITLE
Webpack vs. Gulp

### ISSUE THREAD

**Issue by JeremyEnglert** [JeremyEnglert/JointsWP#381]
Should the next version of JWP use Webpack instead of Gulp?

Gulp is great. But everyone is moving towards Webpack and I'd hate to fall behind. 

For most users, it shouldn't make much of a difference as all of the changes happen "automagically". It's only advanced users who want to make config changes that will notice a difference.

**Comment by garrett-eclipse** [comment]
I agree this seems like the path forward.

**Comment by garrett-eclipse** [comment]
I've had good experiences with it, but I wouldn't say I'm experienced. Been looking for an excuse to learn it though, I'll play around and we can work out a gameplan for Gulp>Webpack feature migration

**Comment by JeremyEnglert** [comment]
I've made some solid progress. I have the Sass and JS files compiling right.

This tutorial was super helpful: https://taylor.callsen.me/using-webpack-4-and-sass-with-wordpress/

Currently trying to figure out a way to make it super easy for people who don't want to "learn" Webpack but want to be able to utilize it as a build tool.
