### ISSUE TITLE
Node sass stopped after upgrading to Mac Mojave

### ISSUE THREAD

**Issue by lenrooney** [JeremyEnglert/JointsWP#383]
Hi, I'm complete noob with node.js and sass workflow. I had everything installed and working fine for the past week or so, but last night I upgraded to Mac Mojave and `npm run watch` stopped compiling style.css. Watch still starts up and responds when my custom.scss file is saved, but style.css remains unchanged ... 

```
[Lens-27-iMac-3]$ npm run watch

> jointswp-sass@5.0.0 watch /Users/lenrooney/Websites/LenRooney-Site/lenrooney-wp/wp-content/themes/JointsWP
> gulp watch

[09:40:55] Using gulpfile ~/Websites/LenRooney-Site/lenrooney-wp/wp-content/themes/JointsWP/gulpfile.js
[09:40:55] Starting 'watch'...
[09:41:18] Starting 'styles'...
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("shake")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("shake")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("spin")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("spin")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("wiggle")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("wiggle")) instead.

[09:41:21] Finished 'styles' after 3.08 s

```
The depreciation warnings have always been there, even when it was working.

I've already tried `npm rebuild node-sass` and reinstalling (clean) node.js v10.13

Can anyone make any suggestions on how I might go about troubleshooting and fixing this?

TIA

**Comment by mlangone** [comment]
Have you tried the gulp.js fix? Remove your existing gulp.js file replace
with the one from the joints repo, rm rf node modules, npm install? If you
want to remove the warnings for wiggle let me know I will explain how to do
that I'd your not using the motion library.

ML

**Comment by lenrooney** [comment]
Thanks for help @mlangone! I followed your instructions and everything went well, except it turns out that sass is working after all. It's the strangest thing; style.css is being updated but its date created/ date modified are stuck at, November 7, 2018 at 10:41 PM. No matter how many times I update the file, the date and time modified on that file won't change. So when I was uploading it to the server I kept getting a warning about it being older than the existing file.

I've never seen this happen on a Mac before, I wouldn't have thought it possible on this filesystem. I've tried duplicating the file, and completely replacing it but every new iteration of that file is stuck on the same date/time. Strange, but I'm happy it is in fact working.

And yes, it would be awesome if you could explain how I could go about fixing the depreciation warnings! Thanks again!

Len

**Comment by garrett-eclipse** [comment]
Hi @lenrooney 

The timestamp issue seems to be a Gulp 4 issue;
https://github.com/gulpjs/gulp/issues/2193

There's a Gulp SASS issue as well;
https://github.com/dlmanning/gulp-sass/issues/706

Seems the best approach is to 'touch' the file in the pipeline so as to force the mtime update;
`.pipe(touch())  /* fix to update modified time */`

You'll need to add `gulp-touch-cmd` to your package.json or `npm install gulp-touch-cmd`
Then register in your gulpfile.js;
`var touch = require('gulp-touch-cmd');`
And finally pipe it in;
`.pipe(touch())  /* fix to update modified time */`

I've added PR #385 for JWP 5, @JeremyEnglert can you take a look and let me know if needs to be applied to JWP6.
*Len you can take a look at the PR to understand the update you'll need to make in your project.

Let me know if you have questions or other issues,
Cheers
P.S. As to the warnings @mlangone mentioned for motion-ui here's the thread on the issue;
https://github.com/zurb/motion-ui/issues/99
You may be able to simply remove `@include motion-ui-animations;` but if that's not enough this whole block seems to be the culprit;
```
@import  '~motion-ui/motion-ui';
@include motion-ui-transitions;
@include motion-ui-animations;
```

**Comment by lenrooney** [comment]
Thanks @mlangone @garrett-eclipse @JeremyEnglert ! Sorry for the delayed response, I had to deal with other projects.

I added the new gulpfile.js and package.json and reinstalled npm to my project. The date on my styles/style.css is now updating correctly.

I had trouble earlier finding the lines to comment out to stop the depreciated warnings, but the zurb/motion-ui#99 thread is really good at explaining my options on this. It's good to know that they are just warnings so I don't have to turn anything off or worry about them for now.

Thanks again. It's always tough jumping into a new workflow, especially when it requires Terminal commands and so many dependancies from multiple sources. Your help is really appreciated!

Len

**Comment by garrett-eclipse** [comment]
> I added the new gulpfile.js and package.json and reinstalled npm to my project. The date on my styles/style.css is now updating correctly.

Thanks for reporting back @lenrooney always nice to know a change works in the field.
 
> I had trouble earlier finding the lines to comment out to stop the depreciated warnings, but the [zurb/motion-ui#99](https://github.com/zurb/motion-ui/issues/99) thread is really good at explaining my options on this. It's good to know that they are just warnings so I don't have to turn anything off or worry about them for now.

Warnings always give me a panic too, especially when coming back to a project months/years later and dependencies have changed.

Good luck with your project. And happy holidays @mlangone enjoy
