### ISSUE TITLE
weblocal is missing in script npm

### ISSUE THREAD

**Issue by 9913103646** [JeremyEnglert/JointsWP#384]
npm ERR! missing script: weblocal

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2018-11-21T09_14_32_706Z-debug.log

**Comment by garrett-eclipse** [comment]
Hi @9913103646, JWP doesn't utilize weblocal so am going to close this issue as it sounds like a customization you've done.
That being said, if you want to share your gulpfile.js and package.json I can take a look for you. Most likely you'll need to declare weblocal in the package.json so it's install on `npm install` or you'll have to run `npm install -g weblocal` to install it globally. But from the error seems you're trying to use weblocal but it hasn't been installed on the project so is unavailable.
