### ISSUE TITLE
cannot find formidable package when i'm using node.js require method

### ISSUE THREAD

**Issue by Hicham95** [JeremyEnglert/JointsWP#388]
I have this packages  installed on 'C:\Users\Hicham\node_modules' as you see below ,the first package is formidable@1.21 which i want to include on my project but the issue is cannot find it I try to install formidable -global or standard and still the same.  
+-- formidable@1.2.1
+-- node-sass@4.10.0
| +-- async-foreach@0.1.3
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.1.1
| | +-- strip-ansi@3.0.1
| | | `-- ansi-regex@2.1.1 deduped
| | `-- supports-color@2.0.0
| +-- cross-spawn@3.0.1
| | +-- lru-cache@4.1.4
| | | +-- pseudomap@1.0.2
| | | `-- yallist@3.0.3
| | `-- which@1.3.1
| |   `-- isexe@2.0.0
| +-- gaze@1.1.3
| | `-- globule@1.2.1
| |   +-- glob@7.1.3 deduped
| |   +-- lodash@4.17.11 deduped
| |   `-- minimatch@3.0.4 deduped
| +-- get-stdin@4.0.1
| +-- glob@7.1.3
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | +-- once@1.4.0 deduped
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.3
| | +-- minimatch@3.0.4
| | | `-- brace-expansion@1.1.11
| | |   +-- balanced-match@1.0.0
| | |   `-- concat-map@0.0.1
| | +-- once@1.4.0
| | | `-- wrappy@1.0.2 deduped
| | `-- path-is-absolute@1.0.1
| +-- in-publish@2.0.0
| +-- lodash.assign@4.2.0
| +-- lodash.clonedeep@4.5.0
| +-- lodash.mergewith@4.6.1
| +-- meow@3.7.0
| | +-- camelcase-keys@2.1.0
| | | +-- camelcase@2.1.1
| | | `-- map-obj@1.0.1 deduped
| | +-- decamelize@1.2.0
| | +-- loud-rejection@1.6.0
| | | +-- currently-unhandled@0.4.1
| | | | `-- array-find-index@1.0.2
| | | `-- signal-exit@3.0.2
| | +-- map-obj@1.0.1
| | +-- minimist@1.2.0
| | +-- normalize-package-data@2.4.0
| | | +-- hosted-git-info@2.7.1
| | | +-- is-builtin-module@1.0.0
| | | | `-- builtin-modules@1.1.1
| | | +-- semver@5.6.0
| | | `-- validate-npm-package-license@3.0.4
| | |   +-- spdx-correct@3.0.2
| | |   | +-- spdx-expression-parse@3.0.0 deduped
| | |   | `-- spdx-license-ids@3.0.2
| | |   `-- spdx-expression-parse@3.0.0
| | |     +-- spdx-exceptions@2.2.0
| | |     `-- spdx-license-ids@3.0.2 deduped
| | +-- object-assign@4.1.1
| | +-- read-pkg-up@1.0.1
| | | +-- find-up@1.1.2
| | | | +-- path-exists@2.1.0
| | | | | `-- pinkie-promise@2.0.1 deduped
| | | | `-- pinkie-promise@2.0.1
| | | |   `-- pinkie@2.0.4
| | | `-- read-pkg@1.1.0
| | |   +-- load-json-file@1.1.0
| | |   | +-- graceful-fs@4.1.15 deduped
| | |   | +-- parse-json@2.2.0
| | |   | | `-- error-ex@1.3.2
| | |   | |   `-- is-arrayish@0.2.1
| | |   | +-- pify@2.3.0
| | |   | +-- pinkie-promise@2.0.1 deduped
| | |   | `-- strip-bom@2.0.0
| | |   |   `-- is-utf8@0.2.1
| | |   +-- normalize-package-data@2.4.0 deduped
| | |   `-- path-type@1.1.0
| | |     +-- graceful-fs@4.1.15 deduped
| | |     +-- pify@2.3.0 deduped
| | |     `-- pinkie-promise@2.0.1 deduped
| | +-- redent@1.0.0
| | | +-- indent-string@2.1.0
| | | | `-- repeating@2.0.1
| | | |   `-- is-finite@1.0.2
| | | |     `-- number-is-nan@1.0.1 deduped
| | | `-- strip-indent@1.0.1
| | |   `-- get-stdin@4.0.1 deduped
| | `-- trim-newlines@1.0.0
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8 extraneous
| +-- nan@2.11.1
| +-- node-gyp@3.8.0
| | +-- fstream@1.0.11
| | | +-- graceful-fs@4.1.15 deduped
| | | +-- inherits@2.0.3 deduped
| | | +-- mkdirp@0.5.1 deduped
| | | `-- rimraf@2.6.2 deduped
| | +-- glob@7.1.3 deduped
| | +-- graceful-fs@4.1.15
| | +-- mkdirp@0.5.1 deduped
| | +-- nopt@3.0.6
| | | `-- abbrev@1.1.1
| | +-- npmlog@4.1.2 deduped
| | +-- osenv@0.1.5
| | | +-- os-homedir@1.0.2
| | | `-- os-tmpdir@1.0.2
| | +-- request@2.88.0 deduped
| | +-- rimraf@2.6.2
| | | `-- glob@7.1.3 deduped
| | +-- semver@5.3.0 extraneous
| | +-- tar@2.2.1
| | | +-- block-stream@0.0.9
| | | | `-- inherits@2.0.3 deduped
| | | +-- fstream@1.0.11 deduped
| | | `-- inherits@2.0.3 deduped
| | `-- which@1.3.1 deduped
| +-- npmlog@4.1.2
| | +-- are-we-there-yet@1.1.5
| | | +-- delegates@1.0.0
| | | `-- readable-stream@2.3.6 deduped
| | +-- console-control-strings@1.1.0
| | +-- gauge@2.7.4
| | | +-- aproba@1.2.0
| | | +-- console-control-strings@1.1.0 deduped
| | | +-- has-unicode@2.0.1
| | | +-- object-assign@4.1.1 deduped
| | | +-- signal-exit@3.0.2 deduped
| | | +-- string-width@1.0.2
| | | | +-- code-point-at@1.1.0
| | | | +-- is-fullwidth-code-point@1.0.0
| | | | | `-- number-is-nan@1.0.1
| | | | `-- strip-ansi@3.0.1 deduped
| | | +-- strip-ansi@3.0.1 deduped
| | | `-- wide-align@1.1.3
| | |   `-- string-width@1.0.2 deduped
| | `-- set-blocking@2.0.0
| +-- request@2.88.0
| | +-- aws-sign2@0.7.0
| | +-- aws4@1.8.0
| | +-- caseless@0.12.0
| | +-- combined-stream@1.0.7
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.2
| | +-- forever-agent@0.6.1
| | +-- form-data@2.3.3
| | | +-- asynckit@0.4.0
| | | +-- combined-stream@1.0.7 deduped
| | | `-- mime-types@2.1.21 deduped
| | +-- har-validator@5.1.3
| | | +-- ajv@6.5.5
| | | | +-- fast-deep-equal@2.0.1
| | | | +-- fast-json-stable-stringify@2.0.0
| | | | +-- json-schema-traverse@0.4.1
| | | | `-- uri-js@4.2.2
| | | |   `-- punycode@2.1.1
| | | `-- har-schema@2.0.0
| | +-- http-signature@1.2.0
| | | +-- assert-plus@1.0.0
| | | +-- jsprim@1.4.1
| | | | +-- assert-plus@1.0.0 deduped
| | | | +-- extsprintf@1.3.0
| | | | +-- json-schema@0.2.3
| | | | `-- verror@1.10.0
| | | |   +-- assert-plus@1.0.0 deduped
| | | |   +-- core-util-is@1.0.2 deduped
| | | |   `-- extsprintf@1.3.0 deduped
| | | `-- sshpk@1.15.2
| | |   +-- asn1@0.2.4
| | |   | `-- safer-buffer@2.1.2 deduped
| | |   +-- assert-plus@1.0.0 deduped
| | |   +-- bcrypt-pbkdf@1.0.2
| | |   | `-- tweetnacl@0.14.5 deduped
| | |   +-- dashdash@1.14.1
| | |   | `-- assert-plus@1.0.0 deduped
| | |   +-- ecc-jsbn@0.1.2
| | |   | +-- jsbn@0.1.1 deduped
| | |   | `-- safer-buffer@2.1.2 deduped
| | |   +-- getpass@0.1.7
| | |   | `-- assert-plus@1.0.0 deduped
| | |   +-- jsbn@0.1.1
| | |   +-- safer-buffer@2.1.2
| | |   `-- tweetnacl@0.14.5
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- mime-types@2.1.21
| | | `-- mime-db@1.37.0
| | +-- oauth-sign@0.9.0
| | +-- performance-now@2.1.0
| | +-- qs@6.5.2
| | +-- safe-buffer@5.1.2
| | +-- tough-cookie@2.4.3
| | | +-- psl@1.1.29
| | | `-- punycode@1.4.1 extraneous
| | +-- tunnel-agent@0.6.0
| | | `-- safe-buffer@5.1.2 deduped
| | `-- uuid@3.3.2
| +-- sass-graph@2.2.4
| | +-- glob@7.1.3 deduped
| | +-- lodash@4.17.11
| | +-- scss-tokenizer@0.2.3
| | | +-- js-base64@2.4.9
| | | `-- source-map@0.4.4
| | |   `-- amdefine@1.0.1
| | `-- yargs@7.1.0
| |   +-- camelcase@3.0.0 extraneous
| |   +-- cliui@3.2.0
| |   | +-- string-width@1.0.2 deduped
| |   | +-- strip-ansi@3.0.1 deduped
| |   | `-- wrap-ansi@2.1.0
| |   |   +-- string-width@1.0.2 deduped
| |   |   `-- strip-ansi@3.0.1 deduped
| |   +-- decamelize@1.2.0 deduped
| |   +-- get-caller-file@1.0.3
| |   +-- os-locale@1.4.0
| |   | `-- lcid@1.0.0
| |   |   `-- invert-kv@1.0.0
| |   +-- read-pkg-up@1.0.1 deduped
| |   +-- require-directory@2.1.1
| |   +-- require-main-filename@1.0.1
| |   +-- set-blocking@2.0.0 deduped
| |   +-- string-width@1.0.2 deduped
| |   +-- which-module@1.0.0
| |   +-- y18n@3.2.1
| |   `-- yargs-parser@5.0.0
| |     `-- camelcase@3.0.0 extraneous
| +-- stdout-stream@1.4.1
| | `-- readable-stream@2.3.6
| |   +-- core-util-is@1.0.2
| |   +-- inherits@2.0.3 deduped
| |   +-- isarray@1.0.0
| |   +-- process-nextick-args@2.0.0
| |   +-- safe-buffer@5.1.2 deduped
| |   +-- string_decoder@1.1.1
| |   | `-- safe-buffer@5.1.2 deduped
| |   `-- util-deprecate@1.0.2
| `-- true-case-path@1.0.3
|   `-- glob@7.1.3 deduped
`-- upper-case@1.1.3

**Comment by garrett-eclipse** [comment]
Hello Hicham95,

Formidable isn't something that JointsWP employs in it's built suite so am going to close this issue as unrelated.

That being said I'll try to give you a hand irregardless.

To start you'll want to make sure to add formidable into your package.json;
https://github.com/JeremyEnglert/JointsWP/blob/master/package.json
*make sure to add it to the devDependencies like this;
"formidable": "^1.2.1",

Once it's in your package.json you'll want to update the gulpfile.js to require it;
https://github.com/JeremyEnglert/JointsWP/blob/master/gulpfile.js
*If you add in with the rest should look like this `formidable = require('formidable'),`
You can then setup your form code following their example;
https://www.npmjs.com/package/formidable

Once it's in your package.json re-install your project by removing the node_modules (`rm -rf node_modules`) and maybe remove package-lock.json. Then run `npm install` and finally `npm run build`.

Hope that helps,
Cheers

**Comment by Hicham95** [comment]
@garrett-eclipse  I get something new to know! thanks
 it’s helped me  I appreciate it

**Comment by garrett-eclipse** [comment]
No worries, always happy to help
