### ISSUE TITLE
Adding globbing 

### ISSUE THREAD

**Issue by emmigereb** [JeremyEnglert/JointsWP#390]
Could I get som help on adding globbing to the gulp file. I don´t manage to get it work. 
I tried https://www.npmjs.com/package/gulp-css-globbing and https://www.npmjs.com/package/gulp-sass-glob but none of the seems to work for me.

**Comment by JeremyEnglert** [comment]
Can you show an example of what you're trying to do? I thought Globbing just worked by default.
