### ISSUE TITLE
Using Timber / Twig with this theme

### ISSUE THREAD

**Issue by HongPong** [JeremyEnglert/JointsWP#395]
Looking at this nice theme, wondering if there is a good way to use Timber/Twig techniques with it instead of the standard PHP.
- https://github.com/timber/timber/

In other contexts I have enjoyed splitting the PHP away from the front templating. Timber is the premiere twig framework for WordPress AFAIK. It can be run as a plugin that then provides the required functions to themes:
- https://wordpress.org/plugins/timber-library/

Some other people tried earlier with this idea combining Timber and Foundation:

- https://github.com/mgmartel/timber-foundation
- https://github.com/gholme4/trunck_theme
- https://github.com/jim-at-jibba/timber-foundation-theme

Why Twig? as said here PHP wasn't intended for templating: 
- https://aristath.github.io/blog/using-twig-in-wordpress

One argument against doing this is that it requires composer to develop from Github as discussed here
- https://timber.github.io/docs/getting-started/setup/

Video tutorials are located here:
- https://timber.github.io/docs/getting-started/video-tutorials/

**Comment by Michael-Ashfield** [comment]
You can use timber/twig with this theme. Make anew folder called "Views" and put any twig files in there, you can add the context to a custom page template. This is how I do it on my sites, as long as you understand Timber.

**Comment by HongPong** [comment]
ok thanks for getting back to me!
