### ISSUE TITLE
Update to use the latest version of Foundation (6.5.3)

### ISSUE THREAD

**Issue by newtlabs** [JeremyEnglert/JointsWP#396]
Hi, I'm thinking of switching from FoundationPress to JointsWP for my next project. Please can you update to the latest version of Foundation? V 6.5.3 was released in January, cheers.

**Comment by mlangone** [comment]
Jeremy are you still going to maintain joints5  or are you going to focus
on joints6?

**Comment by JeremyEnglert** [comment]
I'll be updating JWP 5 today to the newest version of Foundation and to squash some open issues. But all new feature development will be on JWP6.

**Comment by JeremyEnglert** [comment]
Sass and CSS versions are now on 6.5.3.
