### ISSUE TITLE
Older sites built with Joints 5

### ISSUE THREAD

**Issue by easYnow** [JeremyEnglert/JointsWP#400]
Hi Guys,

I have some older sites I built using Joints 5

I now have to go back and make some style changes etc and I'm having issues running Gulp.

When running Gulp get the following - 

TypeError: gulp.start is not a function

Could anyone help with how I need to edit the gulpfile so styles will compile?

Are there any best practice tips for managing older instals of Joints5/ Gulp workflow.

Thanks in advance
Tom

**Comment by mlangone** [comment]
Gulp to build
Gulp watch to watch stiles and just
I think the readme has the commands in it

**Comment by easYnow** [comment]
Thanks Mike,

I'm familiar with all the gulp commands etc and have built a load of sites using Joints

When I run these commands in the terminal I get errors e.g  -

` TypeError: gulp.start is not a function
`

I guess what I'm really asking is how do people alter their gulpfile.js when running older versions of JointsWP?

Thanks
Tom

**Comment by garretthyder** [comment]
Hi @easYnow 

You're got two options here. 

Some backstory: In JWP 4.0 the gulp was expecting ^3.9.0 but w/ Gulp v4 the gulp.start command was replaced with gulp.task/gulp.parallel.

Option 1: Downgrade your gulp to 3.9.0 and your gulpfile will work again.

Option 2: Update your gulpfile.js to drop use of gulp.start.
In the original gulpfile here's the start section - https://github.com/JeremyEnglert/JointsWP/blob/4.0/gulpfile.js#L140-L143
In JWP 5 it's now `gulp.task('default', gulp.parallel('styles', 'scripts', 'images'));`
Source - https://github.com/JeremyEnglert/JointsWP/blob/master/gulpfile.js#L186
I believe you can just replace that section with the new line.

Note: If you've gone with alot of changes I would say just stick with JWP4 until a new project. Or start a clean JWP5 and migrate over your customizations.

Hope that's helpful,
Cheers

**Comment by easYnow** [comment]
Hi @garrett-eclipse 

Thanks for your suggestions and help on this! I've gone with Option 1 and the styles are all compiling now which solves my issue.

Really appreciate your help.

Cheers
Tom

**Comment by garretthyder** [comment]
No worries Tom, glad that helped.
