### ISSUE TITLE
Order of compiled scripts

### ISSUE THREAD

**Issue by dmcgrew** [JeremyEnglert/JointsWP#403]
In my gulpfile.js I have a couple addtional .js files being loaded in. When the scripts compile they the always get added to the top of the scripts.js file for some reason. No matter what order I put them into the gulpfile the order in the compiled .js stays the same. Why is that? Is there a way to make it compile in the same order that I have them listed in the gulpfile?

In the example below custom2.js always get placed at the very top of the compiled scripts.js file.

`scripts: [
		// Lets grab what-input first
	    'node_modules/what-input/dist/what-input.js',

		// Foundation core - needed if you want to use any of the components below
		FOUNDATION + '/dist/js/plugins/foundation.core.js',
		FOUNDATION + '/dist/js/plugins/foundation.util.*.js',

		// Pick the components you need in your project
		FOUNDATION + '/dist/js/plugins/foundation.abide.js',
		FOUNDATION + '/dist/js/plugins/foundation.accordion.js',
		FOUNDATION + '/dist/js/plugins/foundation.accordionMenu.js',
		FOUNDATION + '/dist/js/plugins/foundation.drilldown.js',
		FOUNDATION + '/dist/js/plugins/foundation.dropdown.js',
		FOUNDATION + '/dist/js/plugins/foundation.dropdownMenu.js',
		FOUNDATION + '/dist/js/plugins/foundation.equalizer.js',
		FOUNDATION + '/dist/js/plugins/foundation.interchange.js',
		FOUNDATION + '/dist/js/plugins/foundation.offcanvas.js',
		FOUNDATION + '/dist/js/plugins/foundation.orbit.js',
		FOUNDATION + '/dist/js/plugins/foundation.responsiveMenu.js',
		FOUNDATION + '/dist/js/plugins/foundation.responsiveToggle.js',
		FOUNDATION + '/dist/js/plugins/foundation.reveal.js',
		FOUNDATION + '/dist/js/plugins/foundation.slider.js',
		FOUNDATION + '/dist/js/plugins/foundation.smoothScroll.js',
		FOUNDATION + '/dist/js/plugins/foundation.magellan.js',
		FOUNDATION + '/dist/js/plugins/foundation.sticky.js',
		FOUNDATION + '/dist/js/plugins/foundation.tabs.js',
		FOUNDATION + '/dist/js/plugins/foundation.responsiveAccordionTabs.js',
		FOUNDATION + '/dist/js/plugins/foundation.toggler.js',
		FOUNDATION + '/dist/js/plugins/foundation.tooltip.js',

		// Place custom JS here, files will be concantonated, minified if ran with --production
		'assets/scripts/js/**/*.js',
		'assets/scripts/custom1.js',
		'assets/scripts/custom2.js'
    ],`

**Comment by garretthyder** [comment]
Hi @dmcgrew 

I see what you mean there it's pretty sporadic in that setup. If you want to keep them at the /scripts level you can look into some of the solutions posted here;
https://stackoverflow.com/questions/21961142/concat-scripts-in-order-with-gulp

Myself I place custom scripts into the `assets/scripts/js` folder with at `#-` prefix for ordering. This works nicely for myself and then I don't need to constantly update the gulpfile. You can go that route as well without any additional configuration beyond creating and naming the files.

I hope that helps, if you do a custom solution would love for you to share.

Cheers
