### ISSUE TITLE
The Future

### ISSUE THREAD

**Issue by nitrokevin** [JeremyEnglert/JointsWP#408]
Sorry I know this isn't an issue, but with FoundationPress discontinued and Foundation itself in a bit of a hiatus, what is the future of JointsWP?

**Comment by ifrountas** [comment]
@nitrokevin The last response of Jeremy about this was https://twitter.com/JeremyEnglert/status/1141416903115603968
I'm following this thread too :)

**Comment by nitrokevin** [comment]
Thank you that's very helpful, any idea when the non-foundation JointsWP is going to be out?

**Comment by aibrean** [comment]
Foundation isn't dead.. https://github.com/foundation/foundation-sites/issues/11767#issuecomment-548601283

**Comment by JeremyEnglert** [comment]
> Foundation isn't dead.. [foundation/foundation-sites#11767 (comment)](https://github.com/foundation/foundation-sites/issues/11767#issuecomment-548601283)

Correct. Not dead, but it most likely will not be a part of Joints' future. More coming soon on this.
