### ISSUE TITLE
NPM Install issue

### ISSUE THREAD

**Issue by vkalyanababu** [JeremyEnglert/JointsWP#409]
Hi,

I'm unable to run the command npm install and getting below error. Kindly help resolve the same.

node version - v10.16.3
npm version - 6.9.0
OS - Windows 10 Enterprise

**Error details:**
> node-sass@4.10.0 install G:\pre-dev\NWL\Static\frontend\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-64_binding.node":

tunneling socket could not be established, statusCode=407

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.10.0 postinstall G:\pre-dev\NWL\Static\frontend\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe G:\pre-dev\NWL\Static\frontend\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:80:29)
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:89:16
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:80:29)
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:89:16
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\which\\which.js:13:12)\n    at F (G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\which\\which.js:68:19)\n    at E (G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\which\\which.js:80:29)\n    at G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\which\\which.js:89:16\n    at G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\isexe\\index.js:42:5\n    at G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:80:29)
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:89:16
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:80:29)
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\which\which.js:89:16
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at G:\pre-dev\NWL\Static\frontend\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\which\\which.js:13:12)\n    at F (G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\which\\which.js:68:19)\n    at E (G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\which\\which.js:80:29)\n    at G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\which\\which.js:89:16\n    at G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\isexe\\index.js:42:5\n    at G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (G:\pre-dev\NWL\Static\frontend\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (G:\pre-dev\NWL\Static\frontend\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at G:\pre-dev\NWL\Static\frontend\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "G:\\NWL\\Solutions\\NWG.Azure.ThinkDigital\\pre-dev\\NWL\\Static\\frontend\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd G:\pre-dev\NWL\Static\frontend\node_modules\node-sass
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN rollback Rolling back source-map@0.4.4 failed (this is probably harmless): EPERM: operation not permitted, lstat 'G:\pre-dev\NWL\Static\frontend\node_modules\scss-tokenizer\node_modules'
npm WARN is-in-viewport@3.0.4 requires a peer of jquery@>1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN unminified-webpack-plugin@2.0.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xyz\AppData\Roaming\npm-cache\_logs\2019-10-25T10_42_13_039Z-debug.log

Thanks,
Kalyan

**Comment by garretthyder** [comment]
Hi @vkalyanababu it appears you're unable to download from github.com, can you access it directly? You may need to setup a tunneling socket as the logs mentioned. Closing as this isn't related to the theme itself, if your issues persist I would suggest opening a thread on the npm community forum;
https://npm.community/

Here's the relevant part of your log message;
```
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-64_binding.node":

tunneling socket could not be established, statusCode=407

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

  export HTTP_PROXY=http://example.com:1234
or configure npm proxy via

  npm config set proxy http://example.com:8080
```
