### ISSUE TITLE
How to edit menu items

### ISSUE THREAD

**Issue by SaraCookHE** [JeremyEnglert/JointsWP#416]
I've inherited a WordPress site that uses JointsWP and i'm at a loose end as to how to edit menu items. It's not using a menu made in Appearance > Menus, as none exist. In the template it says:

```
<div class="top-bar-right show-for-medium">
		<?php joints_top_nav(); ?>	
	</div>
	<div class="top-bar-right float-right show-for-small-only">
		<ul class="menu">
			<!-- <li><button class="menu-icon" type="button" data-toggle="off-canvas"></button></li> -->
			<li><a data-toggle="off-canvas"><?php _e( 'Menu', 'jointswp' ); ?></a></li>
		</ul>
	</div>
```

But i'm not sure how to add/remove/edit items in the menu?

**Comment by garretthyder** [comment]
Hi @SaraCookHE 

The `joints_top_nav` lives in JointsWP/functions/menu.php. Take a look and see if they customized it as it should just use the `main-nav` theme_location. Doesn't appear there's a fall back so it should be tied to an existing Menu. If not maybe they customized the functionality or is defaulting to all top-level pages. 

You can create a menu and associate it to 'The Main Menu' location to control the menu on a standard install.

Going to close as it's not really a bug, but happy to keep helping you on this thread.
