### ISSUE TITLE
Range Slider

### ISSUE THREAD

**Issue by JPetroviak** [JeremyEnglert/JointsWP#418]
Foundation 6.2 added support for native HTML5 range sliders:
https://get.foundation/sites/docs/slider.html#native-range-slider

This should be included.

**Comment by JeremyEnglert** [comment]
Unfortunately, as Foundation is basically dead, I'm not making many more changes to this branch. If you're able to get it added and submit a pull request, I'd be glad to get it merged.

Be sure to check out the new version of JointsWP, which is powered by webpack and Framework free: https://github.com/JeremyEnglert/JointsWP/tree/6.0-dev
