### ISSUE TITLE
What's the closest alternative?

### ISSUE THREAD

**Issue by skjerns** [JeremyEnglert/JointsWP#426]
We're remodelling our website and I inherited a site using JointsWP.

However given that there are no updates anymore I wanted to ask what alternative to this theme you can recommend?

**Comment by JeremyEnglert** [comment]
Foundation is dead. If you want to use JointsWP sans Foundation, check out the 6.0 beta branch. No documentation yet, but the README should get you up and going.

**Comment by JeremyEnglert** [comment]
PS - if you inherited a site and you don't plan on rebuilding it, just keep using JointsWP. If you're planning on rebuilding it, use whatever you'd normally use.
