### ISSUE TITLE
Foundation is ALIVE! v6.7.1 released and counting.

### ISSUE THREAD

**Issue by mrscharf** [JeremyEnglert/JointsWP#427]
Hello all! I decided to revisit the Foundation Github repo as I like to do on occasion, and what a surprise it is being worked on once again! ZURB is out of the picture now, and there have been many recent commits. The discussion board is talking about what to keep and what to drop, plans for future improvements are materializing, bugs are being squashed etc. The version is at 6.7.1 and it looks like things will be progressing once again with v7 being discussed as well. This is great news as I really enjoyed working with Foundation. So the question is, in light of this news will @JeremyEnglert be retrofitting JointsWP for v6.7.1 and continuing development?

**Comment by JeremyEnglert** [comment]
Foundation is dead. I wouldn't build anything new on it (and haven't in quite some time). I wouldn't get too excited about the new release. The community of developers ran from the project after a new lead was forced into the project who doesn't understand how open source, community driven projects work. Sorry, but this just isn't worth anyones time.
