### ISSUE TITLE
Detached admin bar on mobile resolutions

### ISSUE THREAD

**Issue by ple103** [JeremyEnglert/JointsWP#46]
I previewed the blank theme in a mobile resolution (320 x 480) and noticed that admin bar is fixed, but not fixed to the very top of the screen.

![Detached admin bar](https://i.imgur.com/u0ATHxQ.png)

Applying the following CSS will fix the issue, but I am unsure if this affects anything else:
```
#wpadminbar {
   position: fixed
}
```

**Comment by flumra** [comment]
Thanks!

**Comment by JeremyEnglert** [comment]
This no longer appears to be an issue. Closing.
