### ISSUE TITLE
Top-bar Toggle no working on iPhone

### ISSUE THREAD

**Issue by jkinley** [JeremyEnglert/JointsWP#70]
I touch but no off-canvas menu appears.

**Comment by sofad** [comment]
open 
partials/nav-top-offcanvas.php
and change line 21 


```html
<a class="left-off-canvas-toggle menu-icon" ><span></span></a>
```
to

```html
<a class="left-off-canvas-toggle menu-icon" href="#" ><span></span></a>
```

_tested with wordpress 4.1 and safari iOS 7.0.2_

**Comment by JeremyEnglert** [comment]
This has been resolved.

**Comment by gabrielbajada** [comment]
Awesome, I've been trying to solve this problem for the past few days!

Thanks!
