### ISSUE TITLE
Images Markdown as Attachement, not Figure?

### ISSUE THREAD

**Issue by NRG-R9T** [JeremyEnglert/JointsWP#73]
The images in the loop and the content are marked as attachement, not figure (and figcaptions)? 

see info: https://developer.mozilla.org/en/docs/Web/HTML/Element/figure

If that's the case, what lead to that decision?. :-)

**Comment by JeremyEnglert** [comment]
Can you point me to the area of the code you are referencing? I don't see anything with "Attachment" in Joints.

Thanks!

**Comment by NRG-R9T** [comment]
on Post Thumbnails, I found the answer it in the wordpress codex http://codex.wordpress.org/Function_Reference/the_post_thumbnail

the reason I've wirote this was motivated as a feature request: i don't find images marked as figure and caption as figcaption by default, but I could be wrong.

**Comment by JeremyEnglert** [comment]
Are you talking about the "attachment-full" class that is added to the featured images?

**Comment by NRG-R9T** [comment]
I'm talking about the markup of the images in posts. HTML5 provides "figure" and "figcaption", while I get with JointsWP something like <div id="attachment_XXX" class="wp-caption">

http://www.w3schools.com/tags/tag_figure.asp
http://www.w3schools.com/tags/tag_figcaption.asp

I just haven't "figured" it out yet, how to get that done ;)

**Comment by NRG-R9T** [comment]
It's not really an Issue, just to be clear. Everything works, I just can't find the part in the theme, where the pictures for single posts are pulled from. for example, I'd like to adjust the color of the caption, but not only that, also to delete the padding that .wp-caption adds around the image inside the single post. problem is, every image has a different ID like ```<div id=attachment_148>```

**Comment by JeremyEnglert** [comment]
This is how WordPress outputs images - so it's not JointsWP specific. I'm sure you can modify it using action hooks.

If you want to change the styling of the caption, simply target the wp-caption class instead of the attachment ID.

I'm closing this as it isn't a JointsWP specific issue, but feel free to ask additional questions if needed.
