### ISSUE TITLE
Topbar .sticky and .sticky Post

### ISSUE THREAD

**Issue by jfelient** [JeremyEnglert/JointsWP#74]
Hi!

First, Big Thanks Jeremy for putting this great starter theme.

I ran across a problem with my current project that requires the use of the WordPress sticky post function which is a problem when using the sticky function for topbar.

I changed the sticky class name in _settings.scss
// Sticky Class
$topbar-sticky-class: ".sticky-bar";

Also tried a few things like adding "data-options" and in the foundation.topbar.js changing the sticky_class : 'sticky-bar',

I looked at the documentation and researched the issue and I still have a problem. Any thoughts or ideas?

**Comment by JeremyEnglert** [comment]
This will be fixed in JointsWP 3. There are a few different options for fixing it:

1. Change the name in the _settings.scss file and remove the global import in this file (it shouldn't be there anyway).

2. Change the WP sticky class name. Check out the second to last function here: https://github.com/JeremyEnglert/JointsWP/blob/JointsWP-3/assets/functions/cleanup.php

**Comment by jfelient** [comment]
Thanks, Jeremy!

I will give the first a try and see how it works out. I was afraid of removing the global import in the _settings.scss.

I did look at the second option and because I am planning on submitting this to WordPress theme repository it might get rejected. Also, changing that function might cause plugins that rely on the sticky post class issues. I will double check with the theme review team just to be sure.

**Comment by jfelient** [comment]
Okay, the first part did work for me either....
When I first removed the global import CodeKit shot out a lot of scss errors to a few items that I had uncommented. After all of that, it was 'No Dice'.

The second part worked out just fine. And because it is using a filter it is just fine to pass the theme review. 

Thanks for the help!

**Comment by jfelient** [comment]
It looks like you are rebuilding JointsWP. Are you planning on adding the child-theme functionality?

**Comment by JeremyEnglert** [comment]
I don't think so. For the most part, the theme should be pretty "child theme friendly". Is there something specific you were looking for?

When it comes to "developer themes" like JointsWP, child-theme functionality becomes really tricky. You can read more about it on the FAQs:
http://jointswp.com/about/

There really isn't much benefit to using a child theme with JointsWP. You can always easily update the Foundation version.
