### ISSUE TITLE
Add next/previous post navigation to loop-single.php? 

### ISSUE THREAD

**Issue by nicdford** [JeremyEnglert/JointsWP#76]
Any thoughts on adding next/previous post navigation to individual posts above comments?

**Comment by JeremyEnglert** [comment]
The posts_nav_link function should do the trick.

http://codex.wordpress.org/Function_Reference/posts_nav_link

**Comment by JeremyEnglert** [comment]
Closing this as it isn't necessarily an issue. But feel free to comment back if you have any questions.

**Comment by nicdford** [comment]
I was thinking more of a feature request, I only mentioned it because I noticed _s has posts_nav_link baked in and thought it may be helpful to others on joints

**Comment by JeremyEnglert** [comment]
In that case, I'll reopen this back up. I think thats a good idea, I'll get it in queue for JointsWP 3.

**Comment by nicdford** [comment]
Woo excited to give JointsWP 3 a go

**Comment by JeremyEnglert** [comment]
A year later, this has been added. :)

https://github.com/JeremyEnglert/JointsWP/commit/444aa98326307a54937f42b5820efac7eb9f88fa
