### ISSUE TITLE
Block Grid Spacing

### ISSUE THREAD

**Issue by gabrielbajada** [JeremyEnglert/JointsWP#77]
Hello again,

I came across this and thought I should let you know.

In the settings.scss file, the column gutter is set to `// $column-gutter: rem-calc(30);`, while the block grid default spacing is set to `// $block-grid-default-spacing: rem-calc(20);`. 

I'm not sure if this was done on purpose or not, but I was stuck for a while trying to figure out why things weren't aligning properly.

Anyway, thought i should let you know.

Cheers,

Gabe

**Comment by JeremyEnglert** [comment]
@gabrielbajada I think that is how Foundation comes out-of-the-box. 

https://github.com/zurb/foundation/blob/master/scss/foundation/_settings.scss
