### ISSUE TITLE
Blank title on home.

### ISSUE THREAD

**Issue by DeepSilver** [JeremyEnglert/JointsWP#8]
Demo site homepage has empty title.
http://jointswp.com/demo/

**Comment by JeremyEnglert** [comment]
This will be fixed in JointsWP 3.

**Comment by senlin** [comment]
glad to see that things are still in development, exactly one year after my message I get a reply!

**Comment by JeremyEnglert** [comment]
I didn't even realize it was exactly one year - kinda cool!

WordPress actually just recently addressed this issue with the 4.1 release. Check out the details here:
http://themeshaper.com/2015/01/27/whats-new-in-wordpress-4-1/

**Comment by senlin** [comment]
title is now part of theme support, I already added it to my theme: https://github.com/senlin/soblossom/commit/8f705609ed39f71af2bc705f10888a2d63d97849

**Comment by JeremyEnglert** [comment]
This was in JointsWP 3. Closing. :+1:
