### ISSUE TITLE
cleanup of translation.php

### ISSUE THREAD

**Issue by mikkelbreum** [JeremyEnglert/JointsWP#80]
In Branch JointsWP-3 In the file assets/translation/translation.php:

What is the purpose of the lines

    $locale = get_locale();
    $locale_file = get_template_directory() ."/assets/translation/$locale.php";
    if ( is_readable($locale_file) ) require_once($locale_file);

Why not remove that part and simply rely on the .po/.mo translation files?

Also I think the whole thing should be hooked to after_setup_theme, see patch  #79

**Comment by JeremyEnglert** [comment]
This was fixed with your patch - huge thanks!
