### ISSUE TITLE
Fatal error when trying to preview or activate theme

### ISSUE THREAD

**Issue by wuworkshop** [JeremyEnglert/JointsWP#81]
I just downloaded the Sass version from http://jointswp.com/ and when I try to preview or activate the theme, I get the following Fatal Error message:

**Fatal error:** Call to undefined function wp_get_theme() in **/var/www/html/wp-content/themes/jointswp/library/joints.php** on line **111**

Any ideas? Also, is there a minimum version of WordPress I need to use? I'm stuck with using WordPress 3.2.1 with no option to upgrade.

**Comment by JeremyEnglert** [comment]
It appears that wp_get_theme() was introduced in 3.4. Have you tried removing that from joints.php? That may fix the issue.

How come your stuck on 3.2.1? Can you do a manual upgrade?

**Comment by wuworkshop** [comment]
Whoa, thanks for the quick reply! Commenting out that line did indeed get rid of the fatal error message. You, sir, are the man! :thumbsup:

I'm stuck with 3.2.1 because the previous dev team had modified WP core so upgrading wouldn't really be all that simple to do.
