### ISSUE TITLE
Warning message JointsWP search

### ISSUE THREAD

**Issue by eleirgulen** [JeremyEnglert/JointsWP#83]
Installed a fresh installation of JointsWP today on php 5.3.6

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'joints_wpsearch' not found or invalid function name in /Users/flerekunder/wpsites/webcode2/wwwroot/wp-includes/plugin.php on line 213

**Comment by JeremyEnglert** [comment]
Looks like an old function stuck around. This has been fixed.
