### ISSUE TITLE
Where did the sass files go?!

### ISSUE THREAD

**Issue by gabrielbajada** [JeremyEnglert/JointsWP#84]
Hey Jeremy,

Looks like there was a major update to JointsWP. It's great to see how this theme keeps improving!

One little thing (especially for a newbie like me). Where did the sass files go?! I used to do all my customisations in small.scss, all the way up to xxlarge.scss. I'm a little lost as to where I go from here. Is it just a case of me adding them back to style.scss, or do you have a smarter/better solution to my dilemma.

Please let me know,

Thanks,

Gabriel

**Comment by JeremyEnglert** [comment]
Hi Gabriel,

I'm going to be adding this to the documentation, as it is probably one of the larger changes to JointsWP.

You're 100% correct - the small.scss, medium.scss, large.scss, etc, etc, are all gone. The problem with this setup was that you would need to jump between multiple files to make small changes. 

So instead of having to re-write your classes in each stylesheet, you can do something like this:

```
.widget {
	padding: 0 5px
	@media #{$medium-up} {
		padding: 0 10px;
	}
}
```
I hope this makes sense - let me know if you have any questions!

**Comment by gabrielbajada** [comment]
Ah nice. I see what you did there. Awesome as always.

Thanks.

Gabe

On Friday, 12 June 2015, Jeremy Englert <notifications@github.com> wrote:

> Hi Gabriel,
>
> I'm going to be adding this to the documentation, as it is probably one of
> the larger changes to JointsWP.
>
> You're 100% correct - the small.scss, medium.scss, large.scss, etc, etc,
> are all gone. The problem with this setup was that you would need to jump
> between multiple files to make small changes.
>
> So instead of having to re-write your classes in each stylesheet, you can
> do something like this:
>
> .widget {
>     padding: 0 5px
>     @media #{$medium-up} {
>         padding: 0 10px;
>     }
> }
>
> I hope this makes sense - let me know if you have any questions!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JeremyEnglert/JointsWP/issues/84#issuecomment-111536113>
> .
>


-- 

Gabriel Bajada
______________________________________________

(+356) 7978 4544                            gabrielbajada.com

Download vCard <http://www.gabrielbajada.com/gabriel-bajada.vcf>. Find me
on Facebook <http://facebook.com/gabrielbajada/>, Twitter
<http://twitter.com/gabrielbajada> & LinkedIn
<http://mt.linkedin.com/in/gabrielbajada>.

**Comment by JeremyEnglert** [comment]
:+1:
