### ISSUE TITLE
When wrapping divs with an anchor, my html gets altered

### ISSUE THREAD

**Issue by tsmith0511** [JeremyEnglert/JointsWP#87]
I love your theme, I've used it many times and the new version is amazing. Yay gulp! However, when I started to build a section where I need to wrap anchors around some divs, the anchor doesn't stay wrapped around them once I put it through wordpress's editor. It also was adding a different class to a nested anchor in one of those divs. I tried it with span tag and that seemed to help, however, the anchor wouldn't stayed wrapped around another anchor. 

http://192.168.1.41:3000/pierres/

This is my html:
![my_html](https://cloud.githubusercontent.com/assets/7408294/8389978/b40d5c28-1c34-11e5-9569-99476d6b723b.png)

And this is what wordpress spits out:
![wordpress_html](https://cloud.githubusercontent.com/assets/7408294/8389980/b8392ac0-1c34-11e5-8121-dfc1cdcbea09.png)

Please let me know if you have any ideas why this is happening. 

Thanks for the amazing theme!

**Comment by jawinn** [comment]
Having an anchor wrapped in another anchor unfortunately isn't valid HTML. The WordPress editor is probably not handling that well. I'd see what you can do to avoid the nested anchors (using a span like you mentioned?). 

I don't think this would be an issue with the theme itself—I don't believe the theme is modifying the TinyMCE editor at all.

**Comment by JeremyEnglert** [comment]
@jawinn is correct. The WordPress editor is a fickle beast when using HTML. The theme itself doesn't make any modifications to the TinyMCE editor.

To be completely sure, can you try the same chunk of code in a default theme?
