### ISSUE TITLE
CSS source maps

### ISSUE THREAD

**Issue by altjon** [JeremyEnglert/JointsWP#88]
Gulp is great but it is not updating the css map files under the folder "maps". 
It looks like it's missing some configuration in the gulpfile.js and also gulp-sourcemaps is not found!

It would be great fixing it because working without css map files is painful :( 

Also, please bring back the header image function (every website needs a logo, not just text)

Thanks

**Comment by JeremyEnglert** [comment]
Let me take a look at the source map issue and find a fix.

I'm not sure which "header image function" you are referring to. I don't believe this has ever been a part of JointsWP.

**Comment by altjon** [comment]
Hahaha, maybe it was wrong saying "bring it back", I have never used Jointswp before. I am going through different start themes based on Foundation and I have to say that yours is my favourite so long :) 
It has very clean and nice folder structure, easy to understand and further develop.

Anyway, the header image function could be nice including in the theme (you know, under the Site Title & Tagline settings in the admin) It is very easy :)

Btw, can you confirm that Languages/translation are working!? I have tested and it seems that it's not working as it should :(

Thanks again :)
![header_image](https://cloud.githubusercontent.com/assets/13140236/8471381/d5f6e356-2097-11e5-96e2-3a1d4e6f1fda.PNG)

**Comment by JeremyEnglert** [comment]
@altjon, something seems to be throwing an error. I'm looking into it.

**Comment by altjon** [comment]
Well, I see gulpfile.js is missing this part:

gulp.task('javascript', function() {
  gulp.src('src/**/*.js')
    .pipe(sourcemaps.init())
    .pipe(sourcemaps.write('../maps'))
    .pipe(gulp.dest('dist'));
});

Of course, this is just an example for "javascript" but you have to change it to "style" and fix the paths :)
I don't think source maps works for minified css files so I guess you have to call the normal style.css.

I have only a few days working with wordpress, scss and gulp so everything I say can be wrong but just trying to help ;)

**Comment by JeremyEnglert** [comment]
Something in one of the Sass files throws an error. I'm trying to narrow it down.

For some odd reason, the minified.css files add the sourcemap without issue - but obviously, that sourcemap would be useless.

**Comment by pablopaul** [comment]
I am not sure why a sourcemap for a minified file should be useless? Here they are doing this:
https://github.com/roots/sage/blob/master/gulpfile.js

**Comment by titaniumbones** [comment]
Hey Jeremy, just wondering if source maps have been enabled in current gulp? I'm afraid I know very little about gulp; tried blindly adding: 
.pipe(sourcemaps.init())
.pipe(sourcemaps.write('../maps')) 

at line 28 of gulpfile.js, but didn't notice any map files being produced. Suggestions? Thanks as always!

**Comment by JeremyEnglert** [comment]
Sourcemaps for JS and CSS minified files were added today. Closing.
