### ISSUE TITLE
archive-grid on archive

### ISSUE THREAD

**Issue by metascode** [JeremyEnglert/JointsWP#92]
I've noticed that the post query on the "archive-grid" does not behave as expected. I have set my archive.php style to "archive-grid" but it displays all posts rather than filtering the expected category, tag etc.

I have also set to the same on my index.php but didn't notice a problem as I was expecting to see all posts.

**Comment by JeremyEnglert** [comment]
@metascode, check out this thread: https://github.com/JeremyEnglert/JointsWP/issues/90

Does that help any?

**Comment by JeremyEnglert** [comment]
This has been fixed in the upcoming version (3.5).

Simply remove the first 8 lines in loop-archive-grid.php.
