### ISSUE TITLE
Fixed topbar transparent untill scroll

### ISSUE THREAD

**Issue by Erehr** [JeremyEnglert/JointsWP#95]
Was looking how to get effect of fixed transparent topbar that get back it's colors when scrolled down. So far i managed to make it work but only on static pages and not blog/post. I don't really want it on blog/post anyway but it's background is still transparent after scrolling.

So far i have (in nav-top-topbar.php):

<div class="contain-to-grid fixed transparent"> 

<script type="text/javascript">
  $(document).ready(function(){
    if($('body').hasClass('transparent')){
      $('.f-topbar-fixed').css('padding-top', '0px');
        $(function() {
    $(window).scroll(function() {
        var scroll = $(window).scrollTop();

        if (scroll >= 300) {
            header.addClass('opaque');
        } else {
            header.removeClass('opaque');
        }
    });
});
    }
  });
</script>  

and in css transparent class has background-color: transparent and .opaque my standard colors. 
Can somehow class .transparent be always removed only from blog and post pages?

**Comment by JeremyEnglert** [comment]
Specific classes get added to the HTML/BODY elements depending which page you're on. You can use CSS to target those specific classes.
