### ISSUE TITLE
nav-top-offcanvas action issue

### ISSUE THREAD

**Issue by ckegelman** [JeremyEnglert/JointsWP#99]
The offcanvas menu does not go away when the menu changes back to default upon making the page wider. 

This can be view at http://jointswp.com/demo/ 

Issue is in:

Mac
  Chrome Version 44.0.2403.155 (64-bit)
  Firefox 39.0.3

**Comment by ckegelman** [comment]
And I found a fix:

line 26:

remove the class "show-for-small-only"

**Comment by JeremyEnglert** [comment]
It looks like this is default behavior for Foundation, however, your fix is a better fallback than what is currently inplace (which ends up showing a blank menu).

This will be updated in 3.5.
